/**
 * mm_asset_loader.cpp - MM Asset Detection and Loading
 *
 * Detects and loads assets from mm.o2r (generated by 2Ship2Harkinian Keiichi Alfa 4.0.0+)
 * This allows Transformation Masks to use actual MM models, audio, and animations.
 *
 * DEPENDENCY: 2Ship2Harkinian Keiichi Alfa 4.0.0 or later
 * https://github.com/HarbourMasters/2ship2harkinian/releases/tag/4.0.0
 *
 * Users must:
 * 1. Own a legal copy of Majora's Mask (US 1.0 or US GC)
 * 2. Run 2Ship2Harkinian to extract mm.o2r from their ROM
 * 3. Place mm.o2r in the same folder as soh.exe (alongside oot.o2r)
 *
 * NO RECOMPILATION NEEDED - just drop mm.o2r and enable the feature.
 */

#include "mm_asset_loader.h"
#include "mods/sound_translator/mm_audio_sfx.h" // MM SFX engine (Tier C vanilla port)
#include <filesystem>
#include <cstring>
#include <cmath>
#include <cstdio>
#include <exception>
#include <unordered_map>
#include <vector> // was transitively via OTRGlobals.h before upstream #6636 cleanup
#include <libultraship/libultraship.h>
#include <libultraship/log/luslog.h>
#include <SDL2/SDL.h>
#include "soh/OTRGlobals.h"
#include "soh/GameVersions.h"
#include "soh/ResourceManagerHelpers.h"
#include "soh/resource/type/Text.h"
#include "functions.h"           // For Audio_SetFontInstrument, AudioLoad_IsFontLoadComplete
#include "message_data_static.h" // MessageTableEntry struct

// SoH globals that hold pointers into Text-resource std::string buffers. After
// SetArchives → ResetVirtualFileSystem unloads+reloads every archive, those
// buffers are reallocated and these pointers dangle. We null them so the
// OTRMessage_Init re-run below repopulates them against the fresh resources.
extern "C" char* _message_0xFFFC_nes;
extern "C" MessageTableEntry* sNesMessageEntryTablePtr;
extern "C" MessageTableEntry* sGerMessageEntryTablePtr;
extern "C" MessageTableEntry* sFraMessageEntryTablePtr;
extern "C" MessageTableEntry* sJpnMessageEntryTablePtr;
extern "C" MessageTableEntry* sStaffMessageEntryTablePtr;
extern "C" void OTRMessage_Init();

// Logging macros (same pattern as mm_anim_loader.c)
#define MMASSETS_LOG(fmt, ...) lusprintf(__FILE__, __LINE__, LUSLOG_LEVEL_INFO, fmt, ##__VA_ARGS__)
#define MMSFX_LOG(fmt, ...) lusprintf(__FILE__, __LINE__, LUSLOG_LEVEL_INFO, fmt, ##__VA_ARGS__)

// NOTE: WAV filesystem loading was removed. All MM audio comes from mm.o2r via ADPCM decoding.
// The decomp SampleBank_0 WAV files are NOT needed - mm.o2r contains the same samples in ADPCM format.

// Cache to keep mm.o2r resources alive (shared_ptr prevents destruction)
static std::unordered_map<std::string, std::shared_ptr<Ship::IResource>> sMmResourceCache;

// Static state - base MM archive
static bool sMmO2rDetected = false;
static bool sMmO2rLoaded = false;
static bool sInitialized = false;
static std::string sMmO2rPath;
static std::shared_ptr<Ship::Archive> sMmArchive; // Reference to mm.o2r archive for archive-specific loading

// Mod override archive (higher priority than mm.o2r)
static bool sModO2rDetected = false;
static bool sModO2rLoaded = false;
static std::string sModO2rPath;
static std::shared_ptr<Ship::Archive> sModArchive; // Reference to mod archive

// Mod archive names to search for (in priority order)
static const char* sModArchiveNames[] = {
    "mm-mod.o2r",      // Primary mod file
    "mm-custom.o2r",   // Alternative name
    "mm-override.o2r", // Alternative name
};
static const int sModArchiveCount = sizeof(sModArchiveNames) / sizeof(sModArchiveNames[0]);

// OoT asset archives (oot.o2r / oot-mq.o2r / soh.o2r) — secondary, loaded at LOWEST
// priority so MM/2ship win shared paths (no shadow crashes), while OoT-UNIQUE resources
// (Link equipment DLs, medallion/item icons) the NEI/pak_loader code loads by OTR
// path are still found. soh.o2r carries SoH's CUSTOM assets (per-dungeon key /
// key-ring DLs, object_nei_* meshes, custom icons) that do NOT exist in oot.o2r;
// mounting it makes those paths resolve both through the normal chain (unique paths)
// and through MmAssets_LoadFromOotArchive (which iterates this vector in order, so
// oot.o2r still wins any path shared with soh.o2r). Gracefully skipped when absent.
// Loaded inside LoadMmO2r so they share its single archive reorder + message-table
// refresh. Skijer's NEI (oot_asset_loader).
static std::vector<std::shared_ptr<Ship::Archive>> sOotArchives;
// soh.o2r is deliberately NOT mounted: SoH-EXPORTED resources served from it crashed 2ship's gfx
// interpreter (FILEPATH+PUSHCD texture refs → "Texture is null" + 0xC0000005 in gfx_push_current_dir,
// and libultraship is off-limits). Every SoH custom asset 2ship needs is copied under
// mm/assets/custom/ and packed by 2ship's OWN pipeline into 2ship.o2r, which renders fine — so the
// normal chain (and the direct loader's normal-chain fallback) serves ONLY the safe copies.
static const char* sOotArchiveNames[] = { "oot.o2r", "oot-mq.o2r" };
static const int sOotArchiveCount = sizeof(sOotArchiveNames) / sizeof(sOotArchiveNames[0]);

// appShortName is defined in OTRGlobals.h as const std::string

/**
 * Check if mm.o2r exists in any of the app directories
 * Uses the same search paths as oot.o2r
 */
static bool DetectMmO2r() {
    // Search for mm.o2r using the same method as oot.o2r
    std::string mmPath = Ship::Context::LocateFileAcrossAppDirs("mm.o2r", appShortName);
    if (!mmPath.empty() && std::filesystem::exists(mmPath)) {
        sMmO2rPath = mmPath;
        MMASSETS_LOG("[MM Assets] Found mm.o2r at: %s", mmPath.c_str());
        return true;
    }

    // Also check current working directory
    if (std::filesystem::exists("mm.o2r")) {
        sMmO2rPath = "mm.o2r";
        MMASSETS_LOG("[MM Assets] Found mm.o2r in current directory");
        return true;
    }

    // Check build output directories (for development)
    const char* buildPaths[] = {
        "x64/Debug/mm.o2r",
        "x64/Release/mm.o2r",
        "build/x64/mm.o2r",
        "../mm.o2r",
    };
    for (const char* path : buildPaths) {
        if (std::filesystem::exists(path)) {
            sMmO2rPath = path;
            MMASSETS_LOG("[MM Assets] Found mm.o2r at: %s", path);
            return true;
        }
    }

    MMASSETS_LOG("[MM Assets] mm.o2r NOT FOUND");
    return false;
}

/**
 * Check if a mod .o2r exists that can override mm.o2r assets
 * Searches for mm-mod.o2r, mm-custom.o2r, etc.
 */
static bool DetectModO2r() {
    for (int i = 0; i < sModArchiveCount; i++) {
        const char* modName = sModArchiveNames[i];

        // Search using standard path resolver
        std::string modPath = Ship::Context::LocateFileAcrossAppDirs(modName, appShortName);
        if (!modPath.empty() && std::filesystem::exists(modPath)) {
            sModO2rPath = modPath;
            MMASSETS_LOG("[MM Assets] Found mod override: %s", modPath.c_str());
            return true;
        }

        // Check current directory
        if (std::filesystem::exists(modName)) {
            sModO2rPath = modName;
            MMASSETS_LOG("[MM Assets] Found mod override in current directory: %s", modName);
            return true;
        }
    }

    return false;
}

/**
 * Load mod .o2r into the archive manager (before mm.o2r for priority)
 */
static bool LoadModO2r() {
    if (sModO2rLoaded || sModO2rPath.empty()) {
        return sModO2rLoaded;
    }

    if (!std::filesystem::exists(sModO2rPath)) {
        return false;
    }

    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (archiveManager) {
        auto archive = archiveManager->AddArchive(sModO2rPath);
        if (archive != nullptr) {
            sModArchive = archive;
            sModO2rLoaded = true;
            MMASSETS_LOG("[MM Assets] Loaded mod override archive: %s", sModO2rPath.c_str());
            return true;
        }
    }

    return false;
}

/**
 * Detect + add the OoT asset archives (oot.o2r, oot-mq.o2r) to the archive manager.
 * Searches the same dirs as mm.o2r plus the parent (../). The caller (LoadMmO2r)
 * reorders them to LOWEST priority alongside mm.o2r and triggers the message refresh.
 */
static void LoadOotO2rs() {
    if (!sOotArchives.empty()) {
        return;
    }
    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (!archiveManager) {
        return;
    }
    for (int i = 0; i < sOotArchiveCount; i++) {
        const char* name = sOotArchiveNames[i];
        std::string candidates[] = {
            Ship::Context::LocateFileAcrossAppDirs(name, appShortName),
            std::string(name),
            std::string("../") + name,
            std::string("x64/Debug/") + name,
            std::string("x64/Release/") + name,
            std::string("build/x64/") + name,
        };
        for (const std::string& path : candidates) {
            if (path.empty() || !std::filesystem::exists(path)) {
                continue;
            }
            auto archive = archiveManager->AddArchive(path);
            if (archive != nullptr) {
                sOotArchives.push_back(archive);
                MMASSETS_LOG("[OotAssets] Loaded %s at: %s", name, path.c_str());
            }
            break; // first existing candidate for this name
        }
    }
}

/**
 * Load mm.o2r into the archive manager
 * Same pattern as oot-mq.o2r loading in OTRGlobals::Initialize()
 */
static bool LoadMmO2r() {
    if (sMmO2rLoaded) {
        return true;
    }

    if (sMmO2rPath.empty() || !std::filesystem::exists(sMmO2rPath)) {
        MMASSETS_LOG("[MM Assets] Cannot load - path empty or file doesn't exist");
        return false;
    }

    // Add mm.o2r to the archive manager, then REORDER so it has LOWEST priority.
    // CRITICAL: mm.o2r contains resources with the SAME paths as oot.otr
    // (e.g., objects/object_okuta/gOctorokSkel) but with different data
    // (MM Octorok has 16 limbs, OOT has 38). Ship uses "last-added-wins" priority,
    // so without reordering, mm.o2r shadows OOT → assertion crash.
    //
    // By moving mm.o2r to the FRONT of the archive list (lowest priority):
    // - MM-unique paths (icon_item_static_yar, object_link_goron, etc.) are found
    //   → icon replacements (Deku replaces Skull) work
    // - Shared paths (objects/object_okuta) resolve to OOT version (higher priority)
    //   → no assertion crashes
    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (archiveManager) {
        auto archive = archiveManager->AddArchive(sMmO2rPath);
        if (archive != nullptr) {
            // Validate the embedded ROM CRC32 before letting mm.o2r participate in
            // resource resolution. We require MM 1.0 USA (NTSC). Older mm.o2r
            // archives that don't embed a version are accepted (false positives
            // would be worse than the missing check); Keiichi Alpha extractor
            // fingerprinting is deferred.
            if (archive->HasGameVersion()) {
                uint32_t mmVer = archive->GetGameVersion();
                if (mmVer != MM_NTSC_US_10) {
                    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Incompatible mm.o2r",
                                             "Your mm.o2r file is not compatible.\n"
                                             "Required: MM 1.0 USA (NTSC).\n\n"
                                             "Please re-extract using 2Ship2Harkinian (Keiichi Alfa 4.0.0+) "
                                             "with an MM 1.0 USA (NTSC) ROM.",
                                             nullptr);
                    MMASSETS_LOG("[MM Assets] Incompatible mm.o2r (got 0x%08X, required 0x%08X)", mmVer, MM_NTSC_US_10);
                    // Don't kill the whole app (was exit(1), which also skipped SDL/graphics
                    // teardown). Remove the incompatible archive so it can't shadow OOT
                    // resources and assertion-crash, then decline MM features and let the
                    // game boot normally with OOT only.
                    archiveManager->RemoveArchive(sMmO2rPath);
                    sMmO2rLoaded = false;
                    return false;
                }
            }
            sMmO2rLoaded = true;
            sMmArchive = archive;

            // Load the OoT asset archives now so they share the SAME single reorder +
            // message-table refresh below (avoids a second ResetVirtualFileSystem that
            // would invalidate the cached message c_str buffers). Skijer's NEI.
            LoadOotO2rs();

            // Reorder: move the OoT archives + mm.o2r to the FRONT (lowest priority);
            // the base 2ship.o2r stays after them (highest priority = base game wins
            // shared paths, while OoT-unique resources still resolve).
            auto currentArchives = archiveManager->GetArchives();
            if (currentArchives && currentArchives->size() > 1) {
                auto reordered = std::make_shared<std::vector<std::shared_ptr<Ship::Archive>>>();
                // OoT archives first (lowest priority of all)
                for (auto& oot : sOotArchives) {
                    reordered->push_back(oot);
                }
                // mm.o2r next (low priority)
                reordered->push_back(archive);
                // All other archives after (higher priority). Skip mm.o2r and the OoT
                // archives already placed.
                for (auto& existing : *currentArchives) {
                    if (existing == archive) {
                        continue;
                    }
                    bool isOot = false;
                    for (auto& oot : sOotArchives) {
                        if (existing == oot) {
                            isOot = true;
                            break;
                        }
                    }
                    if (!isOot) {
                        reordered->push_back(existing);
                    }
                }
                archiveManager->SetArchives(reordered);
                MMASSETS_LOG("[MM Assets] Loaded mm.o2r at lowest priority (pos 0 of %zu archives)", reordered->size());

                // SetArchives → ResetVirtualFileSystem unloads+reloads every archive,
                // invalidating std::string buffers behind every captured c_str()
                // (Font_LoadOrderedFont's _message_0xFFFC_nes, every MessageTableEntry.segment).
                // Refresh ONLY the message tables — wider unloads (UnloadResources("*"))
                // evict scene/collision data that's mid-load and crash WaterBox_GetSurfaceImpl
                // during Player_Init.
                auto resMgr = OTRGlobals::Instance->context->GetResourceManager();
                _message_0xFFFC_nes = nullptr;
                sNesMessageEntryTablePtr = nullptr;
                sGerMessageEntryTablePtr = nullptr;
                sFraMessageEntryTablePtr = nullptr;
                sJpnMessageEntryTablePtr = nullptr;
                sStaffMessageEntryTablePtr = nullptr;
                resMgr->UnloadResource("text/nes_message_data_static/nes_message_data_static");
                resMgr->UnloadResource("text/ger_message_data_static/ger_message_data_static");
                resMgr->UnloadResource("text/fra_message_data_static/fra_message_data_static");
                resMgr->UnloadResource("text/jpn_message_data_static/jpn_message_data_static");
                resMgr->UnloadResource("text/staff_message_data_static/staff_message_data_static");
                OTRMessage_Init();
                MMASSETS_LOG("[MM Assets] Refreshed message tables after archive reorder (0xFFFC=%p)",
                             (void*)_message_0xFFFC_nes);
            } else {
                MMASSETS_LOG("[MM Assets] Loaded mm.o2r (single archive, ptr=%p)", (void*)archive.get());
            }
            return true;
        } else {
            MMASSETS_LOG("[MM Assets] Failed to add mm.o2r as archive");
            return false;
        }
    }

    MMASSETS_LOG("[MM Assets] No archive manager available");
    return false;
}

// =============================================================================
// C API Implementation
// =============================================================================

extern "C" {

// True once an OoT asset archive (oot.o2r / oot-mq.o2r) is loaded. Backs
// OotAssets_Available() in oot_asset_loader.cpp. Skijer's NEI.
//
// 2026-08-07: this now runs the SAME adopt-handles recovery MmAssets_LoadFromOotArchive carries.
// oot.o2r can be mounted by TWO paths — LoadOotO2rs() here (feeds sOotArchives) or BenPort's
// OTRGlobals init (straight into the ArchiveManager, sOotArchives stays empty). When only the
// BenPort path ran, this returned 0 forever, and everything gated on OotAssets_Available() —
// the unified trade wheel's icons (TradeAdult_IconPath) and the OoT-mask wheel's
// (OotMask_IconPath) — resolved NULL and the two trade cells drew EMPTY, while the page-0 spell
// icons (plain FileExists, no Available gate) kept working. That split is exactly the reported
// "trade adult / trade child icons just don't show".
unsigned char MmAssets_OotArchivesLoaded(void) {
    if (sOotArchives.empty()) {
        try {
            auto rm = OTRGlobals::Instance->context->GetResourceManager();
            auto am = rm ? rm->GetArchiveManager() : nullptr;
            auto all = am ? am->GetArchives() : nullptr;
            if (all) {
                for (auto& ar : *all) {
                    if (!ar) {
                        continue;
                    }
                    const std::string& ap = ar->GetPath();
                    if (ap.find("oot.o2r") != std::string::npos || ap.find("oot-mq.o2r") != std::string::npos) {
                        sOotArchives.push_back(ar);
                    }
                }
            }
        } catch (...) {}
    }
    return sOotArchives.empty() ? 0 : 1;
}

void MmAssets_Init(void) {
    if (sInitialized) {
        return;
    }

    try {
        // Detect base MM archive
        sMmO2rDetected = DetectMmO2r();

        // Detect mod override archive
        sModO2rDetected = DetectModO2r();

        sInitialized = true;

        // Load base MM archive FIRST (lower priority)
        if (sMmO2rDetected) {
            LoadMmO2r();
        }

        // Load mod archive LAST (higher priority - overrides mm.o2r)
        // Ship's ResourceManager uses last-added-wins for duplicate resources
        if (sModO2rDetected) {
            LoadModO2r();
        }

        // Summary
        if (sModO2rLoaded) {
            MMASSETS_LOG("[MM Assets] Mod override active - %s overrides mm.o2r", sModO2rPath.c_str());
        }
    } catch (const std::exception& e) {
        MMASSETS_LOG("[MM Assets] Exception during init: %s", e.what());
        sInitialized = true;
        sMmO2rDetected = false;
        sMmO2rLoaded = false;
    } catch (...) {
        MMASSETS_LOG("[MM Assets] Unknown exception during init");
        sInitialized = true;
        sMmO2rDetected = false;
        sMmO2rLoaded = false;
    }
}

u8 MmAssets_IsAvailable(void) {
    if (!sInitialized) {
        MmAssets_Init();
    }
    return sMmO2rDetected ? 1 : 0;
}

u8 MmAssets_IsLoaded(void) {
    return sMmO2rLoaded ? 1 : 0;
}

u8 MmAssets_IsModLoaded(void) {
    return sModO2rLoaded ? 1 : 0;
}

const char* MmAssets_GetModPath(void) {
    return sModO2rPath.c_str();
}

const char* MmAssets_GetRequiredVersion(void) {
    return "2Ship2Harkinian Keiichi Alfa 4.0.0";
}

const char* MmAssets_GetPath(void) {
    return sMmO2rPath.c_str();
}

/**
 * Check if any user mod archive (not mm.o2r, not mm-mod.o2r) overrides a MM resource.
 * This allows .otr files in the mods/ folder to override mm.o2r assets.
 *
 * Priority order (highest first):
 *   1. User mods in mods/ folder (if they contain MM paths)
 *   2. mm-mod.o2r / mm-custom.o2r / mm-override.o2r
 *   3. mm.o2r (base MM archive)
 *
 * OOT mods don't interfere because OOT and MM use different path namespaces
 * (e.g., "textures/icon_item_static/..." vs "icon_item_static_yar/...").
 *
 * @param path Resource path (with or without __OTR__ prefix)
 * @return Archive containing the override, or nullptr if no mod override exists
 */
static std::shared_ptr<Ship::Archive> MmAssets_FindModOverride(const char* path) {
    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager)
        return nullptr;

    auto archiveManager = resourceManager->GetArchiveManager();
    if (!archiveManager)
        return nullptr;

    auto archives = archiveManager->GetArchives();
    if (!archives)
        return nullptr;

    // Strip __OTR__ prefix - archives index files without it
    std::string cleanPath = path;
    if (cleanPath.length() > 7 && cleanPath.substr(0, 7) == "__OTR__") {
        cleanPath = cleanPath.substr(7);
    }

    // Iterate in reverse (last-added archives have highest priority in Ship)
    for (auto it = archives->rbegin(); it != archives->rend(); ++it) {
        auto& archive = *it;

        // Skip mm.o2r - we want mods to override it
        if (archive == sMmArchive)
            continue;

        // Skip mm-mod.o2r if loaded (it's handled by the standard loading path)
        if (sModO2rLoaded && !sModO2rPath.empty() && archive->GetPath() == sModO2rPath)
            continue;

        if (archive->HasFile(cleanPath)) {
            MMASSETS_LOG("[MM Assets] Mod override found: %s in %s", path, archive->GetPath().c_str());
            return archive;
        }
    }

    return nullptr;
}

/**
 * Load a resource from mm.o2r, with support for mod overrides from the mods/ folder.
 * Path format follows 2Ship convention: "objects/object_link_goron/gLinkGoronSkel"
 *
 * Loading priority:
 *   1. User .otr in mods/ folder (if it contains this MM path)
 *   2. mm-mod.o2r (via standard archive priority)
 *   3. mm.o2r (base)
 *
 * @param path Resource path within mm.o2r
 * @return Pointer to loaded resource, or NULL if not found/not loaded
 */
void* MmAssets_LoadResource(const char* path) {
    if (!sMmO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Cannot load resource - mm.o2r not loaded");
        return nullptr;
    }
    if (path == nullptr) {
        return nullptr;
    }

    try {
        auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
        if (!resourceManager) {
            MMASSETS_LOG("[MM Assets] No resource manager");
            return nullptr;
        }

        // Use LoadResourceProcess (synchronous) instead of LoadResource — LoadResource
        // dispatches to mThreadPool and blocks on the future, which deadlocks on CPUs
        // with ≤4 logical cores where the pool has only 1 worker.
        auto modArchive = MmAssets_FindModOverride(path);
        if (modArchive) {
            Ship::ResourceIdentifier identifier(path, 0, modArchive);
            auto resource = resourceManager->LoadResourceProcess(identifier);
            if (resource) {
                void* ptr = resource->GetRawPointer();
                MMASSETS_LOG("[MM Assets] Loaded from mod: %s -> %p", path, ptr);
                return ptr;
            }
        }

        if (sMmArchive) {
            Ship::ResourceIdentifier identifier(path, 0, sMmArchive);
            auto resource = resourceManager->LoadResourceProcess(identifier);
            if (resource) {
                void* ptr = resource->GetRawPointer();
                MMASSETS_LOG("[MM Assets] Loaded from mm.o2r: %s -> %p", path, ptr);
                return ptr;
            }
        }

        MMASSETS_LOG("[MM Assets] Failed to load: %s", path);
    } catch (const std::exception& e) {
        MMASSETS_LOG("[MM Assets] Exception loading resource '%s': %s", path, e.what());
    } catch (...) { MMASSETS_LOG("[MM Assets] Unknown exception loading resource '%s'", path); }
    return nullptr;
}

/**
 * Load a resource from mm.o2r and get its size, with mod override support.
 * @param path Resource path
 * @param outSize Output: size in bytes
 * @return Pointer to loaded resource, or NULL if not found
 */
void* MmAssets_LoadResourceWithSize(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    if (!sMmO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Cannot load resource - mm.o2r not loaded");
        return nullptr;
    }
    if (path == nullptr) {
        return nullptr;
    }

    try {
        auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
        if (!resourceManager) {
            MMASSETS_LOG("[MM Assets] No resource manager");
            return nullptr;
        }

        // LoadResourceProcess (sync) — see MmAssets_LoadResource for deadlock rationale.
        if (sModArchive) {
            Ship::ResourceIdentifier modId(path, 0, sModArchive);
            auto resource = resourceManager->LoadResourceProcess(modId);
            if (resource) {
                void* ptr = resource->GetRawPointer();
                size_t size = resource->GetPointerSize();
                if (outSize)
                    *outSize = size;
                MMASSETS_LOG("[MM Assets] Loaded from mod with size: %s -> %p (%zu bytes)", path, ptr, size);
                return ptr;
            }
        }

        if (sMmArchive) {
            Ship::ResourceIdentifier identifier(path, 0, sMmArchive);
            auto resource = resourceManager->LoadResourceProcess(identifier);
            if (resource) {
                void* ptr = resource->GetRawPointer();
                size_t size = resource->GetPointerSize();
                if (outSize)
                    *outSize = size;
                MMASSETS_LOG("[MM Assets] Loaded from mm.o2r with size: %s -> %p (%zu bytes)", path, ptr, size);
                return ptr;
            }
        }

        MMASSETS_LOG("[MM Assets] Failed to load: %s", path);
    } catch (const std::exception& e) {
        MMASSETS_LOG("[MM Assets] Exception loading resource '%s': %s", path, e.what());
    } catch (...) { MMASSETS_LOG("[MM Assets] Unknown exception loading resource '%s'", path); }
    return nullptr;
}

/**
 * Load a resource SPECIFICALLY from mm.o2r archive, bypassing the resource cache.
 *
 * CRITICAL: The normal LoadResource() path hits the ResourceManager cache, which may
 * contain OOT versions of resources with the same path (e.g., "audio/fonts/Soundfont_0"
 * exists in both oot.o2r and mm.o2r). By using ResourceIdentifier with the mm.o2r
 * archive as Parent, we get a separate cache entry that loads from mm.o2r specifically.
 *
 * @param path Resource path (e.g., "audio/fonts/Soundfont_0")
 * @param outSize Output: size in bytes (optional, can be NULL)
 * @return Pointer to loaded resource data, or NULL if not found
 *
 * NOTE: [[maybe_unused]] — its only historical callers were the MM audio-injection
 * functions, now no-op stubs in 2ship (native MM audio). Retained as a general
 * cache-bypassing mm.o2r archive loader for any future asset path that must avoid
 * OOT/MM shared-path shadowing; kept per "don't touch archive-loading helpers".
 */
[[maybe_unused]] static void* MmAssets_LoadFromMmArchive(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    if (!sMmArchive || !path) {
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: archive=%p, path=%s", (void*)sMmArchive.get(),
                     path ? path : "NULL");
        return nullptr;
    }

    try {
        // Check our own cache first
        std::string pathStr(path);
        auto cacheIt = sMmResourceCache.find(pathStr);
        if (cacheIt != sMmResourceCache.end() && cacheIt->second) {
            void* ptr = cacheIt->second->GetRawPointer();
            size_t size = cacheIt->second->GetPointerSize();
            if (outSize)
                *outSize = size;
            return ptr;
        }

        auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
        if (!resourceManager) {
            MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: no resource manager");
            return nullptr;
        }

        // CRITICAL FIX: Load the File DIRECTLY from mm.o2r archive, then parse it.
        // ResourceManager::LoadResourceProcess has a bug where it calls
        // LoadFileProcess(identifier.Path) instead of LoadFileProcess(identifier),
        // which ignores the Parent archive and loads from oot.o2r instead.
        // Bypass: load File from archive ourselves, then use ResourceLoader to parse.
        auto file = sMmArchive->LoadFile(pathStr);
        if (!file) {
            MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: %s not found in mm.o2r", path);
            return nullptr;
        }

        auto resource = resourceManager->GetResourceLoader()->LoadResource(pathStr, file);
        if (resource) {
            void* ptr = resource->GetRawPointer();
            size_t size = resource->GetPointerSize();
            if (outSize)
                *outSize = size;
            // Keep resource alive in our cache
            sMmResourceCache[pathStr] = resource;
            MMASSETS_LOG("[MM Assets] LoadFromMmArchive OK: %s -> %p (%zu bytes)", path, ptr, size);
            return ptr;
        }

        MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: %s could not be parsed", path);
    } catch (const std::exception& e) {
        MMASSETS_LOG("[MM Assets] Exception in LoadFromMmArchive '%s': %s", path, e.what());
    } catch (...) { MMASSETS_LOG("[MM Assets] Unknown exception in LoadFromMmArchive '%s'", path); }
    return nullptr;
}

// Cache keeping oot.o2r-parsed resources alive (shared_ptr) AND remembering misses
// (nullptr entries), so a path that is absent from the OoT archives is not re-probed
// through Archive::LoadFile every frame by retrying draw code. Skijer's NEI.
static std::unordered_map<std::string, std::shared_ptr<Ship::IResource>> sOotResourceCache;

/**
 * Load a resource SPECIFICALLY from the OoT archives (oot.o2r / oot-mq.o2r), bypassing
 * the resource-manager priority chain AND its cache. Skijer's NEI.
 *
 * WHY (mirrors SoH's MmAssets_LoadFromMmArchive, transformation_masks): the archives
 * are mounted at the LOWEST priority, so any path that ALSO exists in 2ship's own
 * assets (e.g. objects/object_gi_hookshot/gGiHookshotDL, objects/object_gi_shield_3/
 * gGiMirrorShieldDL) always resolves to the MM version via ResourceMgr_*ByName —
 * the real OoT mesh is unreachable through the normal chain. And we cannot lean on
 * ResourceIdentifier{path, 0, archive} + LoadResourceProcess either:
 * ResourceManager::LoadResourceProcess calls LoadFileProcess(identifier.Path)
 * (NOT LoadFileProcess(identifier)), which drops the Parent archive and resolves by
 * priority again. Bypass: pull the File straight off the stored Ship::Archive handle
 * ourselves, then hand it to the ResourceLoader to parse, and keep the parsed
 * resource alive in our own cache (separate cache entry from any shadowing MM twin).
 *
 * @param path OTR path, with or without the "__OTR__" prefix
 * @param outSize Output: size in bytes (optional, can be NULL)
 * @return Pointer to loaded resource data (e.g. Gfx*), or NULL if not found
 */
// Resolve a CRC64 resource hash to its path string.
// oot.o2r display lists reference their children by HASH (G_VTX_OTR_HASH / G_DL_OTR_HASH /
// G_SETTIMG_OTR_HASH); the hash is derived from the PATH, so the deep-load patcher turns each child
// hash back into a path and loads it ARCHIVE-SCOPED from oot.o2r.
//
// CRITICAL: the global ArchiveManager hash index (HashToCString) does NOT contain oot.o2r's files.
// ArchiveManager::AddArchive REJECTS an archive whose game version is not in mValidGameVersions
// (oot.o2r is an OoT archive being mounted into an MM build), so its ListFiles() are never folded
// into mHashes. HashToCString therefore returns null for every OoT-unique child hash — which made
// the deep-patch bail out and fall back to MM's shadowing mesh. We instead resolve the hash from the
// oot.o2r archives' OWN file lists (Archive::ListFiles gives hash->filename), cached once. The global
// index is still consulted first so MM-shared hashes keep resolving.
extern "C" const char* MmAssets_HashToPath(unsigned long long hash) {
    try {
        auto rm = OTRGlobals::Instance->context->GetResourceManager();
        if (rm) {
            const char* p = rm->GetArchiveManager()->HashToCString(hash);
            if (p != nullptr) {
                return p;
            }
        }
        // Fall back to the OoT companion archives' own hash->path maps (kept alive in this static so
        // the returned c_str() stays valid for the process lifetime).
        static std::unordered_map<uint64_t, std::string> sOotHashToPath;
        static size_t sBuiltForArchiveCount = (size_t)-1;
        if (sBuiltForArchiveCount != sOotArchives.size()) {
            sOotHashToPath.clear();
            for (auto& archive : sOotArchives) {
                if (!archive) {
                    continue;
                }
                auto files = archive->ListFiles();
                if (files) {
                    for (auto& [h, name] : *files) {
                        sOotHashToPath.emplace(h, name);
                    }
                }
            }
            sBuiltForArchiveCount = sOotArchives.size();
        }
        auto it = sOotHashToPath.find((uint64_t)hash);
        return it != sOotHashToPath.end() ? it->second.c_str() : nullptr;
    } catch (...) { return nullptr; }
}

extern "C" void* MmAssets_LoadFromOotArchive(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    // sOotArchives is populated by mm_asset_loader's own LoadOotO2rs(). But oot.o2r is ALSO mounted
    // by a SEPARATE path (BenPort.cpp OTRGlobals init, "Skijer's NEI: mounted OoT companion"), which
    // adds it straight to the ArchiveManager WITHOUT feeding sOotArchives. When only that path ran,
    // sOotArchives is empty and every archive-scoped OoT load fails -> the deep-patch bails and the
    // draw falls back to MM's shadowing mesh. Recover here: if sOotArchives is empty but oot.o2r is
    // present in the ArchiveManager, adopt those handles so archive-scoped loads work regardless of
    // which mount path ran.
    if (sOotArchives.empty()) {
        try {
            auto rm = OTRGlobals::Instance->context->GetResourceManager();
            auto am = rm ? rm->GetArchiveManager() : nullptr;
            auto all = am ? am->GetArchives() : nullptr;
            if (all) {
                for (auto& ar : *all) {
                    if (!ar) {
                        continue;
                    }
                    const std::string& ap = ar->GetPath();
                    if (ap.find("oot.o2r") != std::string::npos || ap.find("oot-mq.o2r") != std::string::npos) {
                        sOotArchives.push_back(ar);
                    }
                }
            }
        } catch (...) {}
    }

    if (path == nullptr || sOotArchives.empty()) {
        // No archive yet (boot order) — do NOT negative-cache; caller retries later.
        return nullptr;
    }

    // Draw code passes gfx-style "__OTR__objects/..." paths; the archive stores plain paths.
    if (strncmp(path, "__OTR__", 7) == 0) {
        path += 7;
    }

    try {
        std::string pathStr(path);
        auto cacheIt = sOotResourceCache.find(pathStr);
        if (cacheIt != sOotResourceCache.end()) {
            if (!cacheIt->second) {
                return nullptr; // remembered miss
            }
            void* ptr = cacheIt->second->GetRawPointer();
            if (outSize)
                *outSize = cacheIt->second->GetPointerSize();
            return ptr;
        }

        auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
        if (!resourceManager) {
            return nullptr;
        }

        // oot.o2r first, then oot-mq.o2r (vector order == mount order).
        for (auto& archive : sOotArchives) {
            if (!archive) {
                continue;
            }
            auto file = archive->LoadFile(pathStr);
            if (!file) {
                continue;
            }
            auto resource = resourceManager->GetResourceLoader()->LoadResource(pathStr, file);
            if (resource) {
                void* ptr = resource->GetRawPointer();
                size_t size = resource->GetPointerSize();
                if (outSize)
                    *outSize = size;
                sOotResourceCache[pathStr] = resource; // keep alive
                MMASSETS_LOG("[OotAssets] LoadFromOotArchive OK: %s -> %p (%zu bytes)", path, ptr, size);
                return ptr;
            }
        }

        sOotResourceCache[pathStr] = nullptr; // archives mounted but path absent — remember the miss
        MMASSETS_LOG("[OotAssets] LoadFromOotArchive FAIL: %s not found in oot.o2r/oot-mq.o2r", path);
    } catch (const std::exception& e) {
        MMASSETS_LOG("[OotAssets] Exception in LoadFromOotArchive '%s': %s", path, e.what());
    } catch (...) { MMASSETS_LOG("[OotAssets] Unknown exception in LoadFromOotArchive '%s'", path); }
    return nullptr;
}

/**
 * Check if a specific resource exists in mm.o2r
 * Attempts to load the resource and checks if it succeeded
 */
u8 MmAssets_ResourceExists(const char* path) {
    if (!sMmO2rLoaded || path == nullptr) {
        return 0;
    }

    // Try to load and check if it succeeded
    void* resource = MmAssets_LoadResource(path);
    return (resource != nullptr) ? 1 : 0;
}

/**
 * List files matching a pattern from mm.o2r
 * Same as ResourceMgr_ListFiles in 2Ship (load.c lines 1254-1258)
 *
 * @param searchMask Pattern to match (e.g., "audio/fonts*")
 * @param resultSize Output: number of matching files
 * @return Array of file paths (caller must free), or NULL if none found
 */
char** MmAssets_ListFiles(const char* searchMask, int* resultSize) {
    if (!sMmO2rLoaded || searchMask == nullptr || resultSize == nullptr) {
        if (resultSize)
            *resultSize = 0;
        return nullptr;
    }

    try {
        auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
        if (!archiveManager) {
            *resultSize = 0;
            return nullptr;
        }

        // List files matching pattern from the archive
        // Same pattern as 2Ship's ResourceMgr_ListFiles (BenPort.cpp lines 315-332)
        auto fileList = archiveManager->ListFiles(searchMask);
        if (!fileList || fileList->size() == 0) {
            *resultSize = 0;
            MMASSETS_LOG("[MM Assets] No files match pattern: %s", searchMask);
            return nullptr;
        }

        // Convert to C-style array
        size_t count = fileList->size();
        char** result = (char**)malloc(count * sizeof(char*));
        if (!result) {
            *resultSize = 0;
            return nullptr;
        }

        for (size_t i = 0; i < count; i++) {
            const std::string& path = (*fileList)[i];
            result[i] = (char*)malloc(path.size() + 1);
            if (result[i]) {
                memcpy(result[i], path.c_str(), path.size());
                result[i][path.size()] = '\0';
            }
        }

        *resultSize = (int)count;
        MMASSETS_LOG("[MM Assets] Found %d files matching: %s", (int)count, searchMask);
        return result;
    } catch (const std::exception& e) {
        MMASSETS_LOG("[MM Assets] Exception in ListFiles '%s': %s", searchMask, e.what());
    } catch (...) { MMASSETS_LOG("[MM Assets] Unknown exception in ListFiles '%s'", searchMask); }
    *resultSize = 0;
    return nullptr;
}

/**
 * List files in mm.o2r ONLY (scoped to sMmArchive, ignoring all other mounted archives).
 * Same return convention as MmAssets_ListFiles: caller must free each entry + the array.
 */
char** MmAssets_ListMmArchiveFiles(const char* searchMask, int* resultSize) {
    if (resultSize)
        *resultSize = 0;
    if (!sMmO2rLoaded || !sMmArchive || searchMask == nullptr || resultSize == nullptr) {
        return nullptr;
    }

    try {
        auto fileMap = sMmArchive->ListFiles(searchMask);
        if (!fileMap || fileMap->empty()) {
            return nullptr;
        }

        size_t count = fileMap->size();
        char** result = (char**)malloc(count * sizeof(char*));
        if (!result) {
            return nullptr;
        }

        size_t i = 0;
        for (const auto& entry : *fileMap) {
            const std::string& path = entry.second;
            result[i] = (char*)malloc(path.size() + 1);
            if (result[i]) {
                memcpy(result[i], path.c_str(), path.size());
                result[i][path.size()] = '\0';
            }
            i++;
        }

        *resultSize = (int)count;
        return result;
    } catch (const std::exception& e) {
        MMASSETS_LOG("[MM Assets] Exception in ListMmArchiveFiles '%s': %s", searchMask, e.what());
    } catch (...) { MMASSETS_LOG("[MM Assets] Unknown exception in ListMmArchiveFiles '%s'", searchMask); }
    return nullptr;
}

// =============================================================================
// Asset Replacement System
// =============================================================================

// MM asset paths for replacements (from mm_sources/archives/)
// Icons (32x32 RGBA from icon_item_static_yar)
#define MM_DEKU_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconDekuMaskTex"
#define MM_STONE_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconStoneMaskTex"
#define MM_FIERCE_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconFierceDeityMaskTex"

// Name textures (from item_name_static)
#define MM_DEKU_MASK_NAME_PATH "__OTR__item_name_static/gItemNameDekuMaskENGTex"
#define MM_STONE_MASK_NAME_PATH "__OTR__item_name_static/gItemNameStoneMaskENGTex"
#define MM_FIERCE_MASK_NAME_PATH "__OTR__item_name_static/gItemNameFierceDeitysMaskENGTex"

// Get Item DLs (3D models from object_gi_*)
// Each mask has TWO DLs drawn with specific render modes (from 2Ship z_draw.c):
// - Deku: GetItem_DrawOpa0Xlu1 -> EmptyDL (Opa) + MaskDL (Xlu)
// - Stone: GetItem_DrawOpa0Xlu1 -> EmptyDL (Opa) + MaskDL (Xlu)
// - Fierce: GetItem_DrawOpa01 -> FaceDL (Opa) + HairDL (Opa)

// Deku Mask - object_gi_nutsmask
#define MM_DEKU_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_nutsmask/gGiDekuMaskEmptyDL"
#define MM_DEKU_MASK_DL_PATH "__OTR__objects/object_gi_nutsmask/gGiDekuMaskDL"

// Stone Mask - object_gi_stonemask
#define MM_STONE_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_stonemask/gGiStoneMaskEmptyDL"
#define MM_STONE_MASK_DL_PATH "__OTR__objects/object_gi_stonemask/gGiStoneMaskDL"

// Fierce Deity - object_gi_mask03 (NOT object_gi_mask18 which is Captain's Hat)
#define MM_FIERCE_MASK_FACE_DL_PATH "__OTR__objects/object_gi_mask03/gGiFierceDeityMaskFaceDL"
#define MM_FIERCE_MASK_HAIR_DL_PATH "__OTR__objects/object_gi_mask03/gGiFierceDeityMaskHairAndHatDL"

// Goron Mask - object_gi_golonmask
#define MM_GORON_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_golonmask/gGiGoronMaskEmptyDL"
#define MM_GORON_MASK_DL_PATH "__OTR__objects/object_gi_golonmask/gGiGoronMaskDL"

// Zora Mask - object_gi_zoramask
#define MM_ZORA_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_zoramask/gGiZoraMaskEmptyDL"
#define MM_ZORA_MASK_DL_PATH "__OTR__objects/object_gi_zoramask/gGiZoraMaskDL"

// =============================================================================
// Worn Mask DLs (when Link wears mask on face - DIFFERENT from Get Item DLs!)
// =============================================================================
// These are drawn on Link's face when equipping a mask.
// Transformation masks (Deku, Goron, Zora, Fierce) use gameplay_keep DLs.
// Stone Mask uses its own object file (object_mask_stone).
// From 2Ship z_player_lib.c lines 2918-2926:
//   object_mask_stone_DL_000820,    // PLAYER_MASK_STONE
//   gFierceDeityMaskDL,             // PLAYER_MASK_FIERCE_DEITY (gameplay_keep)
//   gDekuMaskDL,                    // PLAYER_MASK_DEKU (gameplay_keep)

#define MM_DEKU_MASK_WORN_DL_PATH "__OTR__objects/gameplay_keep/gDekuMaskDL"
#define MM_STONE_MASK_WORN_DL_PATH "__OTR__objects/object_mask_stone/object_mask_stone_DL_000820"
#define MM_FIERCE_MASK_WORN_DL_PATH "__OTR__objects/gameplay_keep/gFierceDeityMaskDL"

// Replacement table entry
typedef struct {
    const char* ootPath;  // OOT path (without __OTR__ prefix)
    const char* mmPath;   // MM path (with __OTR__ prefix)
    const char* cvarName; // CVar that controls this replacement
    MmReplaceType type;   // Asset type
} MmAssetReplacementEntry;

// Static replacement table - all transformation mask replacements
static MmAssetReplacementEntry sReplacementTable[] = {
    // =========================================================================
    // Skull Mask → Deku Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskSkullTex", MM_DEKU_MASK_ICON_PATH,
      "gMods.TransformMasks.DekuReplacesSkull", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskSkullNameTex", MM_DEKU_MASK_NAME_PATH, "gMods.TransformMasks.DekuReplacesSkull",
      MM_REPLACE_TEXT },
    // =========================================================================
    // Spooky Mask → Stone Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskSpookyTex", MM_STONE_MASK_ICON_PATH,
      "gMods.TransformMasks.StoneReplacesSpooky", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskSpookyNameTex", MM_STONE_MASK_NAME_PATH,
      "gMods.TransformMasks.StoneReplacesSpooky", MM_REPLACE_TEXT },
    // =========================================================================
    // Gerudo Mask → Fierce Deity Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskGerudoTex", MM_FIERCE_MASK_ICON_PATH,
      "gMods.TransformMasks.FierceReplacesGerudo", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskGerudoNameTex", MM_FIERCE_MASK_NAME_PATH,
      "gMods.TransformMasks.FierceReplacesGerudo", MM_REPLACE_TEXT },
};
static const int sReplacementTableSize = sizeof(sReplacementTable) / sizeof(sReplacementTable[0]);

u8 MmAssets_IsReplacementActive(const char* cvarName) {
    if (!MmAssets_IsAvailable()) {
        return 0;
    }
    if (cvarName == nullptr) {
        return 0;
    }
    // Check CVar value
    return CVarGetInteger(cvarName, 0) ? 1 : 0;
}

const char* MmAssets_GetReplacement(const char* ootPath) {
    if (ootPath == nullptr || !MmAssets_IsAvailable()) {
        return nullptr;
    }

    // Strip __OTR__ prefix if present for comparison
    const char* pathToMatch = ootPath;
    if (strncmp(ootPath, "__OTR__", 7) == 0) {
        pathToMatch = ootPath + 7;
    }

    // Search replacement table
    for (int i = 0; i < sReplacementTableSize; i++) {
        const MmAssetReplacementEntry* entry = &sReplacementTable[i];
        if (strcmp(pathToMatch, entry->ootPath) == 0) {
            // Check if this replacement is active
            if (MmAssets_IsReplacementActive(entry->cvarName)) {
                MMASSETS_LOG("[MM Assets] Replacing %s -> %s", ootPath, entry->mmPath);
                return entry->mmPath;
            }
        }
    }

    return nullptr; // No replacement
}

void* MmAssets_LoadDekuMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        MMASSETS_LOG("[MM Assets] LoadDekuMaskIcon: mm.o2r not available");
        return nullptr;
    }

    void* icon = MmAssets_LoadResource(MM_DEKU_MASK_ICON_PATH);
    if (icon != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Deku Mask icon from mm.o2r");
    } else {
        MMASSETS_LOG("[MM Assets] Failed to load Deku Mask icon");
    }
    return icon;
}

void* MmAssets_LoadDekuMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        MMASSETS_LOG("[MM Assets] LoadDekuMaskNameText: mm.o2r not available");
        return nullptr;
    }

    void* nameText = MmAssets_LoadResource(MM_DEKU_MASK_NAME_PATH);
    if (nameText != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Deku Mask name text from mm.o2r");
    } else {
        MMASSETS_LOG("[MM Assets] Failed to load Deku Mask name text");
    }
    return nameText;
}

// =============================================================================
// Stone Mask Loaders (replaces Spooky Mask)
// =============================================================================

void* MmAssets_LoadStoneMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    void* icon = MmAssets_LoadResource(MM_STONE_MASK_ICON_PATH);
    if (icon != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Stone Mask icon from mm.o2r");
    }
    return icon;
}

void* MmAssets_LoadStoneMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    void* nameText = MmAssets_LoadResource(MM_STONE_MASK_NAME_PATH);
    if (nameText != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Stone Mask name text from mm.o2r");
    }
    return nameText;
}

void* MmAssets_LoadStoneMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_STONE_MASK_DL_PATH;
}

// =============================================================================
// Fierce Deity Mask Loaders
// =============================================================================

void* MmAssets_LoadFierceMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return MmAssets_LoadResource(MM_FIERCE_MASK_ICON_PATH);
}

void* MmAssets_LoadFierceMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return MmAssets_LoadResource(MM_FIERCE_MASK_NAME_PATH);
}

void* MmAssets_LoadFierceMaskFaceDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_FIERCE_MASK_FACE_DL_PATH;
}

void* MmAssets_LoadFierceMaskHairDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_FIERCE_MASK_HAIR_DL_PATH;
}

// =============================================================================
// Deku Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadDekuMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_DEKU_MASK_EMPTY_DL_PATH;
}

void* MmAssets_LoadDekuMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_DEKU_MASK_DL_PATH;
}

// =============================================================================
// Stone Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadStoneMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_STONE_MASK_EMPTY_DL_PATH;
}

// =============================================================================
// Goron Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadGoronMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_GORON_MASK_EMPTY_DL_PATH;
}

void* MmAssets_LoadGoronMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_GORON_MASK_DL_PATH;
}

// =============================================================================
// Zora Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa01)
// =============================================================================

void* MmAssets_LoadZoraMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_ZORA_MASK_EMPTY_DL_PATH;
}

void* MmAssets_LoadZoraMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_ZORA_MASK_DL_PATH;
}

// =============================================================================
// Worn Mask DL Loaders (for Link wearing mask on face)
// =============================================================================
// These DLs are DIFFERENT from Get Item DLs!
// Get Item: object_gi_* files (spinning 3D model when receiving)
// Worn: gameplay_keep or object_mask_* (attached to Link's face)

void* MmAssets_LoadDekuMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Deku Mask WORN DL: %s", MM_DEKU_MASK_WORN_DL_PATH);
    return (void*)MM_DEKU_MASK_WORN_DL_PATH;
}

void* MmAssets_LoadStoneMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Stone Mask WORN DL: %s", MM_STONE_MASK_WORN_DL_PATH);
    return (void*)MM_STONE_MASK_WORN_DL_PATH;
}

void* MmAssets_LoadFierceMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Fierce Deity Mask WORN DL: %s", MM_FIERCE_MASK_WORN_DL_PATH);
    return (void*)MM_FIERCE_MASK_WORN_DL_PATH;
}

// =============================================================================
// MM Audio-Injection Subsystem — NO-OP STUBS
// =============================================================================
// Audio injection is redundant in 2ship (native MM audio) — no-op stub, mirrors
// mm_bgm_loader.cpp.
//
// The original SoH-style subsystem here decoded MM ADPCM samples, patched
// SoundFont sample pointers, and mixed MM SFX directly into the audio output.
// It depended on SoH audio-engine types/members that DO NOT exist in 2ship
// (SoundFontSample, SoundFontSound, Instrument.lowNotesSound/normalNotesSound/
// highNotesSound, Drum.sound, SoundEffect.sample, OTRAudio_LockMutex/UnlockMutex,
// etc.). In 2ship the game already IS Majora's Mask, so its sound effects play
// natively and this cross-game injection path is unnecessary.
//
// Every entry point below keeps its EXACT signature so all callers still link
// (the public MmSfx_*/MmDirectAudio_*/MmGakki_* API declared in mm_asset_loader.h,
// plus the MmSfxBridge_*/MmSfxDecode_Sample bridge entrypoints used by the
// mods/sound_translator engine). Each simply returns a benign value / does
// nothing. If native-bypass MM SFX injection is ever needed again, re-port the
// engine against 2ship's audio/lib types (audio/soundfont.h uses Sample /
// TunedSample instead of SoundFontSample / SoundFontSound).
//
// The archive / texture / skeleton / display-list asset loaders ABOVE and BELOW
// this block are the real reason this file exists and are fully retained.
// =============================================================================

// True when MM audio is available. Stubbed to 0 so callers take their native /
// vanilla audio path instead of the (removed) MM-injection path.
s32 MmSfx_IsAvailable(void) {
    return 0;
}

void MmSfx_Init(void) {
    // Audio injection is redundant in 2ship (native MM audio) — no-op stub, mirrors
    // mm_bgm_loader.cpp.
}

void MmSfx_Shutdown(void) {
    // Audio injection is redundant in 2ship (native MM audio) — no-op stub, mirrors
    // mm_bgm_loader.cpp.
}

// Returns the MM SoundFont for a given font/SFX id. Injection is redundant in
// 2ship — no-op stub, mirrors mm_bgm_loader.cpp.
SoundFont* MmSfx_LoadFont(s32 fontId) {
    (void)fontId;
    return nullptr;
}

SoundFont* MmSfx_GetFontForSfx(u16 sfxId) {
    (void)sfxId;
    return nullptr;
}

// Play an MM sound effect. Injection is redundant in 2ship (native MM audio) —
// no-op stub, mirrors mm_bgm_loader.cpp. Returns 0 so callers fall back to the
// engine's own (native) SFX path.
s32 MmSfx_PlayAtPos(u16 sfxId, Vec3f* pos) {
    (void)sfxId;
    (void)pos;
    return 0;
}

s32 MmSfx_PlayEx(u16 sfxId, Vec3f* pos, u8 token, f32* freqScale, f32* vol, s8* reverbAdd) {
    (void)sfxId;
    (void)pos;
    (void)token;
    (void)freqScale;
    (void)vol;
    (void)reverbAdd;
    return 0;
}

void MmSfx_Stop(u16 sfxId) {
    (void)sfxId;
}

void MmSfx_PlayGoronRoll(Vec3f* pos, f32 speed) {
    (void)pos;
    (void)speed;
}

void MmSfx_PlayGoronChgRoll(Vec3f* pos, f32 speed) {
    (void)pos;
    (void)speed;
}

void MmSfx_PlayGoronRollWithFloor(Vec3f* pos, f32 speed, u16 floorSfxOffset) {
    (void)pos;
    (void)speed;
    (void)floorSfxOffset;
}

void MmSfx_PlayGoronChgRollWithFloor(Vec3f* pos, f32 speed, u16 floorSfxOffset) {
    (void)pos;
    (void)speed;
    (void)floorSfxOffset;
}

void MmSfx_PlayGoronCharge(Vec3f* pos, f32 chargeLevel) {
    (void)pos;
    (void)chargeLevel;
}

void MmSfx_PlayTransformFlash(void) {
    // Audio injection is redundant in 2ship (native MM audio) — no-op stub, mirrors
    // mm_bgm_loader.cpp.
}

void MmSfx_GetCacheStats(s32* outLoadedFonts, s32* outTotalBytes) {
    if (outLoadedFonts) {
        *outLoadedFonts = 0;
    }
    if (outTotalBytes) {
        *outTotalBytes = 0;
    }
}

void MmSfx_FlushCache(void) {
    // Audio injection is redundant in 2ship (native MM audio) — no-op stub, mirrors
    // mm_bgm_loader.cpp.
}

// -----------------------------------------------------------------------------
// MM Direct Audio (ADPCM decode + mix) — no-op stubs.
// -----------------------------------------------------------------------------

// Mix MM direct audio into the output buffer. Injection is redundant in 2ship
// (native MM audio) — no-op stub, mirrors mm_bgm_loader.cpp. The output buffer
// is left untouched so only the native engine contributes audio.
void MmDirectAudio_MixInto(s16* outBuf, u32 numSamples) {
    (void)outBuf;
    (void)numSamples;
}

void MmDirectAudio_StopAll(void) {
    // Audio injection is redundant in 2ship (native MM audio) — no-op stub, mirrors
    // mm_bgm_loader.cpp.
}

// Play a per-form instrument note (gakki). Injection is redundant in 2ship
// (native MM audio) — no-op stub, mirrors mm_bgm_loader.cpp.
void MmGakki_PlayNote(s32 form, u8 buttonIndex, Vec3f* pos) {
    (void)form;
    (void)buttonIndex;
    (void)pos;
}

// -----------------------------------------------------------------------------
// MmSfxBridge_* / MmSfxDecode_Sample — bridge entrypoints consumed by the
// mods/sound_translator engine (mm_sfx_synth_loader.cpp, mm_sfx_synth_backend.cpp,
// mm_audio_sfx_dispatch.cpp). Kept as no-op stubs so those translation units keep
// linking. Injection is redundant in 2ship (native MM audio) — mirrors
// mm_bgm_loader.cpp.
// -----------------------------------------------------------------------------

extern "C" short* MmSfxDecode_Sample(void* sample, unsigned int* outLen) {
    (void)sample;
    if (outLen) {
        *outLen = 0;
    }
    return nullptr;
}

s32 MmSfxBridge_Play(u16 mmSfxId, f32 freqScale, Vec3f* pos) {
    (void)mmSfxId;
    (void)freqScale;
    (void)pos;
    return 0;
}

void MmSfxBridge_StopByMmSfxId(u16 mmSfxId) {
    (void)mmSfxId;
}

// `sf`/`path` are the 2ship SoundFont + o2r-relative path the SoH build would
// have re-patched. No-op in 2ship — mirrors mm_bgm_loader.cpp.
void MmSfxBridge_PatchFontSamples(SoundFont* sf, const char* path) {
    (void)sf;
    (void)path;
}

s32 MmSfxBridge_IsActive(u16 mmSfxId) {
    (void)mmSfxId;
    return 0;
}

void MmSfxBridge_RefreshProperties(u16 mmSfxId, Vec3f* pos, f32 freqScale) {
    (void)mmSfxId;
    (void)pos;
    (void)freqScale;
}

// =============================================================================
// MM Masks Inventory: Icon and Name Texture Loaders (24 masks)
// =============================================================================
// Paths verified from MM decomp: extracted/n64-us/assets/archives/icon_item_static/icon_item_static_yar.h
// and item_name_static/item_name_static.h

// Icon paths (32x32 RGBA textures from icon_item_static_yar)
static const char* sMmMaskIconPaths[24] = {
    "__OTR__icon_item_static_yar/gItemIconPostmansHatTex",      // 0: Postman's Hat
    "__OTR__icon_item_static_yar/gItemIconAllNightMaskTex",     // 1: All-Night Mask
    "__OTR__icon_item_static_yar/gItemIconBlastMaskTex",        // 2: Blast Mask
    "__OTR__icon_item_static_yar/gItemIconStoneMaskTex",        // 3: Stone Mask
    "__OTR__icon_item_static_yar/gItemIconGreatFairyMaskTex",   // 4: Great Fairy Mask
    "__OTR__icon_item_static_yar/gItemIconDekuMaskTex",         // 5: Deku Mask
    "__OTR__icon_item_static_yar/gItemIconKeatonMaskTex",       // 6: Keaton Mask
    "__OTR__icon_item_static_yar/gItemIconBremenMaskTex",       // 7: Bremen Mask
    "__OTR__icon_item_static_yar/gItemIconBunnyHoodTex",        // 8: Bunny Hood
    "__OTR__icon_item_static_yar/gItemIconDonGeroMaskTex",      // 9: Don Gero's Mask
    "__OTR__icon_item_static_yar/gItemIconMaskOfScentsTex",     // 10: Mask of Scents
    "__OTR__icon_item_static_yar/gItemIconGoronMaskTex",        // 11: Goron Mask
    "__OTR__icon_item_static_yar/gItemIconRomaniMaskTex",       // 12: Romani's Mask
    "__OTR__icon_item_static_yar/gItemIconCircusLeaderMaskTex", // 13: Circus Leader's Mask
    "__OTR__icon_item_static_yar/gItemIconKafeisMaskTex",       // 14: Kafei's Mask
    "__OTR__icon_item_static_yar/gItemIconCouplesMaskTex",      // 15: Couple's Mask
    "__OTR__icon_item_static_yar/gItemIconMaskOfTruthTex",      // 16: Mask of Truth
    "__OTR__icon_item_static_yar/gItemIconZoraMaskTex",         // 17: Zora Mask
    "__OTR__icon_item_static_yar/gItemIconKamaroMaskTex",       // 18: Kamaro's Mask
    "__OTR__icon_item_static_yar/gItemIconGibdoMaskTex",        // 19: Gibdo Mask
    "__OTR__icon_item_static_yar/gItemIconGaroMaskTex",         // 20: Garo Mask
    "__OTR__icon_item_static_yar/gItemIconCaptainsHatTex",      // 21: Captain's Hat
    "__OTR__icon_item_static_yar/gItemIconGiantsMaskTex",       // 22: Giant's Mask
    "__OTR__icon_item_static_yar/gItemIconFierceDeityMaskTex",  // 23: Fierce Deity Mask
};

// Name texture paths (from item_name_static)
static const char* sMmMaskNamePaths[24] = {
    "__OTR__item_name_static/gItemNamePostmansHatENGTex",
    "__OTR__item_name_static/gItemNameAllNightMaskENGTex",
    "__OTR__item_name_static/gItemNameBlastMaskENGTex",
    "__OTR__item_name_static/gItemNameStoneMaskENGTex",
    "__OTR__item_name_static/gItemNameGreatFairysMaskENGTex",
    "__OTR__item_name_static/gItemNameDekuMaskENGTex",
    "__OTR__item_name_static/gItemNameKeatonMaskENGTex",
    "__OTR__item_name_static/gItemNameBremenMaskENGTex",
    "__OTR__item_name_static/gItemNameBunnyHoodENGTex",
    "__OTR__item_name_static/gItemNameDonGerosMaskENGTex",
    "__OTR__item_name_static/gItemNameMaskOfScentsENGTex",
    "__OTR__item_name_static/gItemNameGoronMaskENGTex",
    "__OTR__item_name_static/gItemNameRomanisMaskENGTex",
    "__OTR__item_name_static/gItemNameCircusLeadersMaskENGTex",
    "__OTR__item_name_static/gItemNameKafeisMaskENGTex",
    "__OTR__item_name_static/gItemNameCouplesMaskENGTex",
    "__OTR__item_name_static/gItemNameMaskOfTruthENGTex",
    "__OTR__item_name_static/gItemNameZoraMaskENGTex",
    "__OTR__item_name_static/gItemNameKamarosMaskENGTex",
    "__OTR__item_name_static/gItemNameGibdoMaskENGTex",
    "__OTR__item_name_static/gItemNameGarosMaskENGTex",
    "__OTR__item_name_static/gItemNameCaptainsHatENGTex",
    "__OTR__item_name_static/gItemNameGiantsMaskENGTex",
    "__OTR__item_name_static/gItemNameFierceDeitysMaskENGTex",
};

// Cached icon pointers (NULL = not yet loaded)
static void* sCachedMaskIcons[24] = { 0 };
static bool sMaskIconLoaded[24] = { false };

// Cached name texture pointers
static void* sCachedMaskNames[24] = { 0 };
static bool sMaskNameLoaded[24] = { false };

// Index = itemId - ITEM_MM_MASK_POSTMAN
#define MM_MASK_ITEM_BASE ITEM_MM_MASK_POSTMAN

void* MmMasks_LoadIcon(uint16_t itemId) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (itemId < MM_MASK_ITEM_BASE || itemId >= MM_MASK_ITEM_BASE + 24)
        return nullptr;

    int idx = itemId - MM_MASK_ITEM_BASE;
    if (sMaskIconLoaded[idx])
        return sCachedMaskIcons[idx];

    sMaskIconLoaded[idx] = true;
    sCachedMaskIcons[idx] = MmAssets_LoadResource(sMmMaskIconPaths[idx]);
    if (sCachedMaskIcons[idx]) {
        MMASSETS_LOG("[MM Masks] Loaded icon %d: %s", idx, sMmMaskIconPaths[idx]);
    }
    return sCachedMaskIcons[idx];
}

void* MmMasks_LoadNameTex(uint16_t itemId) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (itemId < MM_MASK_ITEM_BASE || itemId >= MM_MASK_ITEM_BASE + 24)
        return nullptr;

    int idx = itemId - MM_MASK_ITEM_BASE;
    if (sMaskNameLoaded[idx])
        return sCachedMaskNames[idx];

    sMaskNameLoaded[idx] = true;
    sCachedMaskNames[idx] = MmAssets_LoadResource(sMmMaskNamePaths[idx]);
    if (sCachedMaskNames[idx]) {
        MMASSETS_LOG("[MM Masks] Loaded name %d: %s", idx, sMmMaskNamePaths[idx]);
    }
    return sCachedMaskNames[idx];
}

// Path getters: return __OTR__ path strings instead of raw data.
// When passed to gDPLoadTextureBlock, the RSP resolves actual texture dimensions
// from resource metadata, so HD mod textures render at their native resolution.
const char* MmMasks_GetIconPath(uint16_t itemId) {
    if (itemId < MM_MASK_ITEM_BASE || itemId >= MM_MASK_ITEM_BASE + 24)
        return nullptr;
    return sMmMaskIconPaths[itemId - MM_MASK_ITEM_BASE];
}

const char* MmMasks_GetNamePath(uint16_t itemId) {
    if (itemId < MM_MASK_ITEM_BASE || itemId >= MM_MASK_ITEM_BASE + 24)
        return nullptr;
    return sMmMaskNamePaths[itemId - MM_MASK_ITEM_BASE];
}

// =============================================================================
// FD Sword Icon (for B-button HUD override)
// =============================================================================

static void* sCachedFDSwordIcon = nullptr;
static bool sFDSwordIconLoaded = false;

void* MmAssets_LoadFDSwordIcon(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sFDSwordIconLoaded)
        return sCachedFDSwordIcon;

    sFDSwordIconLoaded = true;
    sCachedFDSwordIcon = MmAssets_LoadResource("__OTR__icon_item_static_yar/gItemIconFierceDeitySwordTex");
    if (sCachedFDSwordIcon) {
        MMASSETS_LOG("[MM Assets] Loaded FD sword icon");
    }
    return sCachedFDSwordIcon;
}

// =============================================================================
// MM Hookshot assets (icon + held body DL + chain DL + reticle DL + tip DL)
//
// Used by the Clawshot mode (Twilight Upgrade) to render Link wielding MM's
// hookshot 1:1 instead of the OOT graphics. The MM tip lives in object_lbfshot
// ("link_boy_fshot" — MM's hookshot tip object). Cached on first load; each
// loader returns NULL when mm.o2r isn't present and callers fall back to
// vanilla.
// =============================================================================

static void* sCachedMmHookshotIcon = nullptr;
static bool sMmHookshotIconLoaded = false;

void* MmAssets_LoadHookshotIcon(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sMmHookshotIconLoaded)
        return sCachedMmHookshotIcon;

    sMmHookshotIconLoaded = true;
    sCachedMmHookshotIcon = MmAssets_LoadResource("__OTR__icon_item_static_yar/gItemIconHookshotTex");
    if (sCachedMmHookshotIcon) {
        MMASSETS_LOG("[MM Assets] Loaded MM hookshot icon (Clawshot)");
    }
    return sCachedMmHookshotIcon;
}

static void* sCachedMmHookshotBodyDL = nullptr;
static bool sMmHookshotBodyDLLoaded = false;

void* MmAssets_LoadHookshotBodyDL(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sMmHookshotBodyDLLoaded)
        return sCachedMmHookshotBodyDL;

    sMmHookshotBodyDLLoaded = true;
    // gLinkHumanHookshotDL = hookshot body geometry only (no hand sub-DL,
    // unlike the "RightHandHolding" wrapper which prepends MM's closed-fist
    // hand and changes Link's visible hand style). z_player_lib.c builds a
    // compound DL that prepends OOT's hand DL before this one, so Link
    // keeps his OOT hand silhouette and only the hookshot model is MM.
    sCachedMmHookshotBodyDL = MmAssets_LoadResource("__OTR__objects/object_link_child/gLinkHumanHookshotDL");
    if (sCachedMmHookshotBodyDL) {
        MMASSETS_LOG("[MM Assets] Loaded MM hookshot body DL (no hand)");
    }
    return sCachedMmHookshotBodyDL;
}

static void* sCachedMmHookshotTipDL = nullptr;
static bool sMmHookshotTipDLLoaded = false;

void* MmAssets_LoadHookshotTipDL(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sMmHookshotTipDLLoaded)
        return sCachedMmHookshotTipDL;

    sMmHookshotTipDLLoaded = true;
    // MM's hookshot tip (the claw drawn at the END of the body) lives in
    // object_link_child at offset 0x1D960. Verified against MM decomp's
    // ArmsHook_Draw (src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c) which
    // calls `gSPDisplayList(POLY_OPA_DISP++, object_link_child_DL_01D960)`
    // every frame the hookshot actor exists and the player has RH_HOOKSHOT —
    // so this DL renders both when held (chain's tip-end aligns with the
    // body's nose) AND while flying (chain extended). The previous path
    // `object_lbfshot/object_lbfshot_DL_000228` was actually MM's wall
    // anchor/target geometry (the Bg_Lbfshot actor), not the held tip.
    sCachedMmHookshotTipDL = MmAssets_LoadResource("__OTR__objects/object_link_child/object_link_child_DL_01D960");
    if (sCachedMmHookshotTipDL) {
        MMASSETS_LOG("[MM Assets] Loaded MM hookshot tip DL");
    }
    return sCachedMmHookshotTipDL;
}

// MM-display-list-or-fallback selector (see mm_asset_loader.h). Behavior-equivalent
// to the inline `if (mm != NULL) dl = mm;` guard at each MM draw site.
Gfx* MmDL_Or(Gfx* vanillaDL, Gfx* mmDL) {
    return (mmDL != NULL) ? mmDL : vanillaDL;
}

static void* sCachedMmHookshotChainDL = nullptr;
static bool sMmHookshotChainDLLoaded = false;

void* MmAssets_LoadHookshotChainDL(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sMmHookshotChainDLLoaded)
        return sCachedMmHookshotChainDL;

    sMmHookshotChainDLLoaded = true;
    sCachedMmHookshotChainDL = MmAssets_LoadResource("__OTR__objects/gameplay_keep/gHookshotChainDL");
    if (sCachedMmHookshotChainDL) {
        MMASSETS_LOG("[MM Assets] Loaded MM hookshot chain DL");
    }
    return sCachedMmHookshotChainDL;
}

static void* sCachedMmHookshotReticleDL = nullptr;
static bool sMmHookshotReticleDLLoaded = false;

void* MmAssets_LoadHookshotReticleDL(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sMmHookshotReticleDLLoaded)
        return sCachedMmHookshotReticleDL;

    sMmHookshotReticleDLLoaded = true;
    sCachedMmHookshotReticleDL = MmAssets_LoadResource("__OTR__objects/gameplay_keep/gHookshotReticleDL");
    if (sCachedMmHookshotReticleDL) {
        MMASSETS_LOG("[MM Assets] Loaded MM hookshot reticle DL");
    }
    return sCachedMmHookshotReticleDL;
}

// =============================================================================
// Form B-Button Icon (per transformation form)
// =============================================================================

static const char* sFormBIconPaths[] = {
    "__OTR__icon_item_static_yar/gItemIconFierceDeitySwordTex", // MM_PLAYER_FORM_FIERCE_DEITY = 0
    "__OTR__icon_item_static_yar/gItemIconGoronMaskTex",        // MM_PLAYER_FORM_GORON = 1
    "__OTR__icon_item_static_yar/gItemIconZoraMaskTex",         // MM_PLAYER_FORM_ZORA = 2
    "__OTR__icon_item_static_yar/gItemIconDekuMaskTex",         // MM_PLAYER_FORM_DEKU = 3
};

static void* sCachedFormBIcons[4] = { nullptr, nullptr, nullptr, nullptr };
static bool sFormBIconLoaded[4] = { false, false, false, false };

void* MmAssets_LoadFormBIcon(u8 form) {
    if (!MmAssets_IsAvailable() || form > 3)
        return nullptr;
    if (sFormBIconLoaded[form])
        return sCachedFormBIcons[form];

    sFormBIconLoaded[form] = true;
    sCachedFormBIcons[form] = MmAssets_LoadResource(sFormBIconPaths[form]);
    if (sCachedFormBIcons[form]) {
        MMASSETS_LOG("[MM Assets] Loaded form %d B-button icon", form);
    }
    return sCachedFormBIcons[form];
}

// =============================================================================
// Chateau Romani Icon
// =============================================================================

const char* MmAssets_GetChateauIconPath(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    return "__OTR__icon_item_static_yar/gItemIconChateauRomaniTex";
}

} // extern "C"

// =============================================================================
// MM Asset Path Constants
// These are the paths used by 2Ship Keiichi Alfa 4.0.0
// =============================================================================

namespace MmAssetPaths {
// Goron Link assets
const char* GORON_SKELETON = "objects/object_link_goron/gLinkGoronSkel";
const char* GORON_HEAD_DL = "objects/object_link_goron/gLinkGoronHeadDL";
const char* GORON_CURLED_DL = "objects/object_link_goron/gLinkGoronCurledDL";
const char* GORON_SPIKES_DL = "objects/object_link_goron/gLinkGoronRollingSpikesAndEffectDL";

// Zora Link assets
const char* ZORA_SKELETON = "objects/object_link_zora/gLinkZoraSkel";
const char* ZORA_HEAD_DL = "objects/object_link_zora/gLinkZoraHeadDL";

// Deku Link assets
const char* DEKU_SKELETON = "objects/object_link_nuts/gLinkDekuSkel";
const char* DEKU_HEAD_DL = "objects/object_link_nuts/gLinkDekuHeadDL";

// Fierce Deity assets
const char* FIERCE_DEITY_SKELETON = "objects/object_link_boy/gLinkFierceDeitySkel";

// Audio
const char* TRANSFORM_SFX = "audio/sfx/NA_SE_SY_TRANSFORM_MASK_FLASH";
} // namespace MmAssetPaths
