message(STATUS "Copying otr files...")

if(NOT ONLY2SHIPOTR AND EXISTS ${SOURCE_DIR}/OTRExporter/mm.otr)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.otr ${SOURCE_DIR})
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.otr ${BINARY_DIR}/mm/)
    message(STATUS "Copied mm.otr")
endif()
if(EXISTS ${SOURCE_DIR}/OTRExporter/2ship.otr)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.otr ${SOURCE_DIR})
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.otr ${BINARY_DIR}/mm/)
    message(STATUS "Copied 2ship.otr")
endif()

# Additionally for Windows, copy the otrs to the target dir, side by side with 2ship.exe
if(SYSTEM_NAME MATCHES "Windows")
    if(NOT ONLY2SHIPOTR AND EXISTS ${SOURCE_DIR}/OTRExporter/mm.otr)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy mm.otr ${TARGET_DIR})
    endif()
    if(EXISTS ${SOURCE_DIR}/OTRExporter/2ship.otr)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy 2ship.otr ${TARGET_DIR})
    endif()
endif()

if(NOT ONLY2SHIPOTR AND (NOT EXISTS ${SOURCE_DIR}/mm.otr))
    message(FATAL_ERROR "Failed to copy. No OTR files found.")
endif()
if(NOT EXISTS ${SOURCE_DIR}/2ship.otr)
    message(FATAL_ERROR "Failed to copy. No 2ship OTR found.")
endif()
