from __future__ import annotations

from typing import NamedTuple
from enum import IntEnum
from BaseClasses import Item, ItemClassification as IC
from .Enums import Items


class MM2ShipItem(Item):
    game = "2 Ship 2 Harkinian (MM)"


class ItemType(IntEnum):
    none = 0
    song = 1
    magic = 2  # things that cost magic


class MM2ShipItemData(NamedTuple):
    # None means it's just here for the data, and won't be added to the datapackage
    item_id: int | None
    classification: IC = IC.progression
    quantity_in_item_pool: int = 0
    item_type: int = ItemType.none
    # MM: no child/adult split, fields kept for SoH-compat style
    child_only: bool = False
    adult_only: bool = False
    item_groups: list[str] = []  # for item_name_groups


item_data_table: dict[Items, MM2ShipItemData] = {
    Items.ABILITY_SWIM: MM2ShipItemData(2352, IC.progression, 1),
    Items.ARROW_FIRE: MM2ShipItemData(2353, IC.progression, 1),
    Items.ARROW_ICE: MM2ShipItemData(2354, IC.progression, 1),
    Items.ARROW_LIGHT: MM2ShipItemData(2355, IC.progression, 1),
    Items.ARROWS_10: MM2ShipItemData(2356, IC.filler, 1),
    Items.ARROWS_30: MM2ShipItemData(2357, IC.filler, 1),
    Items.ARROWS_50: MM2ShipItemData(2358, IC.filler, 1),
    Items.BLUE_POTION_REFILL: MM2ShipItemData(2359, IC.filler, 1),
    Items.BOMB_BAG_20: MM2ShipItemData(2360, IC.progression, 1),
    Items.BOMB_BAG_30: MM2ShipItemData(2361, IC.useful, 1),
    Items.BOMB_BAG_40: MM2ShipItemData(2362, IC.useful, 1),
    Items.BOMBCHU_10: MM2ShipItemData(2363, IC.filler, 1),
    Items.BOMBCHU_5: MM2ShipItemData(2364, IC.filler, 1),
    Items.BOMBCHU: MM2ShipItemData(2365, IC.filler, 1),
    Items.BOMBERS_NOTEBOOK: MM2ShipItemData(2366, IC.useful, 1),
    Items.BOMBS_10: MM2ShipItemData(2367, IC.filler, 1),
    Items.BOMBS_5: MM2ShipItemData(2368, IC.filler, 1),
    Items.BOTTLE_CHATEAU_ROMANI: MM2ShipItemData(2369, IC.progression, 1),
    Items.BOTTLE_EMPTY: MM2ShipItemData(2370, IC.progression, 1),
    Items.BOTTLE_GOLD_DUST: MM2ShipItemData(2371, IC.progression, 1),
    Items.BOTTLE_MILK: MM2ShipItemData(2372, IC.progression, 1),
    Items.BOTTLE_RED_POTION: MM2ShipItemData(2373, IC.progression, 1),
    Items.BOW: MM2ShipItemData(2374, IC.progression, 1),
    Items.CHATEAU_ROMANI_REFILL: MM2ShipItemData(2375, IC.filler, 1),
    Items.CLOCK_TOWN_STRAY_FAIRY: MM2ShipItemData(2376, IC.progression, 1),
    Items.DEED_LAND: MM2ShipItemData(2377, IC.progression, 1),
    Items.DEED_MOUNTAIN: MM2ShipItemData(2378, IC.progression, 1),
    Items.DEED_OCEAN: MM2ShipItemData(2379, IC.progression, 1),
    Items.DEED_SWAMP: MM2ShipItemData(2380, IC.progression, 1),
    Items.DEKU_NUT: MM2ShipItemData(2381, IC.filler, 1),
    Items.DEKU_NUTS_10: MM2ShipItemData(2382, IC.filler, 1),
    Items.DEKU_NUTS_5: MM2ShipItemData(2383, IC.filler, 1),
    Items.DEKU_STICK: MM2ShipItemData(2384, IC.filler, 1),
    Items.DEKU_STICKS_5: MM2ShipItemData(2385, IC.filler, 1),
    Items.DOUBLE_DEFENSE: MM2ShipItemData(2386, IC.useful, 1),
    Items.DOUBLE_MAGIC: MM2ShipItemData(2387, IC.useful, 1),
    Items.FAIRY_REFILL: MM2ShipItemData(2388, IC.filler, 1),
    Items.FROG_BLUE: MM2ShipItemData(2389, IC.progression, 1),
    Items.FROG_CYAN: MM2ShipItemData(2390, IC.progression, 1),
    Items.FROG_PINK: MM2ShipItemData(2391, IC.progression, 1),
    Items.FROG_WHITE: MM2ShipItemData(2392, IC.progression, 1),
    Items.GOLD_DUST_REFILL: MM2ShipItemData(2393, IC.useful, 1),
    Items.GREAT_BAY_BOSS_KEY: MM2ShipItemData(2394, IC.progression, 1),
    Items.GREAT_BAY_COMPASS: MM2ShipItemData(2395, IC.useful, 1),
    Items.GREAT_BAY_MAP: MM2ShipItemData(2396, IC.useful, 1),
    Items.GREAT_BAY_SMALL_KEY: MM2ShipItemData(2397, IC.progression, 1),
    Items.GREAT_BAY_STRAY_FAIRY: MM2ShipItemData(2398, IC.useful, 1),
    Items.GREAT_FAIRY_SWORD: MM2ShipItemData(2399, IC.useful, 1),
    Items.GREAT_SPIN_ATTACK: MM2ShipItemData(2400, IC.useful, 1),
    Items.GREEN_POTION_REFILL: MM2ShipItemData(2401, IC.filler, 1),
    Items.GS_TOKEN_OCEAN: MM2ShipItemData(2402, IC.useful, 1),
    Items.GS_TOKEN_SWAMP: MM2ShipItemData(2403, IC.useful, 1),
    Items.HEART_CONTAINER: MM2ShipItemData(2404, IC.useful, 1),
    Items.HEART_PIECE: MM2ShipItemData(2405, IC.useful, 1),
    Items.HOOKSHOT: MM2ShipItemData(2406, IC.progression, 1),
   # Items.JUNK: MM2ShipItemData(2407, IC.filler, 1),
    Items.LENS: MM2ShipItemData(2408, IC.progression, 1),
    Items.LETTER_TO_KAFEI: MM2ShipItemData(2409, IC.progression, 1),
    Items.LETTER_TO_MAMA: MM2ShipItemData(2410, IC.progression, 1),
    Items.MAGIC_BEAN: MM2ShipItemData(2411, IC.useful, 1),
    Items.MAGIC_JAR_BIG: MM2ShipItemData(2412, IC.filler, 1),
    Items.MAGIC_JAR_SMALL: MM2ShipItemData(2413, IC.filler, 1),
    Items.MASK_ALL_NIGHT: MM2ShipItemData(2414, IC.progression, 1),
    Items.MASK_BLAST: MM2ShipItemData(2415, IC.progression, 1),
    Items.MASK_BREMEN: MM2ShipItemData(2416, IC.progression, 1),
    Items.MASK_BUNNY: MM2ShipItemData(2417, IC.progression, 1),
    Items.MASK_CAPTAIN: MM2ShipItemData(2418, IC.progression, 1),
    Items.MASK_CIRCUS_LEADER: MM2ShipItemData(2419, IC.progression, 1),
    Items.MASK_COUPLE: MM2ShipItemData(2420, IC.progression, 1),
    Items.MASK_DEKU: MM2ShipItemData(2421, IC.progression, 1),
    Items.MASK_DON_GERO: MM2ShipItemData(2422, IC.progression, 1),
    Items.MASK_FIERCE_DEITY: MM2ShipItemData(2423, IC.progression, 1),
    Items.MASK_GARO: MM2ShipItemData(2424, IC.progression, 1),
    Items.MASK_GIANT: MM2ShipItemData(2425, IC.progression, 1),
    Items.MASK_GIBDO: MM2ShipItemData(2426, IC.progression, 1),
    Items.MASK_GORON: MM2ShipItemData(2427, IC.progression, 1),
    Items.MASK_GREAT_FAIRY: MM2ShipItemData(2428, IC.progression, 1),
    Items.MASK_KAFEIS_MASK: MM2ShipItemData(2429, IC.progression, 1),
    Items.MASK_KAMARO: MM2ShipItemData(2430, IC.progression, 1),
    Items.MASK_KEATON: MM2ShipItemData(2431, IC.progression, 1),
    Items.MASK_POSTMAN: MM2ShipItemData(2432, IC.progression, 1),
    Items.MASK_ROMANI: MM2ShipItemData(2433, IC.progression, 1),
    Items.MASK_SCENTS: MM2ShipItemData(2434, IC.progression, 1),
    Items.MASK_STONE: MM2ShipItemData(2435, IC.progression, 1),
    Items.MASK_TRUTH: MM2ShipItemData(2436, IC.progression, 1),
    Items.MASK_ZORA: MM2ShipItemData(2437, IC.progression, 1),
    Items.MILK_REFILL: MM2ShipItemData(2438, IC.filler, 1),
    Items.MOONS_TEAR: MM2ShipItemData(2439, IC.progression, 1),
    Items.MUSHROOM: MM2ShipItemData(2440, IC.progression, 1),
    Items.NONE: MM2ShipItemData(2441, IC.filler, 1),
    Items.OCARINA_BUTTON_A: MM2ShipItemData(2442, IC.progression, 1),
    Items.OCARINA_BUTTON_C_DOWN: MM2ShipItemData(2443, IC.progression, 1),
    Items.OCARINA_BUTTON_C_RIGHT: MM2ShipItemData(2444, IC.progression, 1),
    Items.OCARINA_BUTTON_C_LEFT: MM2ShipItemData(2445, IC.progression, 1),
    Items.OCARINA_BUTTON_C_UP: MM2ShipItemData(2446, IC.progression, 1),
    Items.OCARINA: MM2ShipItemData(2447, IC.progression, 1),
    Items.OWL_CLOCK_TOWN_SOUTH: MM2ShipItemData(2448, IC.useful, 1),
    Items.OWL_GREAT_BAY_COAST: MM2ShipItemData(2449, IC.useful, 1),
    Items.OWL_IKANA_CANYON: MM2ShipItemData(2450, IC.useful, 1),
    Items.OWL_MILK_ROAD: MM2ShipItemData(2451, IC.useful, 1),
    Items.OWL_MOUNTAIN_VILLAGE: MM2ShipItemData(2452, IC.useful, 1),
    Items.OWL_SNOWHEAD: MM2ShipItemData(2453, IC.useful, 1),
    Items.OWL_SOUTHERN_SWAMP: MM2ShipItemData(2454, IC.useful, 1),
    Items.OWL_STONE_TOWER: MM2ShipItemData(2455, IC.useful, 1),
    Items.OWL_WOODFALL: MM2ShipItemData(2456, IC.useful, 1),
    Items.OWL_ZORA_CAPE: MM2ShipItemData(2457, IC.useful, 1),
    Items.PENDANT_OF_MEMORIES: MM2ShipItemData(2458, IC.progression, 1),
    Items.PICTOGRAPH_BOX: MM2ShipItemData(2459, IC.progression, 1),
    Items.POWDER_KEG: MM2ShipItemData(2460, IC.progression, 1),
    Items.PROGRESSIVE_BOMB_BAG: MM2ShipItemData(2461, IC.progression, 1),
    Items.PROGRESSIVE_BOW: MM2ShipItemData(2462, IC.progression, 1),
    Items.PROGRESSIVE_LULLABY: MM2ShipItemData(2463, IC.progression, 1),
    Items.PROGRESSIVE_MAGIC: MM2ShipItemData(2464, IC.progression, 1),
    Items.PROGRESSIVE_SWORD: MM2ShipItemData(2465, IC.progression, 1),
    Items.PROGRESSIVE_WALLET: MM2ShipItemData(2466, IC.progression, 1),
    Items.QUIVER_40: MM2ShipItemData(2467, IC.useful, 1),
    Items.QUIVER_50: MM2ShipItemData(2468, IC.useful, 1),
    Items.RECOVERY_HEART: MM2ShipItemData(2469, IC.filler, 1),
    Items.RED_POTION_REFILL: MM2ShipItemData(2470, IC.filler, 1),
    Items.REMAINS_GOHT: MM2ShipItemData(2471, IC.progression, 1),
    Items.REMAINS_GYORG: MM2ShipItemData(2472, IC.progression, 1),
    Items.REMAINS_ODOLWA: MM2ShipItemData(2473, IC.progression, 1),
    Items.REMAINS_TWINMOLD: MM2ShipItemData(2474, IC.progression, 1),
    Items.ROOM_KEY: MM2ShipItemData(2475, IC.progression, 1),
    Items.RUPEE_BLUE: MM2ShipItemData(2476, IC.filler, 1),
    Items.RUPEE_GREEN: MM2ShipItemData(2477, IC.filler, 1),
    Items.RUPEE_HUGE: MM2ShipItemData(2478, IC.filler, 1),
    Items.RUPEE_PURPLE: MM2ShipItemData(2479, IC.filler, 1),
    Items.RUPEE_RED: MM2ShipItemData(2480, IC.filler, 1),
    Items.RUPEE_SILVER: MM2ShipItemData(2481, IC.filler, 1),
    Items.SHIELD_HERO: MM2ShipItemData(2482, IC.progression, 1),
    Items.SHIELD_MIRROR: MM2ShipItemData(2483, IC.progression, 1),
    Items.SINGLE_MAGIC: MM2ShipItemData(2484, IC.progression, 1),
    Items.SNOWHEAD_BOSS_KEY: MM2ShipItemData(2485, IC.progression, 1),
    Items.SNOWHEAD_COMPASS: MM2ShipItemData(2486, IC.useful, 1),
    Items.SNOWHEAD_MAP: MM2ShipItemData(2487, IC.useful, 1),
    Items.SNOWHEAD_SMALL_KEY: MM2ShipItemData(2488, IC.progression, 1),
    Items.SNOWHEAD_STRAY_FAIRY: MM2ShipItemData(2489, IC.useful, 1),
    Items.SONG_DOUBLE_TIME: MM2ShipItemData(2490, IC.progression, 1),
    Items.SONG_ELEGY: MM2ShipItemData(2491, IC.progression, 1),
    Items.SONG_EPONA: MM2ShipItemData(2492, IC.progression, 1),
    Items.SONG_HEALING: MM2ShipItemData(2493, IC.progression, 1),
    Items.SONG_INVERTED_TIME: MM2ShipItemData(2494, IC.progression, 1),
    Items.SONG_LULLABY_INTRO: MM2ShipItemData(2495, IC.progression, 1),
    Items.SONG_LULLABY: MM2ShipItemData(2496, IC.progression, 1),
    Items.SONG_NOVA: MM2ShipItemData(2497, IC.progression, 1),
    Items.SONG_OATH: MM2ShipItemData(2498, IC.progression, 1),
    Items.SONG_SARIA: MM2ShipItemData(2499, IC.progression, 1),
    Items.SONG_SOARING: MM2ShipItemData(2500, IC.progression, 1),
    Items.SONG_SONATA: MM2ShipItemData(2501, IC.progression, 1),
    Items.SONG_STORMS: MM2ShipItemData(2502, IC.progression, 1),
    Items.SONG_SUN: MM2ShipItemData(2503, IC.progression, 1),
    Items.SONG_TIME: MM2ShipItemData(2504, IC.progression, 1),
    Items.SOUL_BOSS_GOHT: MM2ShipItemData(2505, IC.progression, 1),
    Items.SOUL_BOSS_GYORG: MM2ShipItemData(2506, IC.progression, 1),
    Items.SOUL_BOSS_MAJORA: MM2ShipItemData(2507, IC.progression, 1),
    Items.SOUL_BOSS_ODOLWA: MM2ShipItemData(2508, IC.progression, 1),
    Items.SOUL_BOSS_TWINMOLD: MM2ShipItemData(2509, IC.progression, 1),
    Items.SOUL_ENEMY_ALIEN: MM2ShipItemData(2510, IC.progression, 1),
    Items.SOUL_ENEMY_ARMOS: MM2ShipItemData(2511, IC.progression, 1),
    Items.SOUL_ENEMY_BAD_BAT: MM2ShipItemData(2512, IC.progression, 1),
    Items.SOUL_ENEMY_BEAMOS: MM2ShipItemData(2513, IC.progression, 1),
    Items.SOUL_ENEMY_BOE: MM2ShipItemData(2514, IC.progression, 1),
    Items.SOUL_ENEMY_BUBBLE: MM2ShipItemData(2515, IC.progression, 1),
    Items.SOUL_ENEMY_CAPTAIN_KEETA: MM2ShipItemData(2516, IC.progression, 1),
    Items.SOUL_ENEMY_CHUCHU: MM2ShipItemData(2517, IC.progression, 1),
    Items.SOUL_ENEMY_DEATH_ARMOS: MM2ShipItemData(2518, IC.progression, 1),
    Items.SOUL_ENEMY_DEEP_PYTHON: MM2ShipItemData(2519, IC.progression, 1),
    Items.SOUL_ENEMY_DEKU_BABA: MM2ShipItemData(2520, IC.progression, 1),
    Items.SOUL_ENEMY_DEXIHAND: MM2ShipItemData(2521, IC.progression, 1),
    Items.SOUL_ENEMY_DINOLFOS: MM2ShipItemData(2522, IC.progression, 1),
    Items.SOUL_ENEMY_DODONGO: MM2ShipItemData(2523, IC.progression, 1),
    Items.SOUL_ENEMY_DRAGONFLY: MM2ShipItemData(2524, IC.progression, 1),
    Items.SOUL_ENEMY_EENO: MM2ShipItemData(2525, IC.progression, 1),
    Items.SOUL_ENEMY_EYEGORE: MM2ShipItemData(2526, IC.progression, 1),
    Items.SOUL_ENEMY_FREEZARD: MM2ShipItemData(2527, IC.progression, 1),
    Items.SOUL_ENEMY_GARO: MM2ShipItemData(2528, IC.progression, 1),
    Items.SOUL_ENEMY_GEKKO: MM2ShipItemData(2529, IC.progression, 1),
    Items.SOUL_ENEMY_GIANT_BEE: MM2ShipItemData(2530, IC.progression, 1),
    Items.SOUL_ENEMY_GOMESS: MM2ShipItemData(2531, IC.progression, 1),
    Items.SOUL_ENEMY_GUAY: MM2ShipItemData(2532, IC.progression, 1),
    Items.SOUL_ENEMY_HIPLOOP: MM2ShipItemData(2533, IC.progression, 1),
    Items.SOUL_ENEMY_IGOS_DU_IKANA: MM2ShipItemData(2534, IC.progression, 1),
    Items.SOUL_ENEMY_IRON_KNUCKLE: MM2ShipItemData(2535, IC.progression, 1),
    Items.SOUL_ENEMY_KEESE: MM2ShipItemData(2536, IC.progression, 1),
    Items.SOUL_ENEMY_LEEVER: MM2ShipItemData(2537, IC.progression, 1),
    Items.SOUL_ENEMY_LIKE_LIKE: MM2ShipItemData(2538, IC.progression, 1),
    Items.SOUL_ENEMY_MAD_SCRUB: MM2ShipItemData(2539, IC.progression, 1),
    Items.SOUL_ENEMY_NEJIRON: MM2ShipItemData(2540, IC.progression, 1),
    Items.SOUL_ENEMY_OCTOROK: MM2ShipItemData(2541, IC.progression, 1),
    Items.SOUL_ENEMY_PEAHAT: MM2ShipItemData(2542, IC.progression, 1),
    Items.SOUL_ENEMY_PIRATE: MM2ShipItemData(2543, IC.progression, 1),
    Items.SOUL_ENEMY_POE: MM2ShipItemData(2544, IC.progression, 1),
    Items.SOUL_ENEMY_REDEAD: MM2ShipItemData(2545, IC.progression, 1),
    Items.SOUL_ENEMY_SHELLBLADE: MM2ShipItemData(2546, IC.progression, 1),
    Items.SOUL_ENEMY_SKULLFISH: MM2ShipItemData(2547, IC.progression, 1),
    Items.SOUL_ENEMY_SKULLTULA: MM2ShipItemData(2548, IC.progression, 1),
    Items.SOUL_ENEMY_SNAPPER: MM2ShipItemData(2549, IC.progression, 1),
    Items.SOUL_ENEMY_STALCHILD: MM2ShipItemData(2550, IC.progression, 1),
    Items.SOUL_ENEMY_TAKKURI: MM2ShipItemData(2551, IC.progression, 1),
    Items.SOUL_ENEMY_TEKTITE: MM2ShipItemData(2552, IC.progression, 1),
    Items.SOUL_ENEMY_WALLMASTER: MM2ShipItemData(2553, IC.progression, 1),
    Items.SOUL_ENEMY_WART: MM2ShipItemData(2554, IC.progression, 1),
    Items.SOUL_ENEMY_WIZROBE: MM2ShipItemData(2555, IC.progression, 1),
    Items.SOUL_ENEMY_WOLFOS: MM2ShipItemData(2556, IC.progression, 1),
    Items.STONE_TOWER_BOSS_KEY: MM2ShipItemData(2557, IC.progression, 1),
    Items.STONE_TOWER_COMPASS: MM2ShipItemData(2558, IC.useful, 1),
    Items.STONE_TOWER_MAP: MM2ShipItemData(2559, IC.useful, 1),
    Items.STONE_TOWER_SMALL_KEY: MM2ShipItemData(2560, IC.progression, 1),
    Items.STONE_TOWER_STRAY_FAIRY: MM2ShipItemData(2561, IC.useful, 1),
    Items.SWORD_GILDED: MM2ShipItemData(2562, IC.progression, 1),
    Items.SWORD_KOKIRI: MM2ShipItemData(2563, IC.progression, 1),
    Items.SWORD_RAZOR: MM2ShipItemData(2564, IC.progression, 1),
    Items.TIME_DAY_1: MM2ShipItemData(2565, IC.progression, 1),
    Items.TIME_DAY_2: MM2ShipItemData(2566, IC.progression, 1),
    Items.TIME_DAY_3: MM2ShipItemData(2567, IC.progression, 1),
    Items.TIME_NIGHT_1: MM2ShipItemData(2568, IC.progression, 1),
    Items.TIME_NIGHT_2: MM2ShipItemData(2569, IC.progression, 1),
    Items.TIME_NIGHT_3: MM2ShipItemData(2570, IC.progression, 1),
    Items.TIME_PROGRESSIVE: MM2ShipItemData(2571, IC.progression, 1),
    Items.TINGLE_MAP_CLOCK_TOWN: MM2ShipItemData(2572, IC.useful, 1),
    Items.TINGLE_MAP_GREAT_BAY: MM2ShipItemData(2573, IC.useful, 1),
    Items.TINGLE_MAP_ROMANI_RANCH: MM2ShipItemData(2574, IC.useful, 1),
    Items.TINGLE_MAP_SNOWHEAD: MM2ShipItemData(2575, IC.useful, 1),
    Items.TINGLE_MAP_STONE_TOWER: MM2ShipItemData(2576, IC.useful, 1),
    Items.TINGLE_MAP_WOODFALL: MM2ShipItemData(2577, IC.useful, 1),
    Items.TRAP: MM2ShipItemData(2578, IC.trap, 1),
   # Items.TRIFORCE_PIECE_PREVIOUS: MM2ShipItemData(2579, IC.progression, 1),
    Items.TRIFORCE_PIECE: MM2ShipItemData(2580, IC.progression, 1),
    Items.WALLET_ADULT: MM2ShipItemData(2581, IC.progression, 1),
    Items.WALLET_GIANT: MM2ShipItemData(2582, IC.progression, 1),
    Items.WOODFALL_BOSS_KEY: MM2ShipItemData(2583, IC.progression, 1),
    Items.WOODFALL_COMPASS: MM2ShipItemData(2584, IC.useful, 1),
    Items.WOODFALL_MAP: MM2ShipItemData(2585, IC.useful, 1),
    Items.WOODFALL_SMALL_KEY: MM2ShipItemData(2586, IC.progression, 1),
    Items.WOODFALL_STRAY_FAIRY: MM2ShipItemData(2587, IC.useful, 1),
    # Event items (not sent over network)
    Items.VICTORY: MM2ShipItemData(None, IC.progression, 0),
}

item_table = {name.value: data.item_id for name, data in item_data_table.items() if data.item_id is not None}

# No-logic phase: leave these empty or derive them later when you build the pool/options.
filler_items: list[Items] = []
no_rules_bottles: list[Items] = []
filler_bottles: list[Items] = []
all_bottles: list[Items] = []
progressive_items: dict[Items, tuple[Items, ...]] = {}

item_name_groups: dict[str, set[str]] = {}
for item, data in item_data_table.items():
    for group in data.item_groups:
        item_name_groups.setdefault(group, set()).add(item.value)
