#ifndef GDAMPESHOVELDL_MESH_001_H
#define GDAMPESHOVELDL_MESH_001_H
extern u64 gDampeShovelDL_mesh_001_object_tk_009CC0_Tex_rgba16_png_001_rgba16[];
extern u64 gDampeShovelDL_mesh_001_object_tk_009D40_Tex_i4_png_001_i4[];
extern u64 gDampeShovelDL_mesh_001_object_tk_009C80_Tex_i8_png_001_i8[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_0[6];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_0[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_1[30];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_1[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_2[9];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_2[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_3[6];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_3[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_4[3];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_4[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_5[3];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_5[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_6[36];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_6[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_7[3];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_7[];
extern Vtx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_vtx_8[60];
extern Gfx gDampeShovelDL_mesh_001_gDampeShovelDL_mesh_001_mesh_layer_Opaque_tri_8[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_259_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_260_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_261_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_262_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_263_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_264_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_265_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_266_layerOpaque[];
extern Gfx mat_gDampeShovelDL_mesh_001_f3dlite_material_267_layerOpaque[];
extern Gfx gDampeShovelDL_mesh_001_opaque_dl[];

#endif
