// Local includes
#include "AchievementIntegration.h"
#include "Achievements.h"

// Standard library
#include <cstdarg>
#include <functional>
#include <map>
#include <vector>

extern "C" {
#include "functions.h"
#include "variables.h"
}

// 2s2h
#include "2s2h/GameInteractor/GameInteractor.h"
#include "2s2h/ShipInit.hpp"

namespace Achievements {

namespace Integration {

// ============================================================================
// Macro Helpers
// ============================================================================

#define ACH_VB(flag) GIVanillaBehavior::flag
#define ACH_AE(event) AchievementEvent::event
#define ACH_FT(type) FlagType::type

#define ACH_TRACK_FLAG(flagType, flag, event) \
    { { ACH_FT(flagType), flag }, ACH_AE(event) }

#define ACH_TRACK_SCENE_FLAG(sceneId, flagType, flag, event) \
    { { sceneId, ACH_FT(flagType), flag }, ACH_AE(event) }

#define ACH_TRACK_VB(event, ...)                                 \
    {                                                            \
        [](va_list args) -> bool { __VA_ARGS__; }, ACH_AE(event) \
    }

std::map<GIVanillaBehavior, std::vector<std::pair<std::function<bool(va_list)>, AchievementEvent>>> vanillaBehaviorMap;

namespace {
std::map<std::pair<FlagType, u32>, AchievementEvent> flagToEventMap;
std::map<std::tuple<s16, FlagType, u32>, AchievementEvent> sceneFlagToEventMap;
} // namespace

void Init() {
    // clang-format off
    flagToEventMap = {
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_LEARNED_SECRET_CODE, 
                   EVENT_LEARNED_SECRET_CODE),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BOMBERS_NOTEBOOK, 
                   EVENT_RECEIVED_BOMBERS_NOTEBOOK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ROOM_KEY, 
                   EVENT_RECEIVED_ROOM_KEY),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_PROMISED_MIDNIGHT_MEETING, 
                   EVENT_PROMISED_MIDNIGHT_MEETING),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_LETTER_TO_KAFEI,
                   EVENT_RECEIVED_LETTER_TO_KAFEI),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DEPOSITED_LETTER_TO_KAFEI,
                   EVENT_DEPOSITED_LETTER_TO_KAFEI),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DELIVERED_PENDANT_OF_MEMORIES,
                   EVENT_DELIVERED_PENDANT_OF_MEMORIES),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_COUPLES_MASK, 
                   EVENT_RECEIVED_COUPLES_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_PROMISED_TO_MEET_KAFEI, 
                   EVENT_PROMISED_TO_MEET_KAFEI),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_PENDANT_OF_MEMORIES, 
                   EVENT_RECEIVED_PENDANT_OF_MEMORIES),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_ESCAPED_SAKONS_HIDEOUT, 
                   EVENT_ESCAPED_SAKONS_HIDEOUT),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_KEATON_MASK, 
                   EVENT_RECEIVED_KEATON_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_PRIORITY_MAIL, 
                   EVENT_RECEIVED_PRIORITY_MAIL),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ALL_NIGHT_MASK, 
                   EVENT_RECEIVED_ALL_NIGHT_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BLAST_MASK, 
                   EVENT_RECEIVED_BLAST_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_PROMISED_TO_HELP_WITH_ALIENS, 
                   EVENT_PROMISED_TO_HELP_WITH_THEM),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DEFENDED_AGAINST_ALIENS, 
                   EVENT_DEFENDED_AGAINST_THEM),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ALIENS_BOTTLE, 
                   EVENT_RECEIVED_MILK_BOTTLE),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_ESCORTED_CREMIA, 
                   EVENT_ESCORTED_CREMIA),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ROMANIS_MASK, 
                   EVENT_RECEIVED_ROMANIS_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_MAYOR_HP, 
                   EVENT_RECEIVED_MAYOR_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_KAFEIS_MASK, 
                   EVENT_RECEIVED_KAFEIS_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_DELIVERED_PRIORITY_MAIL, 
                   EVENT_DELIVERED_PRIORITY_MAIL),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_CIRCUS_LEADERS_MASK, 
                   EVENT_RECEIVED_CIRCUS_LEADERS_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_MET_GORMAN, 
                   EVENT_MET_GORMAN),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_POSTMAN_HP, 
                   EVENT_RECEIVED_POSTMAN_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_POSTMANS_HAT, 
                   EVENT_RECEIVED_POSTMANS_HAT),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_ROSA_SISTERS_HP, 
                   EVENT_RECEIVED_ROSA_SISTERS_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_TOILET_HAND_HP, 
                   EVENT_RECEIVED_TOILET_HAND_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_GRANDMA_SHORT_STORY_HP, 
                   EVENT_RECEIVED_GRANDMA_SHORT_STORY_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_GRANDMA_LONG_STORY_HP, 
                   EVENT_RECEIVED_GRANDMA_LONG_STORY_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_KAMAROS_MASK, 
                   EVENT_RECEIVED_KAMAROS_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BUNNY_HOOD, 
                   EVENT_RECEIVED_BUNNY_HOOD),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_GAROS_MASK, 
                   EVENT_RECEIVED_GAROS_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_STONE_MASK, 
                   EVENT_RECEIVED_STONE_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_BOMBERS_NOTEBOOK_EVENT_RECEIVED_BREMEN_MASK, 
                   EVENT_RECEIVED_BREMEN_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_TINGLE_MAP_BOUGHT_CLOCK_TOWN,
                   EVENT_TINGLE_MAP_CLOCK_TOWN),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_TINGLE_MAP_BOUGHT_WOODFALL,
                   EVENT_TINGLE_MAP_WOODFALL),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_TINGLE_MAP_BOUGHT_SNOWHEAD,
                   EVENT_TINGLE_MAP_SNOWHEAD),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_TINGLE_MAP_BOUGHT_ROMANI_RANCH,
                   EVENT_TINGLE_MAP_ROMANI_RANCH),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_LAND_TITLE_DEED,
                   EVENT_RECEIVED_LAND_TITLE_DEED),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_60_01,
                   EVENT_BANK_REWARD_3),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_59_80,
                   EVENT_BANK_REWARD_2),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_BANK_WALLET_UPGRADE,
                   EVENT_BANK_REWARD_1),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_93_02,
                   EVENT_RECEIVED_MASK_OF_SCENTS),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_DOGGY_RACETRACK_HEART_PIECE,
                   EVENT_RECEIVED_DOGGY_RACETRACK_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_GREAT_SPIN_ATTACK,
                   EVENT_RECEIVED_GREAT_SPIN_ATTACK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_GORON_RACE_BOTTLE,
                   EVENT_GORON_RACE_REWARD),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_62_01,
                   EVENT_RECEIVED_BOMB_BAG_FROM_GORON_SCRUB),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_61_80,
                   EVENT_RECEIVED_MOUNTAIN_TITLE_DEED),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_HONEY_AND_DARLING_HEART_PIECE,
                   EVENT_HONEY_DARLING_REWARD_ALL_DAYS),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_22_10,
                   EVENT_HONEY_DARLING_REWARD_ANY_DAY),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_MARINE_RESEARCH_LAB_FISH_HEART_PIECE,
                   EVENT_RECEIVED_LAB_FISH_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_20_40,
                   EVENT_LEARNED_ZORA_SONG),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_61_01,
                   EVENT_RECEIVED_DON_GERO_MASK),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_74_40,
                   EVENT_RECEIVED_MOON_TEAR),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_SEAHORSE_HEART_PIECE,
                   EVENT_RECEIVED_PINNACLE_ROCK_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_TOWN_SHOOTING_GALLERY_QUIVER_UPGRADE,
                   EVENT_TOWN_ARCHERY_REWARD_1),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_SWAMP_SHOOTING_GALLERY_QUIVER_UPGRADE,
                   EVENT_SWAMP_ARCHERY_REWARD_1),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_SWAMP_SHOOTING_GALLERY_HEART_PIECE,
                   EVENT_SWAMP_ARCHERY_REWARD_2),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_61_10,
                   EVENT_RECEIVED_SWAMP_TITLE_DEED),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_SWORDSMANS_SCHOOL_HEART_PIECE,
                   EVENT_SWORDSMAN_SCHOOL_HP),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_26_40,
                   EVENT_BOAT_ARCHERY_HEART_PIECE),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_24_10,
                   EVENT_LEARNED_GORON_LULLABY_INTRO),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_BEAVER_BROS_HEART_PIECE,
                   EVENT_BEAVER_RACE_2),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_BEAVER_RACE_BOTTLE,
                   EVENT_BEAVER_RACE_1),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_84_10,
                   EVENT_RECEIVED_RED_POTION),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_62_04,
                   EVENT_RECEIVED_OCEAN_TITLE_DEED),
        ACH_TRACK_FLAG(FLAG_WEEK_EVENT_REG, WEEKEVENTREG_RECEIVED_EVAN_HEART_PIECE,
                   EVENT_ZORA_HALL_EVAN_HP),
    };
    // clang-format on

    // clang-format off
    sceneFlagToEventMap = {
        ACH_TRACK_SCENE_FLAG(SCENE_DEKU_KING, FLAG_CYCL_SCENE_SWITCH, 0x0B,
                        EVENT_LEARNED_SONATA_OF_AWAKENING),
        ACH_TRACK_SCENE_FLAG(SCENE_11GORONNOSATO, FLAG_CYCL_SCENE_COLLECTIBLE, 0x34,
                        EVENT_RECEIVED_POWDER_KEG),
        ACH_TRACK_SCENE_FLAG(SCENE_ALLEY, FLAG_CYCL_SCENE_COLLECTIBLE, 0x7F,
                        EVENT_CLOCK_TOWN_STRAY_FAIRY),
        ACH_TRACK_SCENE_FLAG(SCENE_MAP_SHOP, FLAG_PERM_SCENE_COLLECTIBLE, 0x43,
                        EVENT_RECEIVED_PICTOGRAPH_BOX),
        ACH_TRACK_SCENE_FLAG(SCENE_MAP_SHOP, FLAG_CYCL_SCENE_COLLECTIBLE, 0x0C,
                        EVENT_TINGLE_PICTURE_HEART_PIECE),
        ACH_TRACK_SCENE_FLAG(SCENE_20SICHITAI2, FLAG_CYCL_SCENE_SWITCH, 0x0B,
                        EVENT_LEARNED_SONG_OF_SOARING)
    };
    // clang-format on

    // clang-format off
    vanillaBehaviorMap = {
        { ACH_VB(VB_START_CUTSCENE), {
            ACH_TRACK_VB(EVENT_PLAYED_SONG_OF_DOUBLE_TIME, 
                     return gPlayState->msgCtx.ocarinaMode == OCARINA_MODE_APPLY_DOUBLE_SOT),
            ACH_TRACK_VB(EVENT_PLAYED_INVERTED_SONG_OF_TIME, 
                     u8 ocarinaMode = gPlayState->msgCtx.ocarinaMode;
                     return ocarinaMode == OCARINA_MODE_APPLY_INV_SOT_FAST || 
                            ocarinaMode == OCARINA_MODE_APPLY_INV_SOT_SLOW),
        }},
    };
    // clang-format on
}

void OnFlagSet(FlagType flagType, u32 flag) {
    const auto it = flagToEventMap.find({ flagType, flag });
    if (it != flagToEventMap.end()) {
        QUEUE_ACHIEVEMENT(it->second);
    }
}

void OnSceneFlagSet(s16 sceneId, FlagType flagType, u32 flag) {
    const auto it = sceneFlagToEventMap.find({ sceneId, flagType, flag });
    if (it != sceneFlagToEventMap.end()) {
        QUEUE_ACHIEVEMENT(it->second);
    }
}

void OnVanillaBehavior(GIVanillaBehavior flag, bool* /*should*/, va_list originalArgs) {
    const auto it = vanillaBehaviorMap.find(flag);
    if (it != vanillaBehaviorMap.end()) {
        for (const auto& condition : it->second) {
            if (condition.first(originalArgs)) {
                QUEUE_ACHIEVEMENT(condition.second);
            }
        }
    }
}

// ============================================================================
// Cleanup
// ============================================================================
#undef ACH_VB
#undef ACH_AE
#undef ACH_FT
#undef ACH_TRACK_FLAG
#undef ACH_TRACK_SCENE_FLAG
#undef ACH_TRACK_VB

} // namespace Integration

} // namespace Achievements