#ifndef SSBB_ACTION_DEFS_H
#define SSBB_ACTION_DEFS_H

#include "expansions/ssbb/ssbb_anim.h"
#include "expansions/ssbb/characters/pikachu_ssbb_all_anims.h"

// ── Action IDs ──────────────────────────────────────────────────────────────
// Each action maps to one or more SSBBAnim + metadata (loop, cancel, hitbox)

typedef enum {
    // ── Idle/Movement ──
    SSBB_ACT_WAIT1,
    SSBB_ACT_WAIT2,
    SSBB_ACT_WAIT3,
    SSBB_ACT_WALK_SLOW,
    SSBB_ACT_WALK_MIDDLE,
    SSBB_ACT_WALK_FAST,
    SSBB_ACT_WALK_BRAKE,
    SSBB_ACT_DASH,
    SSBB_ACT_RUN,
    SSBB_ACT_RUN_BRAKE,
    SSBB_ACT_TURN,
    SSBB_ACT_TURN_RUN,
    SSBB_ACT_TURN_RUN_BRAKE,
    SSBB_ACT_SQUAT,
    SSBB_ACT_SQUAT_WAIT,
    SSBB_ACT_SQUAT_F,
    SSBB_ACT_SQUAT_B,
    SSBB_ACT_SQUAT_RV,

    // ── Jump/Fall/Land (require Roc's Feather) ──
    SSBB_ACT_JUMP_SQUAT,
    SSBB_ACT_JUMP_F,
    SSBB_ACT_JUMP_B,
    SSBB_ACT_JUMP_AERIAL_F,
    SSBB_ACT_JUMP_AERIAL_B,
    SSBB_ACT_FALL,
    SSBB_ACT_FALL_F,
    SSBB_ACT_FALL_B,
    SSBB_ACT_FALL_AERIAL,
    SSBB_ACT_FALL_AERIAL_F,
    SSBB_ACT_FALL_AERIAL_B,
    SSBB_ACT_FALL_SPECIAL,
    SSBB_ACT_FALL_SPECIAL_F,
    SSBB_ACT_FALL_SPECIAL_B,
    SSBB_ACT_LANDING_LIGHT,
    SSBB_ACT_LANDING_HEAVY,
    SSBB_ACT_LANDING_AIR_N,
    SSBB_ACT_LANDING_AIR_F,
    SSBB_ACT_LANDING_AIR_B,
    SSBB_ACT_LANDING_AIR_HI,
    SSBB_ACT_LANDING_AIR_LW,
    SSBB_ACT_LANDING_FALL_SPECIAL,

    // ── Ground Attacks (A button) ──
    SSBB_ACT_ATTACK_JAB,          // Attack11 — A tap (1st in combo)
    SSBB_ACT_ATTACK_DASH,         // AttackDash — A while running
    SSBB_ACT_ATTACK_FTILT,        // AttackS3S — A + stick held forward
    SSBB_ACT_ATTACK_FTILT_HI,     // AttackS3Hi
    SSBB_ACT_ATTACK_FTILT_LW,     // AttackS3Lw
    SSBB_ACT_ATTACK_UTILT,        // AttackHi3 — 2nd A tap in combo
    SSBB_ACT_ATTACK_DTILT,        // AttackLw3 — A while crouching (L held)
    SSBB_ACT_ATTACK_FSMASH_START, // AttackS4Start — stick flick + A
    SSBB_ACT_ATTACK_FSMASH_HOLD,  // AttackS4Hold — holding A
    SSBB_ACT_ATTACK_FSMASH,       // AttackS4S — release
    SSBB_ACT_ATTACK_USMASH_START, // AttackHi4Start — 3rd A tap in combo
    SSBB_ACT_ATTACK_USMASH_HOLD,  // AttackHi4Hold
    SSBB_ACT_ATTACK_USMASH,       // AttackHi4
    SSBB_ACT_ATTACK_DSMASH_START, // AttackLw4Start — L + stick flick + A
    SSBB_ACT_ATTACK_DSMASH_HOLD,  // AttackLw4Hold
    SSBB_ACT_ATTACK_DSMASH,       // AttackLw4

    // ── Air Attacks (A in air) ──
    SSBB_ACT_ATTACK_NAIR, // AttackAirN — A neutral in air
    SSBB_ACT_ATTACK_FAIR, // AttackAirF — A + forward (facing dir)
    SSBB_ACT_ATTACK_BAIR, // AttackAirB — A + backward (stick opposite facing)
    SSBB_ACT_ATTACK_UAIR, // AttackAirHi — A + up in air
    SSBB_ACT_ATTACK_DAIR, // AttackAirLw — A + L in air

    // ── Specials (B button) ──
    SSBB_ACT_SPECIAL_N,       // SpecialN — B while still
    SSBB_ACT_SPECIAL_N_AIR,   // SpecialAirN
    SSBB_ACT_SPECIAL_S_START, // SpecialSStart — B + stick moving
    SSBB_ACT_SPECIAL_S_HOLD,  // SpecialSHold
    SSBB_ACT_SPECIAL_S_READY, // SpecialSReady
    SSBB_ACT_SPECIAL_S,       // SpecialS — Skull Bash dash
    SSBB_ACT_SPECIAL_S_END,   // SpecialSEnd
    SSBB_ACT_SPECIAL_S_AIR_START,
    SSBB_ACT_SPECIAL_S_AIR_HOLD,
    SSBB_ACT_SPECIAL_S_AIR_READY,
    SSBB_ACT_SPECIAL_S_AIR_END,
    SSBB_ACT_SPECIAL_HI_START, // SpecialHiStart — Boomerang/Beetle C-button
    SSBB_ACT_SPECIAL_HI_END,   // SpecialHiEnd
    SSBB_ACT_SPECIAL_HI_AIR_START,
    SSBB_ACT_SPECIAL_HI_AIR_END,
    SSBB_ACT_SPECIAL_LW, // SpecialLw — Din's Fire/Demise C-button
    SSBB_ACT_SPECIAL_LW_START,
    SSBB_ACT_SPECIAL_LW_LOOP,
    SSBB_ACT_SPECIAL_LW_HIT,
    SSBB_ACT_SPECIAL_LW_CHARGE_END,
    SSBB_ACT_SPECIAL_LW_DISCHARGE_END,
    SSBB_ACT_SPECIAL_LW_AIR,
    SSBB_ACT_SPECIAL_LW_AIR_START,
    SSBB_ACT_SPECIAL_LW_AIR_LOOP,
    SSBB_ACT_SPECIAL_LW_AIR_HIT,
    SSBB_ACT_SPECIAL_LW_AIR_CHARGE_END,
    SSBB_ACT_SPECIAL_LW_AIR_DISCHARGE_END,

    // ── Final Smash (hold B charge = Spin Attack) ──
    SSBB_ACT_FINAL,
    SSBB_ACT_FINAL2,
    SSBB_ACT_FINAL_AIR,
    SSBB_ACT_FINAL_AIR2,

    // ── Defense ──
    SSBB_ACT_GUARD_ON,
    SSBB_ACT_GUARD,
    SSBB_ACT_GUARD_OFF,
    SSBB_ACT_GUARD_DAMAGE,
    SSBB_ACT_ESCAPE_F,
    SSBB_ACT_ESCAPE_B,
    SSBB_ACT_ESCAPE_N,
    SSBB_ACT_ESCAPE_AIR,

    // ── Damage ──
    SSBB_ACT_DAMAGE_N1,
    SSBB_ACT_DAMAGE_N2,
    SSBB_ACT_DAMAGE_N3,
    SSBB_ACT_DAMAGE_HI1,
    SSBB_ACT_DAMAGE_HI2,
    SSBB_ACT_DAMAGE_HI3,
    SSBB_ACT_DAMAGE_LW1,
    SSBB_ACT_DAMAGE_LW2,
    SSBB_ACT_DAMAGE_LW3,
    SSBB_ACT_DAMAGE_AIR1,
    SSBB_ACT_DAMAGE_AIR2,
    SSBB_ACT_DAMAGE_AIR3,
    SSBB_ACT_DAMAGE_FLY_N,
    SSBB_ACT_DAMAGE_FLY_HI,
    SSBB_ACT_DAMAGE_FLY_LW,
    SSBB_ACT_DAMAGE_FLY_ROLL,
    SSBB_ACT_DAMAGE_FLY_TOP,
    SSBB_ACT_DAMAGE_ELEC,
    SSBB_ACT_DAMAGE_FALL,

    // ── Grab/Throw (Hookshot/Switch Hook/Whip) ──
    SSBB_ACT_CATCH,
    SSBB_ACT_CATCH_DASH,
    SSBB_ACT_CATCH_ATTACK,
    SSBB_ACT_CATCH_WAIT,
    SSBB_ACT_CATCH_CUT,
    SSBB_ACT_CATCH_TURN,
    SSBB_ACT_THROW_F,
    SSBB_ACT_THROW_B,
    SSBB_ACT_THROW_HI,
    SSBB_ACT_THROW_LW,

    // ── Being Grabbed/Thrown ──
    SSBB_ACT_THROWN_F,
    SSBB_ACT_THROWN_B,
    SSBB_ACT_THROWN_HI,
    SSBB_ACT_THROWN_LW,
    SSBB_ACT_THROWN_DX_F,
    SSBB_ACT_THROWN_DX_B,
    SSBB_ACT_THROWN_DX_HI,
    SSBB_ACT_THROWN_DX_LW,
    SSBB_ACT_CAPTURE_PULLED_HI,
    SSBB_ACT_CAPTURE_PULLED_LW,
    SSBB_ACT_CAPTURE_WAIT_HI,
    SSBB_ACT_CAPTURE_WAIT_LW,
    SSBB_ACT_CAPTURE_DAMAGE_HI,
    SSBB_ACT_CAPTURE_DAMAGE_LW,
    SSBB_ACT_CAPTURE_CUT,
    SSBB_ACT_CAPTURE_JUMP,
    SSBB_ACT_SWALLOWED,

    // ── Item Interactions ──
    SSBB_ACT_ITEM_HAMMER_WAIT,
    SSBB_ACT_ITEM_HAMMER_MOVE,
    SSBB_ACT_ITEM_HAMMER_AIR,
    SSBB_ACT_ITEM_SHOOT, // Elemental Rod auto-aim
    SSBB_ACT_ITEM_SHOOT_AIR,
    SSBB_ACT_ITEM_SMALL,
    SSBB_ACT_ITEM_BIG,
    SSBB_ACT_LIGHT_GET,
    SSBB_ACT_LIGHT_EAT,
    SSBB_ACT_HEAVY_GET,
    SSBB_ACT_HEAVY_WALK1, // Walk while carrying heavy item
    SSBB_ACT_HEAVY_WALK2,
    SSBB_ACT_HEAVY_THROW_F,  // Throw heavy item forward
    SSBB_ACT_HEAVY_THROW_B,  // Throw heavy item backward
    SSBB_ACT_HEAVY_THROW_HI, // Throw heavy item upward
    SSBB_ACT_HEAVY_THROW_LW, // Throw heavy item downward
    SSBB_ACT_LIGHT_THROW_F,
    SSBB_ACT_LIGHT_THROW_B,
    SSBB_ACT_LIGHT_THROW_HI,
    SSBB_ACT_LIGHT_THROW_LW,
    SSBB_ACT_LIGHT_THROW_DASH,
    SSBB_ACT_LIGHT_THROW_DROP,
    SSBB_ACT_LIGHT_THROW_AIR_F,
    SSBB_ACT_LIGHT_THROW_AIR_B,
    SSBB_ACT_LIGHT_THROW_AIR_HI,
    SSBB_ACT_LIGHT_THROW_AIR_LW,
    SSBB_ACT_LIGHT_WALK_GET,
    SSBB_ACT_LIGHT_WALK_EAT,
    SSBB_ACT_SMASH_THROW_F,
    SSBB_ACT_SMASH_THROW_B,
    SSBB_ACT_SMASH_THROW_HI,
    SSBB_ACT_SMASH_THROW_LW,
    SSBB_ACT_SMASH_THROW_DASH,
    SSBB_ACT_SMASH_THROW_AIR_F,
    SSBB_ACT_SMASH_THROW_AIR_B,
    SSBB_ACT_SMASH_THROW_AIR_HI,
    SSBB_ACT_SMASH_THROW_AIR_LW,
    SSBB_ACT_SWING1, // Melee item (Deku Stick etc)
    SSBB_ACT_SWING3,
    SSBB_ACT_SWING4,     // Charged melee
    SSBB_ACT_SWING4_BAT, // Deku Stick
    SSBB_ACT_SWING4_HOLD,
    SSBB_ACT_SWING4_START,
    SSBB_ACT_SWING_DASH,
    SSBB_ACT_WAIT_ITEM,

    // ── Cliff/Ledge (Brawl system) ──
    SSBB_ACT_CLIFF_CATCH,
    SSBB_ACT_CLIFF_WAIT,
    SSBB_ACT_CLIFF_CLIMB_QUICK,
    SSBB_ACT_CLIFF_CLIMB_SLOW,
    SSBB_ACT_CLIFF_ATTACK_QUICK,
    SSBB_ACT_CLIFF_ATTACK_SLOW,
    SSBB_ACT_CLIFF_ESCAPE_QUICK,
    SSBB_ACT_CLIFF_ESCAPE_SLOW,
    SSBB_ACT_CLIFF_JUMP_QUICK1,
    SSBB_ACT_CLIFF_JUMP_QUICK2,
    SSBB_ACT_CLIFF_JUMP_SLOW1,
    SSBB_ACT_CLIFF_JUMP_SLOW2,

    // ── Swimming (surface only) ──
    SSBB_ACT_SWIM,
    SSBB_ACT_SWIM_F,
    SSBB_ACT_SWIM_UP,
    SSBB_ACT_SWIM_TURN,
    SSBB_ACT_SWIM_END,
    SSBB_ACT_SWIM_RISE,
    SSBB_ACT_SWIM_DROWN,
    SSBB_ACT_SWIM_DROWN_OUT,
    SSBB_ACT_SWIM_UP_DAMAGE,

    // ── Ladder ──
    SSBB_ACT_LADDER_UP,
    SSBB_ACT_LADDER_DOWN,
    SSBB_ACT_LADDER_WAIT,
    SSBB_ACT_LADDER_CATCH_L,
    SSBB_ACT_LADDER_CATCH_R,
    SSBB_ACT_LADDER_CATCH_AIR_L,
    SSBB_ACT_LADDER_CATCH_AIR_R,
    SSBB_ACT_LADDER_CATCH_END_L,
    SSBB_ACT_LADDER_CATCH_END_R,

    // ── Creative Mappings ──
    SSBB_ACT_SLIP, // Ice surfaces
    SSBB_ACT_SLIP_WAIT,
    SSBB_ACT_SLIP_DASH,
    SSBB_ACT_SLIP_TURN,
    SSBB_ACT_SLIP_STAND,
    SSBB_ACT_SLIP_DOWN,
    SSBB_ACT_SLIP_ATTACK,
    SSBB_ACT_SLIP_ESCAPE_F,
    SSBB_ACT_SLIP_ESCAPE_B,
    SSBB_ACT_FURA_FURA, // Shield break / Deku Nut stun
    SSBB_ACT_FURA_FURA_END,
    SSBB_ACT_FURA_FURA_START_D,
    SSBB_ACT_FURA_FURA_START_U,
    SSBB_ACT_FURA_SLEEP_START, // Sleep status
    SSBB_ACT_FURA_SLEEP_LOOP,
    SSBB_ACT_FURA_SLEEP_END,
    SSBB_ACT_PASSIVE, // Wall tech
    SSBB_ACT_PASSIVE_STAND_F,
    SSBB_ACT_PASSIVE_STAND_B,
    SSBB_ACT_PASSIVE_WALL,
    SSBB_ACT_PASSIVE_WALL_JUMP,
    SSBB_ACT_PASSIVE_CEIL,
    SSBB_ACT_DOWN_WAIT_D,
    SSBB_ACT_DOWN_WAIT_U,
    SSBB_ACT_DOWN_STAND_D,
    SSBB_ACT_DOWN_STAND_U,
    SSBB_ACT_DOWN_ATTACK_D,
    SSBB_ACT_DOWN_ATTACK_U,
    SSBB_ACT_DOWN_BOUND_D,
    SSBB_ACT_DOWN_BOUND_U,
    SSBB_ACT_DOWN_DAMAGE_D,
    SSBB_ACT_DOWN_DAMAGE_U,
    SSBB_ACT_DOWN_DAMAGE_D3,
    SSBB_ACT_DOWN_DAMAGE_U3,
    SSBB_ACT_DOWN_BACK_D,
    SSBB_ACT_DOWN_BACK_U,
    SSBB_ACT_DOWN_FORWARD_D,
    SSBB_ACT_DOWN_FORWARD_U,
    SSBB_ACT_DOWN_EAT_D,
    SSBB_ACT_DOWN_EAT_U,
    SSBB_ACT_DOWN_SPOT_D,
    SSBB_ACT_OTTOTTO, // Edge teeter
    SSBB_ACT_OTTOTTO_WAIT,
    SSBB_ACT_STOP_WALL, // Wall bonk
    SSBB_ACT_STOP_CEIL,
    SSBB_ACT_MISS_FOOT, // Small ledge step-off
    SSBB_ACT_REBOUND,   // Attack rebound
    SSBB_ACT_WALL_DAMAGE,
    SSBB_ACT_GEKIKARA_WAIT, // Spicy idle

    // ── Win/Lose/Entry ──
    SSBB_ACT_WIN1,
    SSBB_ACT_WIN1_WAIT,
    SSBB_ACT_WIN2,
    SSBB_ACT_WIN2_WAIT,
    SSBB_ACT_WIN3,
    SSBB_ACT_WIN3_WAIT,
    SSBB_ACT_LOSE,
    SSBB_ACT_ENTRY_L,
    SSBB_ACT_ENTRY_R,

    // ── Taunts (auto-idle after 10s) ──
    SSBB_ACT_APPEAL_HI,
    SSBB_ACT_APPEAL_LW,
    SSBB_ACT_APPEAL_SL,
    SSBB_ACT_APPEAL_SR,

    SSBB_ACT_MAX
} SSBBActionId;

// ── Action Metadata ─────────────────────────────────────────────────────────

#define SSBB_ACT_FLAG_LOOP (1 << 0)     // Animation loops
#define SSBB_ACT_FLAG_ATTACK (1 << 1)   // Has hitbox
#define SSBB_ACT_FLAG_AIRBORNE (1 << 2) // Expects airborne state
#define SSBB_ACT_FLAG_GROUNDED (1 << 3) // Expects grounded state
#define SSBB_ACT_FLAG_MOVEMENT (1 << 4) // Can move during action
#define SSBB_ACT_FLAG_INVULN (1 << 5)   // Invulnerable during action (dodges)
#define SSBB_ACT_FLAG_LOCKED (1 << 6)   // Cannot be interrupted by movement selection (items, specials)

typedef struct {
    SSBBActionId id;
    PikachuAnimId animId; // Index into pikachu_ssbb_all_anims[]
    u8 flags;
    u8 hitboxStartFrame; // 0 = no hitbox
    u8 hitboxEndFrame;
    u8 cancelFrame; // Frame after which action can be interrupted (0 = end of anim)
} SSBBActionDef;

// Action table — maps SSBBActionId → SSBBAnim + metadata
// L = LOOP, A = ATTACK, G = GROUNDED, R = AIRBORNE, M = MOVEMENT, I = INVULN
#define L SSBB_ACT_FLAG_LOOP
#define A SSBB_ACT_FLAG_ATTACK
#define G SSBB_ACT_FLAG_GROUNDED
#define R SSBB_ACT_FLAG_AIRBORNE
#define M SSBB_ACT_FLAG_MOVEMENT
#define I SSBB_ACT_FLAG_INVULN
#define K SSBB_ACT_FLAG_LOCKED

static const SSBBActionDef sSSBBActionTable[SSBB_ACT_MAX] = {
    /* SSBB_ACT_WAIT1 */ { SSBB_ACT_WAIT1, PIKA_ANIM_WAIT1, L | G, 0, 0, 0 },
    /* SSBB_ACT_WAIT2 */ { SSBB_ACT_WAIT2, PIKA_ANIM_WAIT2, G, 0, 0, 0 },
    /* SSBB_ACT_WAIT3 */ { SSBB_ACT_WAIT3, PIKA_ANIM_WAIT3, G, 0, 0, 0 },
    /* SSBB_ACT_WALK_SLOW */ { SSBB_ACT_WALK_SLOW, PIKA_ANIM_WALKSLOW, L | G | M, 0, 0, 0 },
    /* SSBB_ACT_WALK_MIDDLE */ { SSBB_ACT_WALK_MIDDLE, PIKA_ANIM_WALKMIDDLE, L | G | M, 0, 0, 0 },
    /* SSBB_ACT_WALK_FAST */ { SSBB_ACT_WALK_FAST, PIKA_ANIM_WALKFAST, L | G | M, 0, 0, 0 },
    /* SSBB_ACT_WALK_BRAKE */ { SSBB_ACT_WALK_BRAKE, PIKA_ANIM_WALKBRAKE, G, 0, 0, 0 },
    /* SSBB_ACT_DASH */ { SSBB_ACT_DASH, PIKA_ANIM_DASH, G | M, 0, 0, 0 },
    /* SSBB_ACT_RUN */ { SSBB_ACT_RUN, PIKA_ANIM_RUN, L | G | M, 0, 0, 0 },
    /* SSBB_ACT_RUN_BRAKE */ { SSBB_ACT_RUN_BRAKE, PIKA_ANIM_RUNBRAKE, G, 0, 0, 0 },
    /* SSBB_ACT_TURN */ { SSBB_ACT_TURN, PIKA_ANIM_TURN, G, 0, 0, 0 },
    /* SSBB_ACT_TURN_RUN */ { SSBB_ACT_TURN_RUN, PIKA_ANIM_TURNRUN, G | M, 0, 0, 0 },
    /* SSBB_ACT_TURN_RUN_BRAKE */ { SSBB_ACT_TURN_RUN_BRAKE, PIKA_ANIM_TURNRUNBRAKE, G, 0, 0, 0 },
    /* SSBB_ACT_SQUAT */ { SSBB_ACT_SQUAT, PIKA_ANIM_SQUAT, G, 0, 0, 0 },
    /* SSBB_ACT_SQUAT_WAIT */ { SSBB_ACT_SQUAT_WAIT, PIKA_ANIM_SQUATWAIT, L | G, 0, 0, 0 },
    /* SSBB_ACT_SQUAT_F */ { SSBB_ACT_SQUAT_F, PIKA_ANIM_SQUATF, G | M, 0, 0, 0 },
    /* SSBB_ACT_SQUAT_B */ { SSBB_ACT_SQUAT_B, PIKA_ANIM_SQUATB, G | M, 0, 0, 0 },
    /* SSBB_ACT_SQUAT_RV */ { SSBB_ACT_SQUAT_RV, PIKA_ANIM_SQUATRV, G, 0, 0, 0 },
    /* SSBB_ACT_JUMP_SQUAT */ { SSBB_ACT_JUMP_SQUAT, PIKA_ANIM_JUMPSQUAT, G, 0, 0, 0 },
    /* SSBB_ACT_JUMP_F */ { SSBB_ACT_JUMP_F, PIKA_ANIM_JUMPF, R, 0, 0, 0 },
    /* SSBB_ACT_JUMP_B */ { SSBB_ACT_JUMP_B, PIKA_ANIM_JUMPB, R, 0, 0, 0 },
    /* SSBB_ACT_JUMP_AERIAL_F */ { SSBB_ACT_JUMP_AERIAL_F, PIKA_ANIM_JUMPAERIALF, R, 0, 0, 0 },
    /* SSBB_ACT_JUMP_AERIAL_B */ { SSBB_ACT_JUMP_AERIAL_B, PIKA_ANIM_JUMPAERIALB, R, 0, 0, 0 },
    /* SSBB_ACT_FALL */ { SSBB_ACT_FALL, PIKA_ANIM_FALL, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_F */ { SSBB_ACT_FALL_F, PIKA_ANIM_FALLF, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_B */ { SSBB_ACT_FALL_B, PIKA_ANIM_FALLB, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_AERIAL */ { SSBB_ACT_FALL_AERIAL, PIKA_ANIM_FALLAERIAL, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_AERIAL_F */ { SSBB_ACT_FALL_AERIAL_F, PIKA_ANIM_FALLAERIALF, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_AERIAL_B */ { SSBB_ACT_FALL_AERIAL_B, PIKA_ANIM_FALLAERIALB, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_SPECIAL */ { SSBB_ACT_FALL_SPECIAL, PIKA_ANIM_FALLSPECIAL, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_SPECIAL_F */ { SSBB_ACT_FALL_SPECIAL_F, PIKA_ANIM_FALLSPECIALF, L | R, 0, 0, 0 },
    /* SSBB_ACT_FALL_SPECIAL_B */ { SSBB_ACT_FALL_SPECIAL_B, PIKA_ANIM_FALLSPECIALB, L | R, 0, 0, 0 },
    /* SSBB_ACT_LANDING_LIGHT */ { SSBB_ACT_LANDING_LIGHT, PIKA_ANIM_LANDINGLIGHT, G, 0, 0, 4 },
    /* SSBB_ACT_LANDING_HEAVY */ { SSBB_ACT_LANDING_HEAVY, PIKA_ANIM_LANDINGHEAVY, G, 0, 0, 8 },
    /* SSBB_ACT_LANDING_AIR_N */ { SSBB_ACT_LANDING_AIR_N, PIKA_ANIM_LANDINGAIRN, G, 0, 0, 6 },
    /* SSBB_ACT_LANDING_AIR_F */ { SSBB_ACT_LANDING_AIR_F, PIKA_ANIM_LANDINGAIRF, G, 0, 0, 6 },
    /* SSBB_ACT_LANDING_AIR_B */ { SSBB_ACT_LANDING_AIR_B, PIKA_ANIM_LANDINGAIRB, G, 0, 0, 6 },
    /* SSBB_ACT_LANDING_AIR_HI */ { SSBB_ACT_LANDING_AIR_HI, PIKA_ANIM_LANDINGAIRHI, G, 0, 0, 6 },
    /* SSBB_ACT_LANDING_AIR_LW */ { SSBB_ACT_LANDING_AIR_LW, PIKA_ANIM_LANDINGAIRLW, G, 0, 0, 8 },
    /* SSBB_ACT_LANDING_FALL_SPECIAL */ { SSBB_ACT_LANDING_FALL_SPECIAL, PIKA_ANIM_LANDINGFALLSPECIAL, G, 0, 0, 15 },
    // ── Hitbox frames: extended from ATKD for better gameplay feel ──
    // Format: { id, anim, flags, hitStart, hitEnd, totalFrames }
    /* SSBB_ACT_ATTACK_JAB */ { SSBB_ACT_ATTACK_JAB, PIKA_ANIM_ATTACK11, A | G, 1, 8, 12 },
    /* SSBB_ACT_ATTACK_DASH */ { SSBB_ACT_ATTACK_DASH, PIKA_ANIM_ATTACKDASH, A | G | M, 2, 26, 28 },
    /* SSBB_ACT_ATTACK_FTILT */ { SSBB_ACT_ATTACK_FTILT, PIKA_ANIM_ATTACKS3S, A | G, 2, 14, 20 },
    /* SSBB_ACT_ATTACK_FTILT_HI */ { SSBB_ACT_ATTACK_FTILT_HI, PIKA_ANIM_ATTACKS3HI, A | G, 2, 14, 20 },
    /* SSBB_ACT_ATTACK_FTILT_LW */ { SSBB_ACT_ATTACK_FTILT_LW, PIKA_ANIM_ATTACKS3LW, A | G, 2, 14, 20 },
    /* SSBB_ACT_ATTACK_UTILT */ { SSBB_ACT_ATTACK_UTILT, PIKA_ANIM_ATTACKHI3, A | G, 4, 16, 18 },
    /* SSBB_ACT_ATTACK_DTILT */ { SSBB_ACT_ATTACK_DTILT, PIKA_ANIM_ATTACKLW3, A | G, 4, 12, 14 },
    /* SSBB_ACT_ATTACK_FSMASH_START */ { SSBB_ACT_ATTACK_FSMASH_START, PIKA_ANIM_ATTACKS4START, G, 0, 0, 0 },
    /* SSBB_ACT_ATTACK_FSMASH_HOLD */ { SSBB_ACT_ATTACK_FSMASH_HOLD, PIKA_ANIM_ATTACKS4HOLD, L | G, 0, 0, 0 },
    /* SSBB_ACT_ATTACK_FSMASH */ { SSBB_ACT_ATTACK_FSMASH, PIKA_ANIM_ATTACKS4S, A | G, 1, 18, 35 },
    /* SSBB_ACT_ATTACK_USMASH_START */ { SSBB_ACT_ATTACK_USMASH_START, PIKA_ANIM_ATTACKHI4START, G, 0, 0, 0 },
    /* SSBB_ACT_ATTACK_USMASH_HOLD */ { SSBB_ACT_ATTACK_USMASH_HOLD, PIKA_ANIM_ATTACKHI4HOLD, L | G, 0, 0, 0 },
    /* SSBB_ACT_ATTACK_USMASH */ { SSBB_ACT_ATTACK_USMASH, PIKA_ANIM_ATTACKHI4, A | G, 2, 18, 30 },
    /* SSBB_ACT_ATTACK_DSMASH_START */ { SSBB_ACT_ATTACK_DSMASH_START, PIKA_ANIM_ATTACKLW4START, G, 0, 0, 0 },
    /* SSBB_ACT_ATTACK_DSMASH_HOLD */ { SSBB_ACT_ATTACK_DSMASH_HOLD, PIKA_ANIM_ATTACKLW4HOLD, L | G, 0, 0, 0 },
    /* SSBB_ACT_ATTACK_DSMASH */ { SSBB_ACT_ATTACK_DSMASH, PIKA_ANIM_ATTACKLW4, A | G, 1, 25, 38 },
    /* SSBB_ACT_ATTACK_NAIR */ { SSBB_ACT_ATTACK_NAIR, PIKA_ANIM_ATTACKAIRN, A | R, 1, 28, 35 },
    /* SSBB_ACT_ATTACK_FAIR */ { SSBB_ACT_ATTACK_FAIR, PIKA_ANIM_ATTACKAIRF, A | R, 4, 28, 32 },
    /* SSBB_ACT_ATTACK_BAIR */ { SSBB_ACT_ATTACK_BAIR, PIKA_ANIM_ATTACKAIRB, A | R, 2, 25, 28 },
    /* SSBB_ACT_ATTACK_UAIR */ { SSBB_ACT_ATTACK_UAIR, PIKA_ANIM_ATTACKAIRHI, A | R, 1, 14, 20 },
    /* SSBB_ACT_ATTACK_DAIR */ { SSBB_ACT_ATTACK_DAIR, PIKA_ANIM_ATTACKAIRLW, A | R, 8, 28, 35 },
    /* SSBB_ACT_SPECIAL_N */ { SSBB_ACT_SPECIAL_N, PIKA_ANIM_SPECIALN, A | G | K, 18, 18, 40 },
    /* SSBB_ACT_SPECIAL_N_AIR */ { SSBB_ACT_SPECIAL_N_AIR, PIKA_ANIM_SPECIALAIRN, A | R | K, 18, 18, 40 },
    /* SSBB_ACT_SPECIAL_S_START */ { SSBB_ACT_SPECIAL_S_START, PIKA_ANIM_SPECIALSSTART, G | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S_HOLD */ { SSBB_ACT_SPECIAL_S_HOLD, PIKA_ANIM_SPECIALSHOLD, L | K | G, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S_READY */ { SSBB_ACT_SPECIAL_S_READY, PIKA_ANIM_SPECIALSREADY, G | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S */ { SSBB_ACT_SPECIAL_S, PIKA_ANIM_SPECIALS, A | G | M, 1, 30, 35 },
    /* SSBB_ACT_SPECIAL_S_END */ { SSBB_ACT_SPECIAL_S_END, PIKA_ANIM_SPECIALSEND, G | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S_AIR_START */ { SSBB_ACT_SPECIAL_S_AIR_START, PIKA_ANIM_SPECIALAIRSSTART, R | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S_AIR_HOLD */ { SSBB_ACT_SPECIAL_S_AIR_HOLD, PIKA_ANIM_SPECIALAIRSHOLD, L | K | R, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S_AIR_READY */ { SSBB_ACT_SPECIAL_S_AIR_READY, PIKA_ANIM_SPECIALAIRSREADY, R | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_S_AIR_END */ { SSBB_ACT_SPECIAL_S_AIR_END, PIKA_ANIM_SPECIALAIRSEND, R | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_HI_START */ { SSBB_ACT_SPECIAL_HI_START, PIKA_ANIM_SPECIALHISTART, M | K, 13, 18, 0 },
    /* SSBB_ACT_SPECIAL_HI_END */ { SSBB_ACT_SPECIAL_HI_END, PIKA_ANIM_SPECIALHIEND, K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_HI_AIR_START */
    { SSBB_ACT_SPECIAL_HI_AIR_START, PIKA_ANIM_SPECIALAIRHISTART, R | K | M, 13, 18, 0 },
    /* SSBB_ACT_SPECIAL_HI_AIR_END */ { SSBB_ACT_SPECIAL_HI_AIR_END, PIKA_ANIM_SPECIALAIRHIEND, R | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW */ { SSBB_ACT_SPECIAL_LW, PIKA_ANIM_SPECIALLW, A | G, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_START */ { SSBB_ACT_SPECIAL_LW_START, PIKA_ANIM_SPECIALLWSTART, G | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_LOOP */ { SSBB_ACT_SPECIAL_LW_LOOP, PIKA_ANIM_SPECIALLWLOOP, L | K | G, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_HIT */ { SSBB_ACT_SPECIAL_LW_HIT, PIKA_ANIM_SPECIALLWHIT, A | G, 1, 3, 0 },
    /* SSBB_ACT_SPECIAL_LW_CHARGE_END */
    { SSBB_ACT_SPECIAL_LW_CHARGE_END, PIKA_ANIM_SPECIALLWCHARGEEND, G | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_DISCHARGE_END */
    { SSBB_ACT_SPECIAL_LW_DISCHARGE_END, PIKA_ANIM_SPECIALLWDISCHARGEEND, G | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_AIR */ { SSBB_ACT_SPECIAL_LW_AIR, PIKA_ANIM_SPECIALAIRLW, A | R, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_AIR_START */ { SSBB_ACT_SPECIAL_LW_AIR_START, PIKA_ANIM_SPECIALAIRLWSTART, R | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_AIR_LOOP */ { SSBB_ACT_SPECIAL_LW_AIR_LOOP, PIKA_ANIM_SPECIALAIRLWLOOP, L | K | R, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_AIR_HIT */ { SSBB_ACT_SPECIAL_LW_AIR_HIT, PIKA_ANIM_SPECIALAIRLWHIT, A | R, 1, 3, 0 },
    /* SSBB_ACT_SPECIAL_LW_AIR_CHARGE_END */
    { SSBB_ACT_SPECIAL_LW_AIR_CHARGE_END, PIKA_ANIM_SPECIALAIRLWCHARGEEND, R | K, 0, 0, 0 },
    /* SSBB_ACT_SPECIAL_LW_AIR_DISCHARGE_END */
    { SSBB_ACT_SPECIAL_LW_AIR_DISCHARGE_END, PIKA_ANIM_SPECIALAIRLWDISCHARGEEND, R | K, 0, 0, 0 },
    /* SSBB_ACT_FINAL */ { SSBB_ACT_FINAL, PIKA_ANIM_FINAL, A | G, 1, 200, 0 },
    /* SSBB_ACT_FINAL2 */ { SSBB_ACT_FINAL2, PIKA_ANIM_FINAL2, A | G, 1, 200, 0 },
    /* SSBB_ACT_FINAL_AIR */ { SSBB_ACT_FINAL_AIR, PIKA_ANIM_FINALAIR, A | R, 1, 200, 0 },
    /* SSBB_ACT_FINAL_AIR2 */ { SSBB_ACT_FINAL_AIR2, PIKA_ANIM_FINALAIR2, A | R, 1, 200, 0 },
    /* SSBB_ACT_GUARD_ON */ { SSBB_ACT_GUARD_ON, PIKA_ANIM_GUARDON, G | K, 0, 0, 0 },
    /* SSBB_ACT_GUARD */ { SSBB_ACT_GUARD, PIKA_ANIM_GUARD, L | K | G, 0, 0, 0 },
    /* SSBB_ACT_GUARD_OFF */ { SSBB_ACT_GUARD_OFF, PIKA_ANIM_GUARDOFF, G | K, 0, 0, 0 },
    /* SSBB_ACT_GUARD_DAMAGE */ { SSBB_ACT_GUARD_DAMAGE, PIKA_ANIM_GUARDDAMAGE, G | K, 0, 0, 0 },
    /* SSBB_ACT_ESCAPE_F */ { SSBB_ACT_ESCAPE_F, PIKA_ANIM_ESCAPEF, G | K | M | I, 0, 0, 0 },
    /* SSBB_ACT_ESCAPE_B */ { SSBB_ACT_ESCAPE_B, PIKA_ANIM_ESCAPEB, G | K | M | I, 0, 0, 0 },
    /* SSBB_ACT_ESCAPE_N */ { SSBB_ACT_ESCAPE_N, PIKA_ANIM_ESCAPEN, G | K | I, 0, 0, 0 },
    /* SSBB_ACT_ESCAPE_AIR */ { SSBB_ACT_ESCAPE_AIR, PIKA_ANIM_ESCAPEAIR, R | K | I, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_N1 */ { SSBB_ACT_DAMAGE_N1, PIKA_ANIM_DAMAGEN1, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_N2 */ { SSBB_ACT_DAMAGE_N2, PIKA_ANIM_DAMAGEN2, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_N3 */ { SSBB_ACT_DAMAGE_N3, PIKA_ANIM_DAMAGEN3, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_HI1 */ { SSBB_ACT_DAMAGE_HI1, PIKA_ANIM_DAMAGEHI1, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_HI2 */ { SSBB_ACT_DAMAGE_HI2, PIKA_ANIM_DAMAGEHI2, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_HI3 */ { SSBB_ACT_DAMAGE_HI3, PIKA_ANIM_DAMAGEHI3, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_LW1 */ { SSBB_ACT_DAMAGE_LW1, PIKA_ANIM_DAMAGELW1, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_LW2 */ { SSBB_ACT_DAMAGE_LW2, PIKA_ANIM_DAMAGELW2, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_LW3 */ { SSBB_ACT_DAMAGE_LW3, PIKA_ANIM_DAMAGELW3, G, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_AIR1 */ { SSBB_ACT_DAMAGE_AIR1, PIKA_ANIM_DAMAGEAIR1, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_AIR2 */ { SSBB_ACT_DAMAGE_AIR2, PIKA_ANIM_DAMAGEAIR2, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_AIR3 */ { SSBB_ACT_DAMAGE_AIR3, PIKA_ANIM_DAMAGEAIR3, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_FLY_N */ { SSBB_ACT_DAMAGE_FLY_N, PIKA_ANIM_DAMAGEFLYN, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_FLY_HI */ { SSBB_ACT_DAMAGE_FLY_HI, PIKA_ANIM_DAMAGEFLYHI, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_FLY_LW */ { SSBB_ACT_DAMAGE_FLY_LW, PIKA_ANIM_DAMAGEFLYLW, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_FLY_ROLL */ { SSBB_ACT_DAMAGE_FLY_ROLL, PIKA_ANIM_DAMAGEFLYROLL, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_FLY_TOP */ { SSBB_ACT_DAMAGE_FLY_TOP, PIKA_ANIM_DAMAGEFLYTOP, R, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_ELEC */ { SSBB_ACT_DAMAGE_ELEC, PIKA_ANIM_DAMAGEELEC, 0, 0, 0, 0 },
    /* SSBB_ACT_DAMAGE_FALL */ { SSBB_ACT_DAMAGE_FALL, PIKA_ANIM_DAMAGEFALL, R, 0, 0, 0 },
    /* SSBB_ACT_CATCH */ { SSBB_ACT_CATCH, PIKA_ANIM_CATCH, K, 6, 7, 0 },
    /* SSBB_ACT_CATCH_DASH */ { SSBB_ACT_CATCH_DASH, PIKA_ANIM_CATCHDASH, K, 0, 0, 0 },
    /* SSBB_ACT_CATCH_ATTACK */ { SSBB_ACT_CATCH_ATTACK, PIKA_ANIM_CATCHATTACK, K, 0, 0, 0 },
    /* SSBB_ACT_CATCH_WAIT */ { SSBB_ACT_CATCH_WAIT, PIKA_ANIM_CATCHWAIT, K, 0, 0, 0 },
    /* SSBB_ACT_CATCH_CUT */ { SSBB_ACT_CATCH_CUT, PIKA_ANIM_CATCHCUT, K, 0, 0, 0 },
    /* SSBB_ACT_CATCH_TURN */ { SSBB_ACT_CATCH_TURN, PIKA_ANIM_CATCHTURN, K, 0, 0, 0 },
    /* SSBB_ACT_THROW_F */ { SSBB_ACT_THROW_F, PIKA_ANIM_THROWF, K, 0, 0, 0 },
    /* SSBB_ACT_THROW_B */ { SSBB_ACT_THROW_B, PIKA_ANIM_THROWB, K, 0, 0, 0 },
    /* SSBB_ACT_THROW_HI */ { SSBB_ACT_THROW_HI, PIKA_ANIM_THROWHI, K, 0, 0, 0 },
    /* SSBB_ACT_THROW_LW */ { SSBB_ACT_THROW_LW, PIKA_ANIM_THROWLW, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_F */ { SSBB_ACT_THROWN_F, PIKA_ANIM_THROWNF, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_B */ { SSBB_ACT_THROWN_B, PIKA_ANIM_THROWNB, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_HI */ { SSBB_ACT_THROWN_HI, PIKA_ANIM_THROWNHI, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_LW */ { SSBB_ACT_THROWN_LW, PIKA_ANIM_THROWNLW, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_DX_F */ { SSBB_ACT_THROWN_DX_F, PIKA_ANIM_THROWNDXF, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_DX_B */ { SSBB_ACT_THROWN_DX_B, PIKA_ANIM_THROWNDXB, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_DX_HI */ { SSBB_ACT_THROWN_DX_HI, PIKA_ANIM_THROWNDXHI, K, 0, 0, 0 },
    /* SSBB_ACT_THROWN_DX_LW */ { SSBB_ACT_THROWN_DX_LW, PIKA_ANIM_THROWNDXLW, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_PULLED_HI */ { SSBB_ACT_CAPTURE_PULLED_HI, PIKA_ANIM_CAPTUREPULLEDHI, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_PULLED_LW */ { SSBB_ACT_CAPTURE_PULLED_LW, PIKA_ANIM_CAPTUREPULLEDLW, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_WAIT_HI */ { SSBB_ACT_CAPTURE_WAIT_HI, PIKA_ANIM_CAPTUREWAITHI, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_WAIT_LW */ { SSBB_ACT_CAPTURE_WAIT_LW, PIKA_ANIM_CAPTUREWAITLW, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_DAMAGE_HI */ { SSBB_ACT_CAPTURE_DAMAGE_HI, PIKA_ANIM_CAPTUREDAMAGEHI, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_DAMAGE_LW */ { SSBB_ACT_CAPTURE_DAMAGE_LW, PIKA_ANIM_CAPTUREDAMAGELW, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_CUT */ { SSBB_ACT_CAPTURE_CUT, PIKA_ANIM_CAPTURECUT, K, 0, 0, 0 },
    /* SSBB_ACT_CAPTURE_JUMP */ { SSBB_ACT_CAPTURE_JUMP, PIKA_ANIM_CAPTUREJUMP, K, 0, 0, 0 },
    /* SSBB_ACT_SWALLOWED */ { SSBB_ACT_SWALLOWED, PIKA_ANIM_SWALLOWED, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_HAMMER_WAIT */ { SSBB_ACT_ITEM_HAMMER_WAIT, PIKA_ANIM_ITEMHAMMERWAIT, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_HAMMER_MOVE */ { SSBB_ACT_ITEM_HAMMER_MOVE, PIKA_ANIM_ITEMHAMMERMOVE, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_HAMMER_AIR */ { SSBB_ACT_ITEM_HAMMER_AIR, PIKA_ANIM_ITEMHAMMERAIR, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_SHOOT */ { SSBB_ACT_ITEM_SHOOT, PIKA_ANIM_ITEMSHOOT, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_SHOOT_AIR */ { SSBB_ACT_ITEM_SHOOT_AIR, PIKA_ANIM_ITEMSHOOTAIR, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_SMALL */ { SSBB_ACT_ITEM_SMALL, PIKA_ANIM_ITEMSMALL, K, 0, 0, 0 },
    /* SSBB_ACT_ITEM_BIG */ { SSBB_ACT_ITEM_BIG, PIKA_ANIM_ITEMBIG, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_GET */ { SSBB_ACT_LIGHT_GET, PIKA_ANIM_LIGHTGET, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_EAT */ { SSBB_ACT_LIGHT_EAT, PIKA_ANIM_LIGHTEAT, K, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_GET */ { SSBB_ACT_HEAVY_GET, PIKA_ANIM_HEAVYGET, K, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_WALK1 */ { SSBB_ACT_HEAVY_WALK1, PIKA_ANIM_HEAVYWALK1, 0, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_WALK2 */ { SSBB_ACT_HEAVY_WALK2, PIKA_ANIM_HEAVYWALK2, 0, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_THROW_F */ { SSBB_ACT_HEAVY_THROW_F, PIKA_ANIM_HEAVYTHROWF, K, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_THROW_B */ { SSBB_ACT_HEAVY_THROW_B, PIKA_ANIM_HEAVYTHROWB, K, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_THROW_HI */ { SSBB_ACT_HEAVY_THROW_HI, PIKA_ANIM_HEAVYTHROWHI, K, 0, 0, 0 },
    /* SSBB_ACT_HEAVY_THROW_LW */ { SSBB_ACT_HEAVY_THROW_LW, PIKA_ANIM_HEAVYTHROWLW, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_F */ { SSBB_ACT_LIGHT_THROW_F, PIKA_ANIM_LIGHTTHROWF, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_B */ { SSBB_ACT_LIGHT_THROW_B, PIKA_ANIM_LIGHTTHROWB, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_HI */ { SSBB_ACT_LIGHT_THROW_HI, PIKA_ANIM_LIGHTTHROWHI, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_LW */ { SSBB_ACT_LIGHT_THROW_LW, PIKA_ANIM_LIGHTTHROWLW, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_DASH */ { SSBB_ACT_LIGHT_THROW_DASH, PIKA_ANIM_LIGHTTHROWDASH, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_DROP */ { SSBB_ACT_LIGHT_THROW_DROP, PIKA_ANIM_LIGHTTHROWDROP, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_AIR_F */ { SSBB_ACT_LIGHT_THROW_AIR_F, PIKA_ANIM_LIGHTTHROWAIRF, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_AIR_B */ { SSBB_ACT_LIGHT_THROW_AIR_B, PIKA_ANIM_LIGHTTHROWAIRB, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_AIR_HI */ { SSBB_ACT_LIGHT_THROW_AIR_HI, PIKA_ANIM_LIGHTTHROWAIRHI, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_THROW_AIR_LW */ { SSBB_ACT_LIGHT_THROW_AIR_LW, PIKA_ANIM_LIGHTTHROWAIRLW, K, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_WALK_GET */ { SSBB_ACT_LIGHT_WALK_GET, PIKA_ANIM_LIGHTWALKGET, 0, 0, 0, 0 },
    /* SSBB_ACT_LIGHT_WALK_EAT */ { SSBB_ACT_LIGHT_WALK_EAT, PIKA_ANIM_LIGHTWALKEAT, 0, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_F */ { SSBB_ACT_SMASH_THROW_F, PIKA_ANIM_SMASHTHROWF, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_B */ { SSBB_ACT_SMASH_THROW_B, PIKA_ANIM_SMASHTHROWB, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_HI */ { SSBB_ACT_SMASH_THROW_HI, PIKA_ANIM_SMASHTHROWHI, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_LW */ { SSBB_ACT_SMASH_THROW_LW, PIKA_ANIM_SMASHTHROWLW, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_DASH */ { SSBB_ACT_SMASH_THROW_DASH, PIKA_ANIM_SMASHTHROWDASH, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_AIR_F */ { SSBB_ACT_SMASH_THROW_AIR_F, PIKA_ANIM_SMASHTHROWAIRF, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_AIR_B */ { SSBB_ACT_SMASH_THROW_AIR_B, PIKA_ANIM_SMASHTHROWAIRB, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_AIR_HI */ { SSBB_ACT_SMASH_THROW_AIR_HI, PIKA_ANIM_SMASHTHROWAIRHI, K, 0, 0, 0 },
    /* SSBB_ACT_SMASH_THROW_AIR_LW */ { SSBB_ACT_SMASH_THROW_AIR_LW, PIKA_ANIM_SMASHTHROWAIRLW, K, 0, 0, 0 },
    /* SSBB_ACT_SWING1 */ { SSBB_ACT_SWING1, PIKA_ANIM_SWING1, K, 0, 0, 0 },
    /* SSBB_ACT_SWING3 */ { SSBB_ACT_SWING3, PIKA_ANIM_SWING3, K, 0, 0, 0 },
    /* SSBB_ACT_SWING4 */ { SSBB_ACT_SWING4, PIKA_ANIM_SWING4, K, 0, 0, 0 },
    /* SSBB_ACT_SWING4_BAT */ { SSBB_ACT_SWING4_BAT, PIKA_ANIM_SWING4BAT, K, 0, 0, 0 },
    /* SSBB_ACT_SWING4_HOLD */ { SSBB_ACT_SWING4_HOLD, PIKA_ANIM_SWING4HOLD, K, 0, 0, 0 },
    /* SSBB_ACT_SWING4_START */ { SSBB_ACT_SWING4_START, PIKA_ANIM_SWING4START, K, 0, 0, 0 },
    /* SSBB_ACT_SWING_DASH */ { SSBB_ACT_SWING_DASH, PIKA_ANIM_SWINGDASH, K, 0, 0, 0 },
    /* SSBB_ACT_WAIT_ITEM */ { SSBB_ACT_WAIT_ITEM, PIKA_ANIM_WAITITEM, L, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_CATCH */ { SSBB_ACT_CLIFF_CATCH, PIKA_ANIM_CLIFFCATCH, 0, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_WAIT */ { SSBB_ACT_CLIFF_WAIT, PIKA_ANIM_CLIFFWAIT, L, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_CLIMB_QUICK */ { SSBB_ACT_CLIFF_CLIMB_QUICK, PIKA_ANIM_CLIFFCLIMBQUICK, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_CLIMB_SLOW */ { SSBB_ACT_CLIFF_CLIMB_SLOW, PIKA_ANIM_CLIFFCLIMBSLOW, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_ATTACK_QUICK */ { SSBB_ACT_CLIFF_ATTACK_QUICK, PIKA_ANIM_CLIFFATTACKQUICK, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_ATTACK_SLOW */ { SSBB_ACT_CLIFF_ATTACK_SLOW, PIKA_ANIM_CLIFFATTACKSLOW, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_ESCAPE_QUICK */ { SSBB_ACT_CLIFF_ESCAPE_QUICK, PIKA_ANIM_CLIFFESCAPEQUICK, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_ESCAPE_SLOW */ { SSBB_ACT_CLIFF_ESCAPE_SLOW, PIKA_ANIM_CLIFFESCAPESLOW, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_JUMP_QUICK1 */ { SSBB_ACT_CLIFF_JUMP_QUICK1, PIKA_ANIM_CLIFFJUMPQUICK1, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_JUMP_QUICK2 */ { SSBB_ACT_CLIFF_JUMP_QUICK2, PIKA_ANIM_CLIFFJUMPQUICK2, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_JUMP_SLOW1 */ { SSBB_ACT_CLIFF_JUMP_SLOW1, PIKA_ANIM_CLIFFJUMPSLOW1, K, 0, 0, 0 },
    /* SSBB_ACT_CLIFF_JUMP_SLOW2 */ { SSBB_ACT_CLIFF_JUMP_SLOW2, PIKA_ANIM_CLIFFJUMPSLOW2, K, 0, 0, 0 },
    /* SSBB_ACT_SWIM */ { SSBB_ACT_SWIM, PIKA_ANIM_SWIM, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_F */ { SSBB_ACT_SWIM_F, PIKA_ANIM_SWIMF, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_UP */ { SSBB_ACT_SWIM_UP, PIKA_ANIM_SWIMUP, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_TURN */ { SSBB_ACT_SWIM_TURN, PIKA_ANIM_SWIMTURN, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_END */ { SSBB_ACT_SWIM_END, PIKA_ANIM_SWIMEND, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_RISE */ { SSBB_ACT_SWIM_RISE, PIKA_ANIM_SWIMRISE, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_DROWN */ { SSBB_ACT_SWIM_DROWN, PIKA_ANIM_SWIMDROWN, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_DROWN_OUT */ { SSBB_ACT_SWIM_DROWN_OUT, PIKA_ANIM_SWIMDROWNOUT, L, 0, 0, 0 },
    /* SSBB_ACT_SWIM_UP_DAMAGE */ { SSBB_ACT_SWIM_UP_DAMAGE, PIKA_ANIM_SWIMUPDAMAGE, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_UP */ { SSBB_ACT_LADDER_UP, PIKA_ANIM_LADDERUP, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_DOWN */ { SSBB_ACT_LADDER_DOWN, PIKA_ANIM_LADDERDOWN, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_WAIT */ { SSBB_ACT_LADDER_WAIT, PIKA_ANIM_LADDERWAIT, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_CATCH_L */ { SSBB_ACT_LADDER_CATCH_L, PIKA_ANIM_LADDERCATCHL, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_CATCH_R */ { SSBB_ACT_LADDER_CATCH_R, PIKA_ANIM_LADDERCATCHR, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_CATCH_AIR_L */ { SSBB_ACT_LADDER_CATCH_AIR_L, PIKA_ANIM_LADDERCATCHAIRL, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_CATCH_AIR_R */ { SSBB_ACT_LADDER_CATCH_AIR_R, PIKA_ANIM_LADDERCATCHAIRR, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_CATCH_END_L */ { SSBB_ACT_LADDER_CATCH_END_L, PIKA_ANIM_LADDERCATCHENDL, L, 0, 0, 0 },
    /* SSBB_ACT_LADDER_CATCH_END_R */ { SSBB_ACT_LADDER_CATCH_END_R, PIKA_ANIM_LADDERCATCHENDR, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP */ { SSBB_ACT_SLIP, PIKA_ANIM_SLIP, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_WAIT */ { SSBB_ACT_SLIP_WAIT, PIKA_ANIM_SLIPWAIT, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_DASH */ { SSBB_ACT_SLIP_DASH, PIKA_ANIM_SLIPDASH, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_TURN */ { SSBB_ACT_SLIP_TURN, PIKA_ANIM_SLIPTURN, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_STAND */ { SSBB_ACT_SLIP_STAND, PIKA_ANIM_SLIPSTAND, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_DOWN */ { SSBB_ACT_SLIP_DOWN, PIKA_ANIM_SLIPDOWN, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_ATTACK */ { SSBB_ACT_SLIP_ATTACK, PIKA_ANIM_SLIPATTACK, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_ESCAPE_F */ { SSBB_ACT_SLIP_ESCAPE_F, PIKA_ANIM_SLIPESCAPEF, L, 0, 0, 0 },
    /* SSBB_ACT_SLIP_ESCAPE_B */ { SSBB_ACT_SLIP_ESCAPE_B, PIKA_ANIM_SLIPESCAPEB, L, 0, 0, 0 },
    /* SSBB_ACT_FURA_FURA */ { SSBB_ACT_FURA_FURA, PIKA_ANIM_FURAFURA, K, 0, 0, 0 },
    /* SSBB_ACT_FURA_FURA_END */ { SSBB_ACT_FURA_FURA_END, PIKA_ANIM_FURAFURAEND, K, 0, 0, 0 },
    /* SSBB_ACT_FURA_FURA_START_D */ { SSBB_ACT_FURA_FURA_START_D, PIKA_ANIM_FURAFURASTARTD, K, 0, 0, 0 },
    /* SSBB_ACT_FURA_FURA_START_U */ { SSBB_ACT_FURA_FURA_START_U, PIKA_ANIM_FURAFURASTARTU, K, 0, 0, 0 },
    /* SSBB_ACT_FURA_SLEEP_START */ { SSBB_ACT_FURA_SLEEP_START, PIKA_ANIM_FURASLEEPSTART, 0, 0, 0, 0 },
    /* SSBB_ACT_FURA_SLEEP_LOOP */ { SSBB_ACT_FURA_SLEEP_LOOP, PIKA_ANIM_FURASLEEPLOOP, 0, 0, 0, 0 },
    /* SSBB_ACT_FURA_SLEEP_END */ { SSBB_ACT_FURA_SLEEP_END, PIKA_ANIM_FURASLEEPEND, 0, 0, 0, 0 },
    /* SSBB_ACT_PASSIVE */ { SSBB_ACT_PASSIVE, PIKA_ANIM_PASSIVE, K, 0, 0, 0 },
    /* SSBB_ACT_PASSIVE_STAND_F */ { SSBB_ACT_PASSIVE_STAND_F, PIKA_ANIM_PASSIVESTANDF, K, 0, 0, 0 },
    /* SSBB_ACT_PASSIVE_STAND_B */ { SSBB_ACT_PASSIVE_STAND_B, PIKA_ANIM_PASSIVESTANDB, K, 0, 0, 0 },
    /* SSBB_ACT_PASSIVE_WALL */ { SSBB_ACT_PASSIVE_WALL, PIKA_ANIM_PASSIVEWALL, K, 0, 0, 0 },
    /* SSBB_ACT_PASSIVE_WALL_JUMP */ { SSBB_ACT_PASSIVE_WALL_JUMP, PIKA_ANIM_PASSIVEWALLJUMP, K, 0, 0, 0 },
    /* SSBB_ACT_PASSIVE_CEIL */ { SSBB_ACT_PASSIVE_CEIL, PIKA_ANIM_PASSIVECEIL, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_WAIT_D */ { SSBB_ACT_DOWN_WAIT_D, PIKA_ANIM_DOWNWAITD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_WAIT_U */ { SSBB_ACT_DOWN_WAIT_U, PIKA_ANIM_DOWNWAITU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_STAND_D */ { SSBB_ACT_DOWN_STAND_D, PIKA_ANIM_DOWNSTANDD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_STAND_U */ { SSBB_ACT_DOWN_STAND_U, PIKA_ANIM_DOWNSTANDU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_ATTACK_D */ { SSBB_ACT_DOWN_ATTACK_D, PIKA_ANIM_DOWNATTACKD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_ATTACK_U */ { SSBB_ACT_DOWN_ATTACK_U, PIKA_ANIM_DOWNATTACKU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_BOUND_D */ { SSBB_ACT_DOWN_BOUND_D, PIKA_ANIM_DOWNBOUNDD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_BOUND_U */ { SSBB_ACT_DOWN_BOUND_U, PIKA_ANIM_DOWNBOUNDU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_DAMAGE_D */ { SSBB_ACT_DOWN_DAMAGE_D, PIKA_ANIM_DOWNDAMAGED, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_DAMAGE_U */ { SSBB_ACT_DOWN_DAMAGE_U, PIKA_ANIM_DOWNDAMAGEU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_DAMAGE_D3 */ { SSBB_ACT_DOWN_DAMAGE_D3, PIKA_ANIM_DOWNDAMAGED3, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_DAMAGE_U3 */ { SSBB_ACT_DOWN_DAMAGE_U3, PIKA_ANIM_DOWNDAMAGEU3, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_BACK_D */ { SSBB_ACT_DOWN_BACK_D, PIKA_ANIM_DOWNBACKD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_BACK_U */ { SSBB_ACT_DOWN_BACK_U, PIKA_ANIM_DOWNBACKU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_FORWARD_D */ { SSBB_ACT_DOWN_FORWARD_D, PIKA_ANIM_DOWNFORWARDD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_FORWARD_U */ { SSBB_ACT_DOWN_FORWARD_U, PIKA_ANIM_DOWNFORWARDU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_EAT_D */ { SSBB_ACT_DOWN_EAT_D, PIKA_ANIM_DOWNEATD, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_EAT_U */ { SSBB_ACT_DOWN_EAT_U, PIKA_ANIM_DOWNEATU, K, 0, 0, 0 },
    /* SSBB_ACT_DOWN_SPOT_D */ { SSBB_ACT_DOWN_SPOT_D, PIKA_ANIM_DOWNSPOTD, K, 0, 0, 0 },
    /* SSBB_ACT_OTTOTTO */ { SSBB_ACT_OTTOTTO, PIKA_ANIM_OTTOTTO, K, 0, 0, 0 },
    /* SSBB_ACT_OTTOTTO_WAIT */ { SSBB_ACT_OTTOTTO_WAIT, PIKA_ANIM_OTTOTTOWAIT, K, 0, 0, 0 },
    /* SSBB_ACT_STOP_WALL */ { SSBB_ACT_STOP_WALL, PIKA_ANIM_STOPWALL, 0, 0, 0, 0 },
    /* SSBB_ACT_STOP_CEIL */ { SSBB_ACT_STOP_CEIL, PIKA_ANIM_STOPCEIL, 0, 0, 0, 0 },
    /* SSBB_ACT_MISS_FOOT */ { SSBB_ACT_MISS_FOOT, PIKA_ANIM_MISSFOOT, 0, 0, 0, 0 },
    /* SSBB_ACT_REBOUND */ { SSBB_ACT_REBOUND, PIKA_ANIM_REBOUND, K, 0, 0, 0 },
    /* SSBB_ACT_WALL_DAMAGE */ { SSBB_ACT_WALL_DAMAGE, PIKA_ANIM_WALLDAMAGE, K, 0, 0, 0 },
    /* SSBB_ACT_GEKIKARA_WAIT */ { SSBB_ACT_GEKIKARA_WAIT, PIKA_ANIM_GEKIKARAWAIT, 0, 0, 0, 0 },
    /* SSBB_ACT_WIN1 */ { SSBB_ACT_WIN1, PIKA_ANIM_WIN1, K, 0, 0, 0 },
    /* SSBB_ACT_WIN1_WAIT */ { SSBB_ACT_WIN1_WAIT, PIKA_ANIM_WIN1WAIT, K, 0, 0, 0 },
    /* SSBB_ACT_WIN2 */ { SSBB_ACT_WIN2, PIKA_ANIM_WIN2, K, 0, 0, 0 },
    /* SSBB_ACT_WIN2_WAIT */ { SSBB_ACT_WIN2_WAIT, PIKA_ANIM_WIN2WAIT, K, 0, 0, 0 },
    /* SSBB_ACT_WIN3 */ { SSBB_ACT_WIN3, PIKA_ANIM_WIN3, K, 0, 0, 0 },
    /* SSBB_ACT_WIN3_WAIT */ { SSBB_ACT_WIN3_WAIT, PIKA_ANIM_WIN3WAIT, K, 0, 0, 0 },
    /* SSBB_ACT_LOSE */ { SSBB_ACT_LOSE, PIKA_ANIM_LOSE, K, 0, 0, 0 },
    /* SSBB_ACT_ENTRY_L */ { SSBB_ACT_ENTRY_L, PIKA_ANIM_ENTRYL, K, 0, 0, 0 },
    /* SSBB_ACT_ENTRY_R */ { SSBB_ACT_ENTRY_R, PIKA_ANIM_ENTRYR, K, 0, 0, 0 },
    /* SSBB_ACT_APPEAL_HI */ { SSBB_ACT_APPEAL_HI, PIKA_ANIM_APPEALHI, K, 0, 0, 0 },
    /* SSBB_ACT_APPEAL_LW */ { SSBB_ACT_APPEAL_LW, PIKA_ANIM_APPEALLW, K, 0, 0, 0 },
    /* SSBB_ACT_APPEAL_SL */ { SSBB_ACT_APPEAL_SL, PIKA_ANIM_APPEALSL, K, 0, 0, 0 },
    /* SSBB_ACT_APPEAL_SR */ { SSBB_ACT_APPEAL_SR, PIKA_ANIM_APPEALSR, K, 0, 0, 0 },
};

#undef L
#undef A
#undef G
#undef R
#undef M
#undef I
#undef K

// ── Helper: get action def ──
static inline const SSBBActionDef* SSBBAction_Get(SSBBActionId id) {
    if (id >= SSBB_ACT_MAX)
        return NULL;
    return &sSSBBActionTable[id];
}

// ── Helper: get SSBBAnim for action ──
static inline const struct SSBBAnim* SSBBAction_GetAnim(SSBBActionId id) {
    const SSBBActionDef* def = SSBBAction_Get(id);
    if (!def || def->animId >= PIKA_ANIM_MAX)
        return NULL;
    return pikachu_ssbb_all_anims[def->animId];
}

#endif // SSBB_ACTION_DEFS_H
