/**
 * @file mm_anims.h
 * @brief MM Animation Definitions for use in OOT
 *
 * This file defines all MM animations with their OTR paths and frame counts.
 * Use with MmAnim_Load() from anim_translator/mm_anim_loader.h
 *
 * CRITICAL: OOT and MM use IDENTICAL raw format for Link animations!
 * - 67 s16 per frame (66 components + 1 appearanceInfo)
 * - Same layout (root pos, root rot, limb rotations)
 * - Only fix needed: baseTransl (X=-57, Z=0)
 * - Uses LinkAnimationHeader (NOT AnimationHeader!)
 *
 * Animation paths follow 2Ship pattern:
 * - Header: objects/gameplay_keep/gPlayerAnim_*
 * - Data: misc/link_animetion/gPlayerAnim_*_Data
 */

#ifndef MM_ANIMS_H
#define MM_ANIMS_H

#include "z64.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Animation Definition Struct
// ============================================================================

/**
 * MM Animation definition
 * Contains all info needed to load and use an MM animation
 */
typedef struct {
    const char* path; // OTR path (misc/link_animetion/..._Data)
    s16 frameCount;   // Number of frames (from MM decomp)
    u8 limbCount;     // Number of limbs (22 for Human Link)
} MmAnimDef;

// ============================================================================
// Limb Counts
// ============================================================================

// ALL MM Link forms use 22 limbs (confirmed from 2Ship: LINK_*_LIMB_MAX = 0x16)
// Visual differences come from different display lists per limb, not limb count.
// This allows all forms to share the same animation data format (67 s16 per frame).
#define MM_LIMB_COUNT_HUMAN 22 // Human Link, Child Link
#define MM_LIMB_COUNT_GORON 22 // Goron Link (LINK_GORON_LIMB_MAX = 0x16)
#define MM_LIMB_COUNT_ZORA 22  // Zora Link (LINK_ZORA_LIMB_MAX = 0x16)
#define MM_LIMB_COUNT_DEKU 22  // Deku Link (LINK_DEKU_LIMB_MAX = 0x16)

// ============================================================================
// Frame Data Constants
// ============================================================================

// Raw frame format: limbCount * 3 components + 1 appearanceInfo = 67 for Human
#define MM_FRAME_S16_COUNT_HUMAN 67
#define MM_FRAME_S16_COUNT_GORON 52 // 17*3 + 1
#define MM_FRAME_S16_COUNT_ZORA 70  // 23*3 + 1
#define MM_FRAME_S16_COUNT_DEKU 37  // 12*3 + 1

// ============================================================================
// Animation ID Enum
// Generated from MM decomp gameplay_keep.h and link_animetion.h
// ============================================================================

typedef enum MmAnimId {
    // ========================================
    // Human Link Animations (gPlayerAnim_link_*)
    // ========================================

    // Normal/Idle animations
    MM_ANIM_LINK_NORMAL_WAIT,
    MM_ANIM_LINK_NORMAL_WAIT_FREE,
    MM_ANIM_LINK_NORMAL_WALK,
    MM_ANIM_LINK_NORMAL_WALK_FREE,
    MM_ANIM_LINK_NORMAL_WALK_ENDL,
    MM_ANIM_LINK_NORMAL_WALK_ENDR,
    MM_ANIM_LINK_NORMAL_WALK_ENDL_FREE,
    MM_ANIM_LINK_NORMAL_WALK_ENDR_FREE,
    MM_ANIM_LINK_NORMAL_RUN,
    MM_ANIM_LINK_NORMAL_RUN_FREE,
    MM_ANIM_LINK_NORMAL_RUN_JUMP,
    MM_ANIM_LINK_NORMAL_RUN_JUMP_END,

    // Fall/Landing animations
    MM_ANIM_LINK_NORMAL_FALL,
    MM_ANIM_LINK_NORMAL_FALL_UP,
    MM_ANIM_LINK_NORMAL_FALL_UP_FREE,
    MM_ANIM_LINK_NORMAL_FALL_WAIT,
    MM_ANIM_LINK_NORMAL_LANDING,
    MM_ANIM_LINK_NORMAL_LANDING_FREE,
    MM_ANIM_LINK_NORMAL_LANDING_ROLL,
    MM_ANIM_LINK_NORMAL_LANDING_ROLL_FREE,
    MM_ANIM_LINK_NORMAL_LANDING_WAIT,
    MM_ANIM_LINK_NORMAL_SHORT_LANDING,
    MM_ANIM_LINK_NORMAL_SHORT_LANDING_FREE,

    // Jump animations
    MM_ANIM_LINK_NORMAL_JUMP,
    MM_ANIM_LINK_NORMAL_JUMP_CLIMB_HOLD,
    MM_ANIM_LINK_NORMAL_JUMP_CLIMB_HOLD_FREE,
    MM_ANIM_LINK_NORMAL_JUMP_CLIMB_UP,
    MM_ANIM_LINK_NORMAL_JUMP_CLIMB_UP_FREE,
    MM_ANIM_LINK_NORMAL_JUMP_CLIMB_WAIT,
    MM_ANIM_LINK_NORMAL_JUMP_CLIMB_WAIT_FREE,
    MM_ANIM_LINK_NORMAL_250JUMP_START,

    // Side/Back movement
    MM_ANIM_LINK_NORMAL_SIDE_WALK,
    MM_ANIM_LINK_NORMAL_SIDE_WALK_FREE,
    MM_ANIM_LINK_NORMAL_SIDE_WALKL_FREE,
    MM_ANIM_LINK_NORMAL_SIDE_WALKR_FREE,
    MM_ANIM_LINK_NORMAL_BACK_WALK,
    MM_ANIM_LINK_NORMAL_BACK_RUN,
    MM_ANIM_LINK_NORMAL_BACK_BRAKE,
    MM_ANIM_LINK_NORMAL_BACK_BRAKE_END,
    MM_ANIM_LINK_NORMAL_BACKSPACE,

    // Damage animations
    MM_ANIM_LINK_NORMAL_FRONT_HIT,
    MM_ANIM_LINK_NORMAL_BACK_HIT,
    MM_ANIM_LINK_NORMAL_FRONT_SHIT,
    MM_ANIM_LINK_NORMAL_FRONT_SHITR,
    MM_ANIM_LINK_NORMAL_BACK_SHIT,
    MM_ANIM_LINK_NORMAL_BACK_SHITR,
    MM_ANIM_LINK_NORMAL_FRONT_DOWNA,
    MM_ANIM_LINK_NORMAL_FRONT_DOWNB,
    MM_ANIM_LINK_NORMAL_FRONT_DOWN_WAKE,
    MM_ANIM_LINK_NORMAL_BACK_DOWNA,
    MM_ANIM_LINK_NORMAL_BACK_DOWNB,
    MM_ANIM_LINK_NORMAL_BACK_DOWN_WAKE,
    MM_ANIM_LINK_NORMAL_ELECTRIC_SHOCK,
    MM_ANIM_LINK_NORMAL_ELECTRIC_SHOCK_END,
    MM_ANIM_LINK_NORMAL_ICE_DOWN,
    MM_ANIM_LINK_NORMAL_DAMAGE_RUN_FREE,

    // Hip/Sit animations
    MM_ANIM_LINK_NORMAL_HIP_DOWN,
    MM_ANIM_LINK_NORMAL_HIP_DOWN_FREE,
    MM_ANIM_LINK_NORMAL_HIP_DOWN_LONG,

    // Defense animations
    MM_ANIM_LINK_NORMAL_DEFENSE,
    MM_ANIM_LINK_NORMAL_DEFENSE_FREE,
    MM_ANIM_LINK_NORMAL_DEFENSE_WAIT,
    MM_ANIM_LINK_NORMAL_DEFENSE_WAIT_FREE,
    MM_ANIM_LINK_NORMAL_DEFENSE_END,
    MM_ANIM_LINK_NORMAL_DEFENSE_END_FREE,
    MM_ANIM_LINK_NORMAL_DEFENSE_HIT,
    MM_ANIM_LINK_NORMAL_DEFENSE_KIRU,

    // Climb animations
    MM_ANIM_LINK_NORMAL_CLIMB_STARTA,
    MM_ANIM_LINK_NORMAL_CLIMB_STARTB,
    MM_ANIM_LINK_NORMAL_CLIMB_DOWN,
    MM_ANIM_LINK_NORMAL_CLIMB_UP,
    MM_ANIM_LINK_NORMAL_CLIMB_UPL,
    MM_ANIM_LINK_NORMAL_CLIMB_UPR,
    MM_ANIM_LINK_NORMAL_CLIMB_ENDAL,
    MM_ANIM_LINK_NORMAL_CLIMB_ENDAR,
    MM_ANIM_LINK_NORMAL_CLIMB_ENDBL,
    MM_ANIM_LINK_NORMAL_CLIMB_ENDBR,

    // Front climb animations
    MM_ANIM_LINK_NORMAL_FCLIMB_STARTA,
    MM_ANIM_LINK_NORMAL_FCLIMB_STARTB,
    MM_ANIM_LINK_NORMAL_FCLIMB_UPL,
    MM_ANIM_LINK_NORMAL_FCLIMB_UPR,
    MM_ANIM_LINK_NORMAL_FCLIMB_SIDEL,
    MM_ANIM_LINK_NORMAL_FCLIMB_SIDER,
    MM_ANIM_LINK_NORMAL_FCLIMB_HOLD2UPL,

    // Push/Pull animations
    MM_ANIM_LINK_NORMAL_PUSH_START,
    MM_ANIM_LINK_NORMAL_PUSHING,
    MM_ANIM_LINK_NORMAL_PUSH_WAIT,
    MM_ANIM_LINK_NORMAL_PUSH_WAIT_END,
    MM_ANIM_LINK_NORMAL_PUSH_END,
    MM_ANIM_LINK_NORMAL_PULL_START,
    MM_ANIM_LINK_NORMAL_PULL_START_FREE,
    MM_ANIM_LINK_NORMAL_PULLING,
    MM_ANIM_LINK_NORMAL_PULLING_FREE,
    MM_ANIM_LINK_NORMAL_PULL_END,
    MM_ANIM_LINK_NORMAL_PULL_END_FREE,

    // Carry/Throw animations
    MM_ANIM_LINK_NORMAL_TAKE_OUT,
    MM_ANIM_LINK_NORMAL_PUT,
    MM_ANIM_LINK_NORMAL_PUT_FREE,
    MM_ANIM_LINK_NORMAL_THROW,
    MM_ANIM_LINK_NORMAL_THROW_FREE,
    MM_ANIM_LINK_NORMAL_CARRYB,
    MM_ANIM_LINK_NORMAL_CARRYB_FREE,
    MM_ANIM_LINK_NORMAL_CARRYB_WAIT,
    MM_ANIM_LINK_NORMAL_NOCARRY_FREE,
    MM_ANIM_LINK_NORMAL_NOCARRY_FREE_END,
    MM_ANIM_LINK_NORMAL_NOCARRY_FREE_WAIT,

    // Hang animations
    MM_ANIM_LINK_NORMAL_HANG_UP_DOWN,

    // Slope animations
    MM_ANIM_LINK_NORMAL_UP_SLOPE_SLIP,
    MM_ANIM_LINK_NORMAL_UP_SLOPE_SLIP_END,
    MM_ANIM_LINK_NORMAL_UP_SLOPE_SLIP_END_FREE,
    MM_ANIM_LINK_NORMAL_UP_SLOPE_SLIP_END_LONG,
    MM_ANIM_LINK_NORMAL_DOWN_SLOPE_SLIP,
    MM_ANIM_LINK_NORMAL_DOWN_SLOPE_SLIP_END,
    MM_ANIM_LINK_NORMAL_DOWN_SLOPE_SLIP_END_FREE,
    MM_ANIM_LINK_NORMAL_DOWN_SLOPE_SLIP_END_LONG,

    // Step up animations
    MM_ANIM_LINK_NORMAL_100STEP_UP,
    MM_ANIM_LINK_NORMAL_150STEP_UP,

    // Turn animations
    MM_ANIM_LINK_NORMAL_45_TURN,
    MM_ANIM_LINK_NORMAL_45_TURN_FREE,
    MM_ANIM_LINK_NORMAL_WAITL2WAIT,
    MM_ANIM_LINK_NORMAL_WAITR2WAIT,
    MM_ANIM_LINK_NORMAL_WAIT2WAITR,

    // State change animations
    MM_ANIM_LINK_NORMAL_FREE2FREE,
    MM_ANIM_LINK_NORMAL_FREE2FREEB,
    MM_ANIM_LINK_NORMAL_NORMAL2FREE,
    MM_ANIM_LINK_NORMAL_FIGHTER2FREE,
    MM_ANIM_LINK_NORMAL_NORMAL2FIGHTER,
    MM_ANIM_LINK_NORMAL_NORMAL2FIGHTER_FREE,
    MM_ANIM_LINK_NORMAL_FREE2FIGHTER_FREE,

    // Item/Check animations
    MM_ANIM_LINK_NORMAL_CHECK,
    MM_ANIM_LINK_NORMAL_CHECK_FREE,
    MM_ANIM_LINK_NORMAL_CHECK_WAIT,
    MM_ANIM_LINK_NORMAL_CHECK_WAIT_FREE,
    MM_ANIM_LINK_NORMAL_CHECK_END,
    MM_ANIM_LINK_NORMAL_CHECK_END_FREE,
    MM_ANIM_LINK_NORMAL_GIVE_OTHER,
    MM_ANIM_LINK_NORMAL_BOX_KICK,

    // Talk animations
    MM_ANIM_LINK_NORMAL_TALK_FREE,
    MM_ANIM_LINK_NORMAL_TALK_FREE_WAIT,

    // Bomb animations
    MM_ANIM_LINK_NORMAL_NORMAL2BOM,
    MM_ANIM_LINK_NORMAL_FREE2BOM,
    MM_ANIM_LINK_NORMAL_LONG2BOM,
    MM_ANIM_LINK_NORMAL_LIGHT_BOM,
    MM_ANIM_LINK_NORMAL_LIGHT_BOM_END,

    // Ocarina animations
    MM_ANIM_LINK_NORMAL_OKARINA_START,
    MM_ANIM_LINK_NORMAL_OKARINA_END,
    MM_ANIM_LINK_NORMAL_OKARINA_SWING,

    // Redead attack
    MM_ANIM_LINK_NORMAL_RE_DEAD_ATTACK,
    MM_ANIM_LINK_NORMAL_RE_DEAD_ATTACK_WAIT,

    // New roll/side jump (20f = 20 frames)
    MM_ANIM_LINK_NORMAL_NEWROLL_JUMP_20F,
    MM_ANIM_LINK_NORMAL_NEWROLL_JUMP_END_20F,
    MM_ANIM_LINK_NORMAL_NEWSIDE_JUMP_20F,
    MM_ANIM_LINK_NORMAL_NEWSIDE_JUMP_END_20F,

    // Water/Swim transitions
    MM_ANIM_LINK_NORMAL_RUN_JUMP_WATER_FALL,
    MM_ANIM_LINK_NORMAL_RUN_JUMP_WATER_FALL_WAIT,

    // Free wait states
    MM_ANIM_LINK_NORMAL_WAITL_FREE,
    MM_ANIM_LINK_NORMAL_WAITR_FREE,

    // ========================================
    // Fighter (Sword) Animations
    // ========================================

    // Basic sword stance
    MM_ANIM_LINK_FIGHTER_WAIT_LONG,
    MM_ANIM_LINK_FIGHTER_WAITL_LONG,
    MM_ANIM_LINK_FIGHTER_WAITR_LONG,
    MM_ANIM_LINK_FIGHTER_WAITL2WAIT_LONG,
    MM_ANIM_LINK_FIGHTER_WAITR2WAIT_LONG,
    MM_ANIM_LINK_FIGHTER_WAIT2WAITR_LONG,

    // Movement with sword
    MM_ANIM_LINK_FIGHTER_RUN,
    MM_ANIM_LINK_FIGHTER_RUN_LONG,
    MM_ANIM_LINK_FIGHTER_WALK_LONG,
    MM_ANIM_LINK_FIGHTER_WALK_ENDL_LONG,
    MM_ANIM_LINK_FIGHTER_WALK_ENDR_LONG,
    MM_ANIM_LINK_FIGHTER_SIDE_WALK_LONG,
    MM_ANIM_LINK_FIGHTER_SIDE_WALKL_LONG,
    MM_ANIM_LINK_FIGHTER_SIDE_WALKR_LONG,
    MM_ANIM_LINK_FIGHTER_DAMAGE_RUN,
    MM_ANIM_LINK_FIGHTER_DAMAGE_RUN_LONG,

    // Sword transitions
    MM_ANIM_LINK_FIGHTER_NORMAL2FIGHTER,
    MM_ANIM_LINK_FIGHTER_FIGHTER2LONG,

    // Normal slash
    MM_ANIM_LINK_FIGHTER_NORMAL_KIRU,
    MM_ANIM_LINK_FIGHTER_NORMAL_KIRU_END,
    MM_ANIM_LINK_FIGHTER_NORMAL_KIRU_ENDR,
    MM_ANIM_LINK_FIGHTER_NORMAL_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_NORMAL_KIRU_FINSH_END,

    // Left normal slash
    MM_ANIM_LINK_FIGHTER_LNORMAL_KIRU,
    MM_ANIM_LINK_FIGHTER_LNORMAL_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LNORMAL_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_LNORMAL_KIRU_FINSH_END,

    // Side slashes
    MM_ANIM_LINK_FIGHTER_RSIDE_KIRU,
    MM_ANIM_LINK_FIGHTER_RSIDE_KIRU_END,
    MM_ANIM_LINK_FIGHTER_RSIDE_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_RSIDE_KIRU_FINSH_END,
    MM_ANIM_LINK_FIGHTER_LSIDE_KIRU,
    MM_ANIM_LINK_FIGHTER_LSIDE_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LSIDE_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_LSIDE_KIRU_FINSH_END,

    // Double side slashes
    MM_ANIM_LINK_FIGHTER_LRSIDE_KIRU,
    MM_ANIM_LINK_FIGHTER_LRSIDE_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LRSIDE_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_LRSIDE_KIRU_FINSH_END,
    MM_ANIM_LINK_FIGHTER_LLSIDE_KIRU,
    MM_ANIM_LINK_FIGHTER_LLSIDE_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LLSIDE_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_LLSIDE_KIRU_FINSH_END,

    // Pierce/Stab
    MM_ANIM_LINK_FIGHTER_PIERCE_KIRU,
    MM_ANIM_LINK_FIGHTER_PIERCE_KIRU_END,
    MM_ANIM_LINK_FIGHTER_PIERCE_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_PIERCE_KIRU_FINSH_END,
    MM_ANIM_LINK_FIGHTER_LPIERCE_KIRU,
    MM_ANIM_LINK_FIGHTER_LPIERCE_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LPIERCE_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_LPIERCE_KIRU_FINSH_END,

    // Rolling slashes
    MM_ANIM_LINK_FIGHTER_ROLLING_KIRU,
    MM_ANIM_LINK_FIGHTER_ROLLING_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LROLLING_KIRU,
    MM_ANIM_LINK_FIGHTER_LROLLING_KIRU_END,
    MM_ANIM_LINK_FIGHTER_WROLLING_KIRU,
    MM_ANIM_LINK_FIGHTER_WROLLING_KIRU_END,

    // Turn slashes
    MM_ANIM_LINK_FIGHTER_TURN_KIRUL,
    MM_ANIM_LINK_FIGHTER_TURN_KIRUL_END,
    MM_ANIM_LINK_FIGHTER_TURN_KIRUR,
    MM_ANIM_LINK_FIGHTER_TURN_KIRUR_END,

    // Power (spin) attacks
    MM_ANIM_LINK_FIGHTER_POWER_KIRU_START,
    MM_ANIM_LINK_FIGHTER_POWER_KIRU_STARTL,
    MM_ANIM_LINK_FIGHTER_POWER_KIRU_WAIT,
    MM_ANIM_LINK_FIGHTER_POWER_KIRU_WAIT_END,
    MM_ANIM_LINK_FIGHTER_POWER_KIRU_WALK,
    MM_ANIM_LINK_FIGHTER_POWER_KIRU_SIDE_WALK,
    MM_ANIM_LINK_FIGHTER_POWER_JUMP_KIRU_END,

    // Left power attacks
    MM_ANIM_LINK_FIGHTER_LPOWER_KIRU_START,
    MM_ANIM_LINK_FIGHTER_LPOWER_KIRU_WAIT,
    MM_ANIM_LINK_FIGHTER_LPOWER_KIRU_WAIT_END,
    MM_ANIM_LINK_FIGHTER_LPOWER_KIRU_WALK,
    MM_ANIM_LINK_FIGHTER_LPOWER_KIRU_SIDE_WALK,
    MM_ANIM_LINK_FIGHTER_LPOWER_JUMP_KIRU,
    MM_ANIM_LINK_FIGHTER_LPOWER_JUMP_KIRU_END,
    MM_ANIM_LINK_FIGHTER_LPOWER_JUMP_KIRU_HIT,

    // Jump attacks
    MM_ANIM_LINK_FIGHTER_JUMP_KIRU_FINSH,
    MM_ANIM_LINK_FIGHTER_JUMP_KIRU_FINSH_END,
    MM_ANIM_LINK_FIGHTER_JUMP_ROLLKIRU,

    // Backturn jump (backflip slash) - TESTED AND WORKING!
    MM_ANIM_LINK_FIGHTER_BACKTURN_JUMP,
    MM_ANIM_LINK_FIGHTER_BACKTURN_JUMP_END,
    MM_ANIM_LINK_FIGHTER_BACKTURN_JUMP_ENDR,

    // Front jump
    MM_ANIM_LINK_FIGHTER_FRONT_JUMP,
    MM_ANIM_LINK_FIGHTER_FRONT_JUMP_END,
    MM_ANIM_LINK_FIGHTER_FRONT_JUMP_ENDR,

    // Side jumps
    MM_ANIM_LINK_FIGHTER_LSIDE_JUMP,
    MM_ANIM_LINK_FIGHTER_LSIDE_JUMP_END,
    MM_ANIM_LINK_FIGHTER_LSIDE_JUMP_ENDL,
    MM_ANIM_LINK_FIGHTER_RSIDE_JUMP,
    MM_ANIM_LINK_FIGHTER_RSIDE_JUMP_END,
    MM_ANIM_LINK_FIGHTER_RSIDE_JUMP_ENDR,

    // Rebound
    MM_ANIM_LINK_FIGHTER_REBOUND,
    MM_ANIM_LINK_FIGHTER_REBOUNDR,
    MM_ANIM_LINK_FIGHTER_REBOUND_LONG,
    MM_ANIM_LINK_FIGHTER_REBOUND_LONGR,

    // Landing roll
    MM_ANIM_LINK_FIGHTER_LANDING_ROLL_LONG,

    // Defense with sword
    MM_ANIM_LINK_FIGHTER_DEFENSE_LONG_HIT,

    // ========================================
    // Anchor (Z-Target) Animations
    // ========================================
    MM_ANIM_LINK_ANCHOR_WAITL,
    MM_ANIM_LINK_ANCHOR_WAITR,
    MM_ANIM_LINK_ANCHOR_WAITL2DEFENSE,
    MM_ANIM_LINK_ANCHOR_WAITR2DEFENSE,
    MM_ANIM_LINK_ANCHOR_WAITL2DEFENSE_LONG,
    MM_ANIM_LINK_ANCHOR_WAITR2DEFENSE_LONG,
    MM_ANIM_LINK_ANCHOR_ANCHOR2FIGHTER,
    MM_ANIM_LINK_ANCHOR_SIDE_WALKL,
    MM_ANIM_LINK_ANCHOR_SIDE_WALKR,
    MM_ANIM_LINK_ANCHOR_BACK_WALK,
    MM_ANIM_LINK_ANCHOR_BACK_BRAKE,
    MM_ANIM_LINK_ANCHOR_DEFENSE_HIT,
    MM_ANIM_LINK_ANCHOR_FRONT_HITR,
    MM_ANIM_LINK_ANCHOR_BACK_HITR,
    MM_ANIM_LINK_ANCHOR_DEFENSE_LONG_HITL,
    MM_ANIM_LINK_ANCHOR_DEFENSE_LONG_HITR,
    MM_ANIM_LINK_ANCHOR_LANDINGR,

    // Anchor attacks
    MM_ANIM_LINK_ANCHOR_NORMAL_KIRU_FINSH_ENDR,
    MM_ANIM_LINK_ANCHOR_LNORMAL_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_LNORMAL_KIRU_FINSH_ENDR,
    MM_ANIM_LINK_ANCHOR_PIERCE_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_PIERCE_KIRU_FINSH_ENDR,
    MM_ANIM_LINK_ANCHOR_ROLLING_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_LROLLING_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_LSIDE_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_LSIDE_KIRU_FINSH_ENDR,
    MM_ANIM_LINK_ANCHOR_RSIDE_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_RSIDE_KIRU_FINSH_ENDR,
    MM_ANIM_LINK_ANCHOR_LRSIDE_KIRU_ENDR,
    MM_ANIM_LINK_ANCHOR_LRSIDE_KIRU_FINSH_ENDL,
    MM_ANIM_LINK_ANCHOR_LLSIDE_KIRU_ENDL,
    MM_ANIM_LINK_ANCHOR_LLSIDE_KIRU_FINSH_ENDR,
    MM_ANIM_LINK_ANCHOR_LPIERCE_KIRU_ENDL,
    MM_ANIM_LINK_ANCHOR_LPIERCE_KIRU_FINSH_ENDR,

    // ========================================
    // Bow Animations
    // ========================================
    MM_ANIM_LINK_BOW_BOW_READY,
    MM_ANIM_LINK_BOW_BOW_WAIT,
    MM_ANIM_LINK_BOW_BOW_SHOOT_END,
    MM_ANIM_LINK_BOW_BOW_SHOOT_NEXT,
    MM_ANIM_LINK_BOW_WALK2READY,
    MM_ANIM_LINK_BOW_SIDE_WALK,
    MM_ANIM_LINK_BOW_DEFENSE,
    MM_ANIM_LINK_BOW_DEFENSE_WAIT,

    // ========================================
    // Hook/Hookshot Animations
    // ========================================
    MM_ANIM_LINK_HOOK_SHOT_READY,
    MM_ANIM_LINK_HOOK_WAIT,
    MM_ANIM_LINK_HOOK_WALK2READY,
    MM_ANIM_LINK_HOOK_FLY_START,
    MM_ANIM_LINK_HOOK_FLY_WAIT,

    // ========================================
    // Bottle Animations
    // ========================================
    MM_ANIM_LINK_BOTTLE_BUG_IN,
    MM_ANIM_LINK_BOTTLE_BUG_OUT,
    MM_ANIM_LINK_BOTTLE_BUG_MISS,
    MM_ANIM_LINK_BOTTLE_FISH_IN,
    MM_ANIM_LINK_BOTTLE_FISH_OUT,
    MM_ANIM_LINK_BOTTLE_FISH_MISS,
    MM_ANIM_LINK_BOTTLE_DRINK_DEMO_START,
    MM_ANIM_LINK_BOTTLE_DRINK_DEMO_WAIT,
    MM_ANIM_LINK_BOTTLE_DRINK_DEMO_END,
    MM_ANIM_LINK_BOTTLE_READ,
    MM_ANIM_LINK_BOTTLE_READ_END,

    // ========================================
    // Magic Animations
    // ========================================
    MM_ANIM_LINK_MAGIC_TAME,
    MM_ANIM_LINK_MAGIC_HONOO1,
    MM_ANIM_LINK_MAGIC_HONOO2,
    MM_ANIM_LINK_MAGIC_HONOO3,
    MM_ANIM_LINK_MAGIC_KAZE1,
    MM_ANIM_LINK_MAGIC_KAZE2,
    MM_ANIM_LINK_MAGIC_KAZE3,
    MM_ANIM_LINK_MAGIC_TAMASHII1,
    MM_ANIM_LINK_MAGIC_TAMASHII2,
    MM_ANIM_LINK_MAGIC_TAMASHII3,

    // ========================================
    // Hammer Animations
    // ========================================
    MM_ANIM_LINK_HAMMER_NORMAL2LONG,
    MM_ANIM_LINK_HAMMER_LONG2LONG,
    MM_ANIM_LINK_HAMMER_LONG2FREE,

    // ========================================
    // Boom (Boomerang) Animations
    // ========================================
    MM_ANIM_LINK_BOOM_THROW_WAITL,
    MM_ANIM_LINK_BOOM_THROW_WAITR,

    // ========================================
    // Silver (Heavy) Lift Animations
    // ========================================
    MM_ANIM_LINK_SILVER_WAIT,
    MM_ANIM_LINK_SILVER_CARRY,
    MM_ANIM_LINK_SILVER_THROW,

    // ========================================
    // Swim Animations
    // ========================================
    MM_ANIM_LINK_SWIMER_SWIM,
    MM_ANIM_LINK_SWIMER_SWIM_WAIT,
    MM_ANIM_LINK_SWIMER_SWIM_GET,
    MM_ANIM_LINK_SWIMER_SWIM_HIT,
    MM_ANIM_LINK_SWIMER_SWIM_DOWN,
    MM_ANIM_LINK_SWIMER_SWIM_15STEP_UP,
    MM_ANIM_LINK_SWIMER_SWIM_DEEP_START,
    MM_ANIM_LINK_SWIMER_SWIM_DEEP_END,
    MM_ANIM_LINK_SWIMER_WAIT2SWIM_WAIT,
    MM_ANIM_LINK_SWIMER_LAND2SWIM_WAIT,
    MM_ANIM_LINK_SWIMER_BACK_SWIM,
    MM_ANIM_LINK_SWIMER_LSIDE_SWIM,
    MM_ANIM_LINK_SWIMER_RSIDE_SWIM,

    // ========================================
    // Demo/Cutscene Animations
    // ========================================
    MM_ANIM_LINK_DEMO_TBOX_OPEN,
    MM_ANIM_LINK_DEMO_GET_ITEMA,
    MM_ANIM_LINK_DEMO_GET_ITEMB,
    MM_ANIM_LINK_DEMO_DOORA_LINK,
    MM_ANIM_LINK_DEMO_DOORA_LINK_FREE,
    MM_ANIM_LINK_DEMO_DOORB_LINK,
    MM_ANIM_LINK_DEMO_DOORB_LINK_FREE,
    MM_ANIM_LINK_DEMO_WARP,
    MM_ANIM_LINK_DEMO_BACK_TO_PAST,
    MM_ANIM_LINK_DEMO_RETURN_TO_PAST,
    MM_ANIM_LINK_DEMO_BIKKURI,
    MM_ANIM_LINK_DEMO_FURIMUKI,
    MM_ANIM_LINK_DEMO_FURIMUKI2,
    MM_ANIM_LINK_DEMO_FURIMUKI2_WAIT,
    MM_ANIM_LINK_DEMO_JIBUNMIRU,
    MM_ANIM_LINK_DEMO_KAKEYORI,
    MM_ANIM_LINK_DEMO_KAKEYORI_WAIT,
    MM_ANIM_LINK_DEMO_KAKEYORI_MIMAWASI,
    MM_ANIM_LINK_DEMO_KAKEYORI_MIOKURI,
    MM_ANIM_LINK_DEMO_KAKEYORI_MIOKURI_WAIT,
    MM_ANIM_LINK_DEMO_KAOAGE,
    MM_ANIM_LINK_DEMO_KAOAGE_WAIT,
    MM_ANIM_LINK_DEMO_KENMIRU1,
    MM_ANIM_LINK_DEMO_KENMIRU1_WAIT,
    MM_ANIM_LINK_DEMO_KENMIRU2,
    MM_ANIM_LINK_DEMO_KENMIRU2_WAIT,
    MM_ANIM_LINK_DEMO_KENMIRU2_MODORI,
    MM_ANIM_LINK_DEMO_KOUSAN,
    MM_ANIM_LINK_DEMO_LOOK_HAND,
    MM_ANIM_LINK_DEMO_LOOK_HAND_WAIT,
    MM_ANIM_LINK_DEMO_NOZOKIKOMI,
    MM_ANIM_LINK_DEMO_NOZOKIKOMI_WAIT,
    MM_ANIM_LINK_DEMO_SITA_WAIT,
    MM_ANIM_LINK_DEMO_UE,
    MM_ANIM_LINK_DEMO_UE_WAIT,
    MM_ANIM_LINK_DEMO_ZELDAMIRU,
    MM_ANIM_LINK_DEMO_ZELDAMIRU_WAIT,
    MM_ANIM_LINK_DEMO_GURAD,
    MM_ANIM_LINK_DEMO_GURAD_WAIT,
    MM_ANIM_LINK_DEMO_GOMA_FURIMUKI,
    MM_ANIM_LINK_DEMO_BARU_OP1,
    MM_ANIM_LINK_DEMO_BARU_OP2,
    MM_ANIM_LINK_DEMO_BARU_OP3,

    // ========================================
    // Uma (Horse) Animations
    // ========================================
    MM_ANIM_LINK_UMA_ANIM_STOP,
    MM_ANIM_LINK_UMA_ANIM_STAND,
    MM_ANIM_LINK_UMA_ANIM_WALK,
    MM_ANIM_LINK_UMA_ANIM_WALK_MUTI,
    MM_ANIM_LINK_UMA_ANIM_SLOWRUN,
    MM_ANIM_LINK_UMA_ANIM_SLOWRUN_MUTI,
    MM_ANIM_LINK_UMA_ANIM_FASTRUN,
    MM_ANIM_LINK_UMA_ANIM_FASTRUN_MUTI,
    MM_ANIM_LINK_UMA_ANIM_JUMP100,
    MM_ANIM_LINK_UMA_ANIM_JUMP200,
    MM_ANIM_LINK_UMA_STOP_MUTI,
    MM_ANIM_LINK_UMA_LEFT_UP,
    MM_ANIM_LINK_UMA_LEFT_DOWN,
    MM_ANIM_LINK_UMA_RIGHT_UP,
    MM_ANIM_LINK_UMA_RIGHT_DOWN,
    MM_ANIM_LINK_UMA_WAIT_1,
    MM_ANIM_LINK_UMA_WAIT_2,
    MM_ANIM_LINK_UMA_WAIT_3,

    // ========================================
    // Tunnel (Crawl) Animations
    // ========================================
    MM_ANIM_LINK_CHILD_TUNNEL_START,
    MM_ANIM_LINK_CHILD_TUNNEL_END,

    // ========================================
    // Wait Type Animations
    // ========================================
    MM_ANIM_LINK_WAIT_TYPEA_20F,
    MM_ANIM_LINK_WAIT_TYPEB_20F,
    MM_ANIM_LINK_WAIT_TYPEC_20F,
    MM_ANIM_LINK_WAIT_TYPED_20F,
    MM_ANIM_LINK_WAIT_HEAT1_20F,
    MM_ANIM_LINK_WAIT_HEAT2_20F,
    MM_ANIM_LINK_WAIT_ITEMA_20F,
    MM_ANIM_LINK_WAIT_ITEMB_20F,
    MM_ANIM_LINK_WAIT_ITEMC_20F,
    MM_ANIM_LINK_WAIT_ITEMD1_20F,
    MM_ANIM_LINK_WAIT_ITEMD2_20F,
    MM_ANIM_LINK_WAITF_TYPEA_20F,
    MM_ANIM_LINK_WAITF_TYPEB_20F,
    MM_ANIM_LINK_WAITF_TYPEC_20F,
    MM_ANIM_LINK_WAITF_TYPED_20F,
    MM_ANIM_LINK_WAITF_HEAT1_20F,
    MM_ANIM_LINK_WAITF_HEAT2_20F,
    MM_ANIM_LINK_WAITF_ITEMA_20F,
    MM_ANIM_LINK_WAITF_ITEMB_20F,

    // ========================================
    // Misc Link Animations
    // ========================================
    MM_ANIM_LINK_SHAGAMU_DEMO,
    MM_ANIM_LINK_HATTO_DEMO,
    MM_ANIM_LINK_OKARINA_WARP_GOAL,
    MM_ANIM_LINK_OKIRU_DEMO,
    MM_ANIM_LINK_KEIREI,
    MM_ANIM_LINK_KEI_WAIT,
    MM_ANIM_LINK_DERTH_REBIRTH,
    MM_ANIM_LINK_LAST_HIT_MOTION1,
    MM_ANIM_LINK_LAST_HIT_MOTION2,

    // ========================================
    // Special Animations (al_, alink_, etc.)
    // ========================================
    MM_ANIM_AL_ELF_TOBIDASI,
    MM_ANIM_AL_FUWAFUWA,
    MM_ANIM_AL_FUWAFUWA_LOOP,
    MM_ANIM_AL_FUWAFUWA_MODORI,
    MM_ANIM_AL_GAKU,
    MM_ANIM_AL_HENSIN,
    MM_ANIM_AL_HENSIN_LOOP,
    MM_ANIM_AL_NO,
    MM_ANIM_AL_UNUN,
    MM_ANIM_AL_YAREYARE,
    MM_ANIM_AL_YES,
    MM_ANIM_ALINK_DANCE_LOOP,
    MM_ANIM_ALINK_EE,
    MM_ANIM_ALINK_EE_LOOP,
    MM_ANIM_ALINK_FUKITOBU,
    MM_ANIM_ALINK_KAITENMISS,
    MM_ANIM_ALINK_KYORO,
    MM_ANIM_ALINK_KYORO_LOOP,
    MM_ANIM_ALINK_OZIGI,
    MM_ANIM_ALINK_OZIGI_LOOP,
    MM_ANIM_ALINK_OZIGI_MODORI,
    MM_ANIM_ALINK_POWERUP,
    MM_ANIM_ALINK_POWERUP_LOOP,
    MM_ANIM_ALINK_RAKKATYU,
    MM_ANIM_ALINK_SOMUKERU,
    MM_ANIM_ALINK_SOMUKERU_LOOP,
    MM_ANIM_ALINK_TERERU,
    MM_ANIM_ALINK_YURAYURA,

    // ========================================
    // Child Link Demo Animations (clink_)
    // ========================================
    MM_ANIM_CLINK_DEMO_TBOX_OPEN,
    MM_ANIM_CLINK_DEMO_GET1,
    MM_ANIM_CLINK_DEMO_GET2,
    MM_ANIM_CLINK_DEMO_GET3,
    MM_ANIM_CLINK_DEMO_DOORA_LINK,
    MM_ANIM_CLINK_DEMO_DOORB_LINK,
    MM_ANIM_CLINK_DEMO_GOTO_FUTURE,
    MM_ANIM_CLINK_DEMO_RETURN_TO_FUTURE,
    MM_ANIM_CLINK_DEMO_ATOZUSARI,
    MM_ANIM_CLINK_DEMO_BASHI,
    MM_ANIM_CLINK_DEMO_FUTTOBI,
    MM_ANIM_CLINK_DEMO_KOUTAI,
    MM_ANIM_CLINK_DEMO_KOUTAI_WAIT,
    MM_ANIM_CLINK_DEMO_KOUTAI_KENNUKI,
    MM_ANIM_CLINK_DEMO_MIMAWASI,
    MM_ANIM_CLINK_DEMO_MIMAWASI_WAIT,
    MM_ANIM_CLINK_DEMO_MIOKURI,
    MM_ANIM_CLINK_DEMO_MIOKURI_WAIT,
    MM_ANIM_CLINK_DEMO_NOZOKI,
    MM_ANIM_CLINK_DEMO_STANDUP,
    MM_ANIM_CLINK_DEMO_STANDUP_WAIT,

    // Child Link Normal
    MM_ANIM_CLINK_NORMAL_CLIMB_ENDAL,
    MM_ANIM_CLINK_NORMAL_CLIMB_ENDAR,
    MM_ANIM_CLINK_NORMAL_CLIMB_ENDBL,
    MM_ANIM_CLINK_NORMAL_CLIMB_ENDBR,
    MM_ANIM_CLINK_NORMAL_CLIMB_STARTA,
    MM_ANIM_CLINK_NORMAL_CLIMB_STARTB,
    MM_ANIM_CLINK_NORMAL_CLIMB_UPL,
    MM_ANIM_CLINK_NORMAL_CLIMB_UPR,
    MM_ANIM_CLINK_NORMAL_DEFENSE_ALL,
    MM_ANIM_CLINK_NORMAL_OKARINA_WALK,
    MM_ANIM_CLINK_NORMAL_OKARINA_WALKB,

    // Child Link OP3
    MM_ANIM_CLINK_OP3_NEGAERI,
    MM_ANIM_CLINK_OP3_OKIAGARI,
    MM_ANIM_CLINK_OP3_TATIAGARI,
    MM_ANIM_CLINK_OP3_WAIT1,
    MM_ANIM_CLINK_OP3_WAIT2,
    MM_ANIM_CLINK_OP3_WAIT3,

    // ========================================
    // CL (Alternative Child Link) Animations
    // ========================================
    MM_ANIM_CL_DAKISIME,
    MM_ANIM_CL_DAKISIME_LOOP,
    MM_ANIM_CL_FURAFURA,
    MM_ANIM_CL_HOO,
    MM_ANIM_CL_JIBUN_MIRU,
    MM_ANIM_CL_KUBISIME,
    MM_ANIM_CL_MASKOFF,
    MM_ANIM_CL_MSBOWAIT,
    MM_ANIM_CL_NIGERU,
    MM_ANIM_CL_ONONOKI,
    MM_ANIM_CL_SETMASK,
    MM_ANIM_CL_SETMASKEND,
    MM_ANIM_CL_TEWOFURU,
    MM_ANIM_CL_TOBIKAKARU,
    MM_ANIM_CL_UMA_LEFTUP,
    MM_ANIM_CL_UMA_RIGHTUP,
    MM_ANIM_CL_UMAMIAGE,
    MM_ANIM_CL_UMAMIAGE_LOOP,
    MM_ANIM_CL_UMANORU,
    MM_ANIM_CL_UMANORU_LOOP,
    MM_ANIM_CL_WAKARE,
    MM_ANIM_CL_WAKARE_LOOP,

    // ========================================
    // Goron Animations (pg_)
    // ========================================
    MM_ANIM_PG_WAIT,
    MM_ANIM_PG_PUNCHA,
    MM_ANIM_PG_PUNCHB,
    MM_ANIM_PG_PUNCHC,
    MM_ANIM_PG_PUNCHAEND,
    MM_ANIM_PG_PUNCHBEND,
    MM_ANIM_PG_PUNCHCEND,
    MM_ANIM_PG_PUNCHAENDR,
    MM_ANIM_PG_PUNCHBENDR,
    MM_ANIM_PG_PUNCHCENDR,
    MM_ANIM_PG_MARU_CHANGE,
    MM_ANIM_PG_CLIMB_STARTA,
    MM_ANIM_PG_CLIMB_STARTB,
    MM_ANIM_PG_CLIMB_ENDAL,
    MM_ANIM_PG_CLIMB_ENDAR,
    MM_ANIM_PG_CLIMB_ENDBL,
    MM_ANIM_PG_CLIMB_ENDBR,
    MM_ANIM_PG_CLIMB_UPL,
    MM_ANIM_PG_CLIMB_UPR,
    MM_ANIM_PG_DOORA_OPEN,
    MM_ANIM_PG_DOORB_OPEN,
    MM_ANIM_PG_TBOX_OPEN,
    MM_ANIM_PG_MASKOFFSTART,
    MM_ANIM_PG_GAKKISTART,
    MM_ANIM_PG_GAKKIWAIT,
    MM_ANIM_PG_GAKKIPLAY,
    MM_ANIM_PG_GAKKIPLAYA,
    MM_ANIM_PG_GAKKIPLAYD,
    MM_ANIM_PG_GAKKIPLAYL,
    MM_ANIM_PG_GAKKIPLAYR,
    MM_ANIM_PG_GAKKIPLAYU,

    // ========================================
    // Zora Animations (pz_)
    // ========================================
    MM_ANIM_PZ_WAIT,
    MM_ANIM_PZ_ATTACKA,
    MM_ANIM_PZ_ATTACKB,
    MM_ANIM_PZ_ATTACKC,
    MM_ANIM_PZ_ATTACKAEND,
    MM_ANIM_PZ_ATTACKBEND,
    MM_ANIM_PZ_ATTACKCEND,
    MM_ANIM_PZ_ATTACKAENDR,
    MM_ANIM_PZ_ATTACKBENDR,
    MM_ANIM_PZ_ATTACKCENDR,
    MM_ANIM_PZ_BLADEON,
    MM_ANIM_PZ_CUTTERATTACK,
    MM_ANIM_PZ_CUTTERCATCH,
    MM_ANIM_PZ_CUTTERWAITA,
    MM_ANIM_PZ_CUTTERWAITB,
    MM_ANIM_PZ_CUTTERWAITC,
    MM_ANIM_PZ_CUTTERWAITANIM,
    MM_ANIM_PZ_JUMPAT,
    MM_ANIM_PZ_JUMPATEND,
    MM_ANIM_PZ_FISHSWIM,
    MM_ANIM_PZ_WATERROLL,
    MM_ANIM_PZ_SWIMTOWAIT,
    MM_ANIM_PZ_CLIMB_STARTA,
    MM_ANIM_PZ_CLIMB_STARTB,
    MM_ANIM_PZ_CLIMB_ENDAL,
    MM_ANIM_PZ_CLIMB_ENDAR,
    MM_ANIM_PZ_CLIMB_ENDBL,
    MM_ANIM_PZ_CLIMB_ENDBR,
    MM_ANIM_PZ_CLIMB_UPL,
    MM_ANIM_PZ_CLIMB_UPR,
    MM_ANIM_PZ_DOORA_OPEN,
    MM_ANIM_PZ_DOORB_OPEN,
    MM_ANIM_PZ_TBOX_OPEN,
    MM_ANIM_PZ_MASKOFFSTART,
    MM_ANIM_PZ_GAKKISTART,
    MM_ANIM_PZ_GAKKIPLAY,

    // ========================================
    // Deku Animations (pn_)
    // ========================================
    MM_ANIM_PN_ATTACK,
    MM_ANIM_PN_GURD,
    MM_ANIM_PN_GETA,
    MM_ANIM_PN_GETB,
    MM_ANIM_PN_TAMAHAKI,
    MM_ANIM_PN_TAMAHAKIDF,
    MM_ANIM_PN_BATABATA,
    MM_ANIM_PN_KAKKU,
    MM_ANIM_PN_KAKKUFINISH,
    MM_ANIM_PN_RAKKAFINISH,
    MM_ANIM_PN_DRINK,
    MM_ANIM_PN_DRINKSTART,
    MM_ANIM_PN_DRINKEND,
    MM_ANIM_PN_DOORA_OPEN,
    MM_ANIM_PN_DOORB_OPEN,
    MM_ANIM_PN_TBOX_OPEN,
    MM_ANIM_PN_MASKOFFSTART,
    MM_ANIM_PN_GAKKISTART,
    MM_ANIM_PN_GAKKIPLAY,

    // ========================================
    // Misc Demo Animations
    // ========================================
    MM_ANIM_DEMO_LINK_NWAIT,
    MM_ANIM_DEMO_LINK_TWAIT,
    MM_ANIM_DEMO_LINK_OROSUU,
    MM_ANIM_DEMO_LINK_TEWATASHI,
    MM_ANIM_DEMO_PIKUPIKU,
    MM_ANIM_DEMO_RAKKA,
    MM_ANIM_DEMO_SUWARI1,
    MM_ANIM_DEMO_SUWARI2,
    MM_ANIM_DEMO_SUWARI3,

    // ========================================
    // Other Animations
    // ========================================
    MM_ANIM_BAJYO_FURIKAERU,
    MM_ANIM_BAJYO_WALK,
    MM_ANIM_D_LINK_IMANODARE,
    MM_ANIM_D_LINK_OROORO,
    MM_ANIM_D_LINK_OROWAIT,
    MM_ANIM_DL_JIBUNMIRU,
    MM_ANIM_DL_JIBUNMIRU_WAIT,
    MM_ANIM_DL_KOKERU,
    MM_ANIM_DL_YUSABURU,
    MM_ANIM_KF_AWASE,
    MM_ANIM_KF_DAKIAU,
    MM_ANIM_KF_DAKIAU_LOOP,
    MM_ANIM_KF_HANARE,
    MM_ANIM_KF_HANARE_LOOP,
    MM_ANIM_KF_MISEAU,
    MM_ANIM_KF_OMEN,
    MM_ANIM_KF_OMEN_LOOP,
    MM_ANIM_KF_TETUNAGU_LOOP,
    MM_ANIM_KOLINK_ODOROKI_DEMO,
    MM_ANIM_L_BOUZEN,
    MM_ANIM_L_HAJIKARERU,
    MM_ANIM_L_KAMAERU,
    MM_ANIM_L_KEN_MIRU,
    MM_ANIM_L_KENNASI_W,
    MM_ANIM_L_KW,
    MM_ANIM_L_MUKINAORU,
    MM_ANIM_L_OKARINA_GET,
    MM_ANIM_L_SAGARU,
    MM_ANIM_L_1KYORO,
    MM_ANIM_L_2KYORO,
    MM_ANIM_LINK_HA,
    MM_ANIM_LINK_M_WAIT,
    MM_ANIM_LINK_MIAGERU,
    MM_ANIM_LINK_MUKU,
    MM_ANIM_LINK_OTITUKU_W,
    MM_ANIM_LINK_UE_WAIT,
    MM_ANIM_LKT_NWAIT,
    MM_ANIM_LOST_HORSE,
    MM_ANIM_LOST_HORSE_WAIT,
    MM_ANIM_LOST_HORSE2,
    MM_ANIM_NW_MODORU,
    MM_ANIM_O_GET_ATO,
    MM_ANIM_O_GET_MAE,
    MM_ANIM_OKIAGARU,
    MM_ANIM_OKIAGARU_TATU,
    MM_ANIM_OKIAGARU_WAIT,
    MM_ANIM_OKARINATORI,
    MM_ANIM_OM_GET,
    MM_ANIM_OM_GET_MAE,
    MM_ANIM_RAKKA,
    MM_ANIM_RAKUBA,
    MM_ANIM_SIRIMOCHI,
    MM_ANIM_SIRIMOCHI_WAIT,
    MM_ANIM_SPOTLIGHT,
    MM_ANIM_SPOTLIGHT_WAIT,
    MM_ANIM_SUDE_NWAIT,
    MM_ANIM_URUSAI,
    MM_ANIM_VS_YOUSEI,

    // ========================================
    // Total count
    // ========================================
    MM_ANIM_MAX
} MmAnimId;

// ============================================================================
// Animation Definition Table
// Defined in mm_anims_data.c
// ============================================================================

extern const MmAnimDef gMmAnims[MM_ANIM_MAX];

#ifdef __cplusplus
}
#endif

#endif // MM_ANIMS_H
