/**
 * stasis_rune.c — Sheikah Slate rune: Stasis (Skijer's NEI)
 *
 * Freezes ONE actor in time (BotW holds a single target too). What the freeze means depends on what
 * was frozen:
 *
 *   ENEMY     — its AI stops. Hits Link lands are stored, not reacted to, and applied when the
 *               stasis ends. Enemies are never launched (user-locked).
 *   PROP      — a rock/boulder/breakable stops dead and can be launched.
 *   BLOCK     — a pushable block, crate or platform: launchable, never climbable.
 *   CLIMBABLE — any other dynapoly body big enough to climb: launchable AND its surface becomes a
 *               vine wall while frozen, so Link can grab on.
 *
 * Hitting a frozen object builds launch force from the damage each blow WOULD have dealt, and each
 * blow's direction steers where it flies. A curved arrow traces the resulting arc.
 *
 * NO HEADER ON PURPOSE: both repos glob mods/*.h with CONFIGURE_DEPENDS, so a new header there
 * forces a full CMake regeneration on the next build. The API is declared here and repeated as
 * local externs at the few call sites (all of which are in this same unity translation unit or the
 * files right next to it).
 *
 * The takeover is the Cane of Pacci idiom (mods/actors/cane_pacci.c): swap the actor's `update` for
 * a no-op — never NULL it, that is the engine's "dead" marker — snapshot every field we write, and
 * disable culling or the engine stops running OUR replacement update the moment the player looks
 * away.
 *
 * Kept 1:1 with soh/mods/actors/stasis_rune.c — regenerated by
 * scratchpad/port_stasis_to_mm.py. The divergences are the ones the tree already documents
 * everywhere: MM's actor-id table is its own, `speed` replaces `speedXZ`, the scene is `sceneId`,
 * the camera list is `bgCamList`, and the hookshot chain has to be loaded by OTR path.
 */

#include "z64.h"
#include "macros.h"
#include "functions.h"
#include "variables.h"
#include <math.h>
#include <string.h>
#include "../items/helpers/target_select_helper.h"
#include "../items/helpers/combat_helper.h"

// TargetSelect's filter takes no PlayState, and the teardown paths can run outside a frame, so both
// lean on the global. Every mod in the tree reaches it the same way.
extern PlayState* gPlayState;

// Defined further down, next to the rest of the offer handling, but called from Stasis_Begin above
// it — without this the compiler assumes an int-returning function and the real definition clashes.
static void Stasis_ClearOffer(void);
static f32 Stasis_ChargeFraction(void);

// ── Public API ───────────────────────────────────────────────────────────────
s32 Stasis_Cast(PlayState* play, Player* player);
void Stasis_Update(PlayState* play, Player* player);
void Stasis_Draw(PlayState* play);
void Stasis_Forget(void);
void Stasis_UpdateOffer(PlayState* play, u8 allowed);
u8 Stasis_IsClimbableBgId(s32 bgId);
// Defined in stasis_sfx.inc.c (pulled in at the tail of this file). MixInto is called from the
// audio thread; the other two from gameplay.
void StasisSfx_Play(f32 rate, f32 volume);
void StasisSfx_Stop(void);
void StasisSfx_MixInto(s16* outBuf, u32 numSamples);

// ── Tuning ───────────────────────────────────────────────────────────────────
// Actor updates run at 20 ticks/second in both engines (cane_pacci.h documents 100 as "roughly
// five seconds"), so 200 is the requested 10 seconds. Enemies hold just as long; what changes for
// them is the cue, which plays at double rate.
#define STASIS_FRAMES_OBJECT 200
#define STASIS_FRAMES_ENEMY 200
#define STASIS_CHAIN_FRAMES 20 // the chain burst: one second, at the start only
#define STASIS_FLIGHT_FRAMES 90
#define STASIS_RANGE TARGETSEL_DEFAULT_RANGE

#define STASIS_LAUNCH_BASE 8.0f       // speed with no hits stored at all
#define STASIS_LAUNCH_PER_DAMAGE 1.8f // added speed per point of stored damage
#define STASIS_LAUNCH_PER_HIT 3.0f    // ...and what a damage-less blow (sword on a rock) is worth
#define STASIS_LAUNCH_MAX 42.0f
#define STASIS_LAUNCH_VEL_Y 6.0f
#define STASIS_GRAVITY -1.4f
#define STASIS_RECOIL_SPEED 7.0f  // how hard the attacker bounces off a frozen body
#define STASIS_RECOIL_HEIGHT 3.5f

// A body has to be about Link's height before climbing it makes any sense. This is what "actor bg
// GRANDE" means in code — a rule rather than a list, so new scenes need no table edit.
#define STASIS_CLIMB_MIN_HALF_HEIGHT 24.0f

// Vine/climbable wall. It is wallType 4 (WALL_FLAG_3), the value the player's climb check gates on.
#define STASIS_WALL_TYPE_CLIMBABLE 4

// The tint is a RAMP, not one colour: BotW fades a stasis body from yellow toward red as it takes
// on energy, so the colour alone tells you how hard it is about to go. Uncharged first, fully
// charged second.
// The grayscale pass multiplies these by each texel's own brightness, so they are pushed near
// white-hot — a dark model would otherwise come out muddy.
#define STASIS_TINT_R 255
#define STASIS_TINT_G 235
#define STASIS_TINT_B 90
#define STASIS_TINT_HOT_R 255
#define STASIS_TINT_HOT_G 70
#define STASIS_TINT_HOT_B 40

typedef enum {
    STASIS_KIND_NONE = 0,
    STASIS_KIND_ENEMY,
    STASIS_KIND_PROP,
    STASIS_KIND_BLOCK,
    STASIS_KIND_CLIMBABLE,
} StasisKind;

typedef enum {
    STASIS_PHASE_FROZEN = 0,
    STASIS_PHASE_FLYING,
} StasisPhase;

typedef struct {
    Actor* actor;
    u8 kind;
    u8 phase;
    s16 timer;      // stasis frames left, or flight frames once launched
    s16 chainTimer; // chain-burst frames left
    s16 age;        // frames since the freeze started (drives the pulse)
    u16 accumDamage;
    f32 force;   // accumulated launch speed — every blow adds, nothing ever subtracts
    Vec3f hitDir; // unit vector of the LAST blow, in full 3D. Direction is not accumulated:
                  // in BotW the newest hit re-aims the object and only the magnitude stacks.
    u8 hasHitDir;
    s32 bgId;      // dynapoly id while frozen, or -1
    u8 bgIsOurs;   // 1 = WE registered that bgId and must delete it on thaw
    // Saved actor state, restored verbatim (the Pacci_Restore field set).
    ActorFunc origUpdate;
    ActorFunc origDraw;
    u32 origFlags;
    f32 origGravity;
    f32 origMinVelocityY;
    f32 origSpeed;
    Vec3s origShapeRot;
    Vec3s origWorldRot;
    s16 origRoom;
    u8 origMass;
    // Our own collider, OWNED BY THE TARGET so hits land in the target's colChkInfo.
    ColliderCylinder collider;
    u8 colliderReady;
} StasisState;

static StasisState sStasis = { 0 };

// The override light for a body in stasis: ambient almost white, one strong diffuse. Ordinary scene
// ambient sits far lower, which is exactly why an untouched model has no brightness to tint.
static Lights1 sStasisLights = gdSPDefLights1(210, 205, 175, 255, 250, 220, 0x28, 0x28, 0x28);

// What the rune WOULD freeze right now. Painted with the same gold so you can see the pick before
// committing to it — the "on offer" highlight. Its draw pointer is swapped exactly like the frozen
// body's, and restored at the top of every tick before the next scan, so a target that stops being
// offered never keeps our wrapper.
static Actor* sStasisOffer = NULL;
static ActorFunc sStasisOfferDraw = NULL;

// AC keeps a frozen body hittable (that is the whole point — you beat on it to charge the launch);
// AT goes live only while it is flying, so a thrown block smashes what it reaches.
static ColliderCylinderInit sStasisColliderInit = {
    {
        COL_MATERIAL_NONE,
        AT_ON | AT_TYPE_PLAYER,
        AC_ON | AC_TYPE_PLAYER,
        OC1_NONE,
        OC2_NONE,
        COLSHAPE_CYLINDER,
    },
    {
        ELEM_MATERIAL_UNK0,
        { 0xFFCFFFFF, 0x00, 0x08 },
        { 0xFFCFFFFF, 0x00, 0x00 },
        ATELEM_ON | ATELEM_SFX_NORMAL,
        ACELEM_ON,
        OCELEM_NONE,
    },
    { 40, 60, 0, { 0, 0, 0 } },
};

// ============================================================================
// WHITELIST
// ============================================================================

// Pushable blocks, block-like crates, platforms and elevators. Launchable, never climbable — a
// pushblock you can climb would break every block puzzle in the game.
static const s16 sStasisBlockIds[] = {
    ACTOR_OBJ_OSHIHIKI,   ACTOR_OBJ_KIBAKO2,      ACTOR_OBJ_SKATEBLOCK, ACTOR_OBJ_PZLBLOCK,
    ACTOR_OBJ_LIGHTBLOCK, ACTOR_OBJ_VISIBLOCK,    ACTOR_OBJ_ICEBLOCK,   ACTOR_OBJ_HSBLOCK,
    ACTOR_BG_F40_BLOCK,   ACTOR_OBJ_LIFT,         ACTOR_OBJ_RAILLIFT,   ACTOR_OBJ_DRIFTICE,
    ACTOR_OBJ_DANPEILIFT, ACTOR_OBJ_LUPYGAMELIFT, ACTOR_OBJ_Y2LIFT,     ACTOR_OBJ_OCARINALIFT,
    ACTOR_OBJ_ROTLIFT,    ACTOR_BG_DBLUE_ELEVATOR, ACTOR_BG_FU_KAITEN,  ACTOR_BG_ICEFLOE,
    ACTOR_BG_F40_FLIFT,   ACTOR_BG_F40_SWLIFT,
};

// Rocks, boulders and large breakables. These carry plain cylinder/sphere colliders, no dynapoly.
static const s16 sStasisPropIds[] = {
    ACTOR_OBJ_BOMBIWA,  ACTOR_OBJ_HAMISHI,   ACTOR_EN_GOROIWA, ACTOR_OBJ_HUGEBOMBIWA,
    ACTOR_OBJ_SNOWBALL, ACTOR_OBJ_SNOWBALL2, ACTOR_BG_ICICLE,  ACTOR_OBJ_BIGICICLE,
    ACTOR_OBJ_HAKAISI,  ACTOR_OBJ_GHAKA,     ACTOR_OBJ_ARMOS,  ACTOR_OBJ_HSSTUMP,
    ACTOR_EN_MM,
};

// Enemies that shrug Stasis off. Same spirit as sPacciBlacklist: scripted heavyweights whose AI
// does not survive being paused.
static const s16 sStasisEnemyBlacklist[] = {
    ACTOR_EN_WIZ, ACTOR_EN_DINOFOS, ACTOR_EN_BIGPO, ACTOR_EN_BIGSLIME, ACTOR_EN_WALLMAS,
    ACTOR_EN_FLOORMAS, ACTOR_EN_RD, ACTOR_EN_FZ,
};

static u8 Stasis_IdInList(s16 id, const s16* list, s32 count) {
    for (s32 i = 0; i < count; i++) {
        if (list[i] == id) {
            return 1;
        }
    }
    return 0;
}

// The dynapoly scan: the index into bgActors IS the bgId (mirrors Pacci_FuseFindBg).
static CollisionHeader* Stasis_FindBg(PlayState* play, Actor* actor, s32* bgIdOut) {
    if ((play == NULL) || (actor == NULL)) {
        return NULL;
    }
    for (s32 i = 0; i < BG_ACTOR_MAX; i++) {
        BgActor* bg = &play->colCtx.dyna.bgActors[i];

        if ((bg->actor == actor) && (bg->colHeader != NULL)) {
            if (bgIdOut != NULL) {
                *bgIdOut = i;
            }
            return bg->colHeader;
        }
    }
    return NULL;
}

// ── Synthesised collision ────────────────────────────────────────────────────────────────────────
// A boulder like Obj_Hamishi carries only a cylinder collider: you cannot stand on it, you cannot
// climb it, and Link walks straight through its middle. Freezing one is supposed to make it a solid
// piece of the world, so while it is held we build a real dynapoly box from its own collider
// dimensions and register it. Deleted again on thaw, so nothing leaks into the scene.
//
// The pools are file-static and single-slot on purpose: exactly one body is ever frozen.
#define STASIS_BOX_VTX 8
#define STASIS_BOX_POLY 12

// The camera reads the header's bgCamList entry WITHOUT a NULL check, and every poly's surface
// type carries a camera index. Leaving this NULL is an instant crash the moment the camera looks
// at the frozen body. One neutral entry, and every poly points at index 0.
static BgCamInfo sStasisCamData[1];

static Vec3s sStasisVtxPool[STASIS_BOX_VTX];
static CollisionPoly sStasisPolyPool[STASIS_BOX_POLY];
static SurfaceType sStasisSurfPool[1];
static CollisionHeader sStasisHeader;

// Outward winding: the engine reads normal.y to tell floor from wall from ceiling, so an inverted
// box is a ceiling you fall through.
static const u8 sStasisBoxTris[STASIS_BOX_POLY][3] = {
    { 0, 1, 2 }, { 0, 2, 3 }, // bottom, -Y
    { 4, 6, 5 }, { 4, 7, 6 }, // top, +Y
    { 0, 5, 1 }, { 0, 4, 5 }, // -Z
    { 1, 6, 2 }, { 1, 5, 6 }, // +X
    { 2, 7, 3 }, { 2, 6, 7 }, // +Z
    { 3, 4, 0 }, { 3, 7, 4 }, // -X
};

static void Stasis_MakePoly(CollisionPoly* poly, u16 ia, u16 ib, u16 ic) {
    Vec3f a;
    Vec3f b;
    Vec3f c;
    Vec3f e1;
    Vec3f e2;
    Vec3f n;
    f32 len;

    poly->type = 0;
    poly->flags_vIA = ia & 0x1FFF;
    poly->flags_vIB = ib & 0x1FFF;
    poly->vIC = ic & 0x1FFF;

    a.x = (f32)sStasisVtxPool[ia].x;
    a.y = (f32)sStasisVtxPool[ia].y;
    a.z = (f32)sStasisVtxPool[ia].z;
    b.x = (f32)sStasisVtxPool[ib].x;
    b.y = (f32)sStasisVtxPool[ib].y;
    b.z = (f32)sStasisVtxPool[ib].z;
    c.x = (f32)sStasisVtxPool[ic].x;
    c.y = (f32)sStasisVtxPool[ic].y;
    c.z = (f32)sStasisVtxPool[ic].z;

    e1.x = b.x - a.x;
    e1.y = b.y - a.y;
    e1.z = b.z - a.z;
    e2.x = c.x - a.x;
    e2.y = c.y - a.y;
    e2.z = c.z - a.z;
    n.x = (e1.y * e2.z) - (e1.z * e2.y);
    n.y = (e1.z * e2.x) - (e1.x * e2.z);
    n.z = (e1.x * e2.y) - (e1.y * e2.x);
    len = sqrtf((n.x * n.x) + (n.y * n.y) + (n.z * n.z));
    if (len > 0.001f) {
        n.x /= len;
        n.y /= len;
        n.z /= len;
        poly->normal.x = (s16)(n.x * 32767.0f);
        poly->normal.y = (s16)(n.y * 32767.0f);
        poly->normal.z = (s16)(n.z * 32767.0f);
        poly->dist = (s16)-((n.x * a.x) + (n.y * a.y) + (n.z * a.z));
    }
}

// The body the collision is registered ON. It is NOT the frozen actor.
//
// This is the whole reason Stasis used to corrupt trees and rocks: the engine treats every actor in
// `bgActors[]` as a DynaPolyActor and writes through that cast — `DynaPolyActor_UnsetAllInteractFlags`
// stores `interactFlags` at offset 0x160, and `bgId` at 0x14C. En_Wood02 keeps its ColliderCylinder
// at 0x158, so registering a tree wrote straight into its collider and left `collider.base.actor`
// dangling. The next frame the tree's own update submitted that collider and
// CollisionCheck_SetAC dereferenced the garbage pointer.
//
// So we register a carrier we own every byte of, parked on top of the frozen body. The engine can
// scribble on it freely, the real actor is never touched, and it gets its AI back untouched when
// the stasis ends.
static DynaPolyActor sStasisCarrier;

// Never runs (the carrier is in no actor list), but a non-NULL update is the engine's "alive"
// marker and several collision paths test it.
static void Stasis_CarrierUpdate(Actor* thisx, PlayState* play) {
}

// Park the carrier on the frozen body.
static void Stasis_CarrierSync(Actor* target) {
    sStasisCarrier.actor.world.pos = target->world.pos;
    sStasisCarrier.actor.home.pos = target->world.pos;
    sStasisCarrier.actor.prevPos = target->world.pos;
    sStasisCarrier.actor.shape.rot = target->shape.rot;
    sStasisCarrier.actor.world.rot = target->shape.rot;
    // Scale deliberately NOT copied: the box is authored in world units, so the carrier stays at 1
    // and the engine's per-frame transform does not apply the target's scale a second time.
}

// How big the body LOOKS.
//
// Two wrong sources were tried before this one, and both are worth naming:
//   - `colChkInfo.cylRadius/cylHeight` is not a size at all for most props. En_Wood02 leaves it at
//     zero, so a tree got no box built; Obj_Hamishi puts 12 there while its real collider is 50.
//   - the actor's own ColliderCylinder is the true COLLISION shape, but it is deliberately much
//     smaller than the model — a tree's is radius 18 around the trunk while the visible tree is
//     several times that. Wrapping the collider gives a box you slide off, not one you climb.
//
// So these are the VISUAL extents, matched to what is drawn. The collider list cannot be consulted
// either way: the engine clears it at the end of the collision phase (z_play.c), so it is always
// empty by the time any mod code runs. Tune the numbers here — one row per body.
#define STASIS_FALLBACK_RADIUS 45
#define STASIS_FALLBACK_HEIGHT 90

typedef struct {
    s16 id;
    s16 radius; // visual half-width
    s16 height; // visual height from the actor's feet
    s16 yShift;
} StasisBodySize;

static const StasisBodySize sStasisBodySizes[] = {
    // A tree is narrow but very tall: the box has to reach the canopy or there is nothing up there
    // to hang from. Collider says 18x60; the model is nothing like that.
    { ACTOR_EN_WOOD02, 40, 220, 0 },
    // The boulders are close to spherical, and read slightly wider than their colliders.
    { ACTOR_OBJ_HAMISHI, 62, 88, 0 },
    { ACTOR_OBJ_BOMBIWA, 66, 86, 0 },
    { ACTOR_EN_ISHI, 62, 80, 0 }, // the type-1 boulder; type 0 is never frozen
};

static void Stasis_MeasureTarget(PlayState* play, Actor* actor, f32* radius, f32* height, f32* yShift) {
    s32 i;

    (void)play;

    for (i = 0; i < (s32)ARRAY_COUNT(sStasisBodySizes); i++) {
        if (sStasisBodySizes[i].id == actor->id) {
            *radius = (f32)sStasisBodySizes[i].radius;
            *height = (f32)sStasisBodySizes[i].height;
            *yShift = (f32)sStasisBodySizes[i].yShift;
            return;
        }
    }

    *radius = (actor->colChkInfo.cylRadius > 0) ? (f32)actor->colChkInfo.cylRadius : STASIS_FALLBACK_RADIUS;
    *height = (actor->colChkInfo.cylHeight > 0) ? (f32)actor->colChkInfo.cylHeight : STASIS_FALLBACK_HEIGHT;
    *yShift = 0.0f;

    if (*height <= 0.0f) {
        *height = *radius * 2.0f;
    }
}

// Builds and registers the box. Returns the new bgId, or -1 if the actor has nothing to build from.
static s32 Stasis_BuildCollision(PlayState* play, Actor* actor) {
    static const s8 sRingX[4] = { -1, 1, 1, -1 };
    static const s8 sRingZ[4] = { -1, -1, 1, 1 };
    f32 r;
    f32 h;
    f32 y0;
    f32 y1;
    // The carrier is registered at scale 1, so the collider dimensions go in as-is — no inverse
    // scaling, and no dependence on whatever odd scale the frozen actor happens to carry.
    s32 i;

    Stasis_MeasureTarget(play, actor, &r, &h, &y0);
    if (r <= 0.0f) {
        return -1;
    }
    y1 = y0 + h;

    // Ring order round the base then the same ring on top; a raw bit sweep crosses the side faces.
    for (i = 0; i < 8; i++) {
        f32 x = (f32)sRingX[i & 3] * r;
        f32 z = (f32)sRingZ[i & 3] * r;
        f32 y = (i < 4) ? y0 : y1;

        sStasisVtxPool[i].x = (s16)x;
        sStasisVtxPool[i].y = (s16)y;
        sStasisVtxPool[i].z = (s16)z;
    }
    for (i = 0; i < STASIS_BOX_POLY; i++) {
        Stasis_MakePoly(&sStasisPolyPool[i], sStasisBoxTris[i][0], sStasisBoxTris[i][1], sStasisBoxTris[i][2]);
    }

    // One surface type, and we own it — so the climbable wall type is baked straight in rather than
    // patched into a shared, cached scene resource.
    // Bits 0..7 of data[0] are the camera index — it must stay 0, which is the one entry above.
    sStasisSurfPool[0].data[0] = (u32)(STASIS_WALL_TYPE_CLIMBABLE << 21);
    sStasisSurfPool[0].data[1] = 0;

    sStasisHeader.minBounds.x = (s16)-r;
    sStasisHeader.minBounds.y = (s16)y0;
    sStasisHeader.minBounds.z = (s16)-r;
    sStasisHeader.maxBounds.x = (s16)r;
    sStasisHeader.maxBounds.y = (s16)y1;
    sStasisHeader.maxBounds.z = (s16)r;
    sStasisHeader.numVertices = STASIS_BOX_VTX;
    sStasisHeader.vtxList = sStasisVtxPool;
    sStasisHeader.numPolygons = STASIS_BOX_POLY;
    sStasisHeader.polyList = sStasisPolyPool;
    sStasisHeader.surfaceTypeList = sStasisSurfPool;
    sStasisCamData[0].setting = 0;
    sStasisCamData[0].count = 0;
    sStasisCamData[0].bgCamFuncData = NULL;
    sStasisHeader.bgCamList = sStasisCamData;
    sStasisHeader.numWaterBoxes = 0;
    sStasisHeader.waterBoxes = NULL;

    // Zeroed first: the engine writes bgId/interactFlags through the DynaPolyActor cast, and stale
    // values from a previous freeze would be read back as live state.
    memset(&sStasisCarrier, 0, sizeof(sStasisCarrier));
    sStasisCarrier.actor.update = Stasis_CarrierUpdate;
    sStasisCarrier.actor.scale.x = sStasisCarrier.actor.scale.y = sStasisCarrier.actor.scale.z = 1.0f;
    Stasis_CarrierSync(actor);

    return DynaPoly_SetBgActor(play, &play->colCtx.dyna, &sStasisCarrier.actor, &sStasisHeader);
}

static u8 Stasis_IsFreezableEnemy(Actor* actor) {
    if (actor->category != ACTORCAT_ENEMY) {
        return 0;
    }
    // MASS_IMMOVABLE inside ACTORCAT_ENEMY is how scripted minibosses mark themselves; it means
    // something different on props, which is why this test is category-scoped.
    if (actor->colChkInfo.mass == MASS_IMMOVABLE) {
        return 0;
    }
    return !Stasis_IdInList(actor->id, sStasisEnemyBlacklist, ARRAY_COUNT(sStasisEnemyBlacklist));
}

static u8 Stasis_IsFreezableProp(Actor* actor) {
    // En_Ishi type 0 is the small rock Link simply picks up — only the type-1 boulder is worth
    // freezing (the type is bit 0 of params in both games).
    if (actor->id == ACTOR_EN_ISHI) {
        return (actor->params & 1) == 1;
    }
    // Wood02's bush/leaf types carry no collider at all, so there is nothing to freeze or throw.
    // MM builds one for types below WOOD_BUSH_GREEN_SMALL (0x0B) plus WOOD_TREE_SPECIAL (0x1A);
    // the enum lives in the actor's own overlay header, which mods cannot include.
    if (actor->id == ACTOR_EN_WOOD02) {
        u16 woodType = actor->params & 0xFF;

        return (woodType < 0x0B) || (woodType == 0x1A);
    }
    return Stasis_IdInList(actor->id, sStasisPropIds, ARRAY_COUNT(sStasisPropIds));
}

// Returns the STASIS_KIND_* this actor would freeze as, or STASIS_KIND_NONE.
static u8 Stasis_Classify(PlayState* play, Actor* actor, s32* bgIdOut) {
    CollisionHeader* hdr;
    s32 bgId = -1;

    if (bgIdOut != NULL) {
        *bgIdOut = -1;
    }
    if ((actor == NULL) || (actor->update == NULL) || (actor->id == ACTOR_PLAYER)) {
        return STASIS_KIND_NONE;
    }
    if (actor->category == ACTORCAT_BOSS) {
        return STASIS_KIND_NONE;
    }
    // Invisible triggers, spawn points and cutscene markers: freezing one moves something the
    // player cannot see, which always reads as a bug.
    if (actor->draw == NULL) {
        return STASIS_KIND_NONE;
    }

    if (Stasis_IsFreezableEnemy(actor)) {
        return STASIS_KIND_ENEMY;
    }

    // BLOCK is tested before the generic dynapoly rule below, or every pushblock would come out
    // climbable.
    if (Stasis_IdInList(actor->id, sStasisBlockIds, ARRAY_COUNT(sStasisBlockIds))) {
        Stasis_FindBg(play, actor, bgIdOut);
        return STASIS_KIND_BLOCK;
    }

    if (Stasis_IsFreezableProp(actor)) {
        return STASIS_KIND_PROP;
    }

    hdr = Stasis_FindBg(play, actor, &bgId);
    if (hdr != NULL) {
        f32 halfHeight = ((f32)hdr->maxBounds.y - (f32)hdr->minBounds.y) * 0.5f * actor->scale.y;

        if (bgIdOut != NULL) {
            *bgIdOut = bgId;
        }
        // Big enough to be worth climbing; anything smaller behaves like a block.
        return (halfHeight >= STASIS_CLIMB_MIN_HALF_HEIGHT) ? STASIS_KIND_CLIMBABLE : STASIS_KIND_BLOCK;
    }

    return STASIS_KIND_NONE;
}

static s32 Stasis_TargetFilter(Actor* actor) {
    return Stasis_Classify(gPlayState, actor, NULL) != STASIS_KIND_NONE;
}

static const u8 sStasisCats[3] = { ACTORCAT_ENEMY, ACTORCAT_PROP, ACTORCAT_BG };

// ============================================================================
// FREEZE / THAW
// ============================================================================

// The replacement update. It does the one thing a frozen body still has to do: swallow incoming
// hits, bank them, and make sure the actor itself never reacts.
static void Stasis_FrozenUpdate(Actor* actor, PlayState* play) {
    if (!sStasis.colliderReady || (sStasis.actor != actor)) {
        return;
    }

    // Held completely still — but ONLY while frozen. The takeover is kept through the launch, so
    // zeroing unconditionally here would cancel the throw the instant it started.
    if (sStasis.phase == STASIS_PHASE_FROZEN) {
        actor->velocity.x = actor->velocity.y = actor->velocity.z = 0.0f;
        actor->speed = 0.0f;
    }
}

// The tint. Wrapping the actor's own draw is the only way to recolour a foreign actor: the engine's
// colour filter is three hardcoded modes (white/red/blue) and structurally cannot make yellow, so
// the gold comes from the grayscale tint, whose 4th argument is a blend weight — free pulsing.
// Yellow when idle, red when fully charged.
static void Stasis_ChargeColor(f32 t, u8* r, u8* g, u8* b) {
    *r = (u8)(STASIS_TINT_R + ((f32)(STASIS_TINT_HOT_R - STASIS_TINT_R) * t));
    *g = (u8)(STASIS_TINT_G + ((f32)(STASIS_TINT_HOT_G - STASIS_TINT_G) * t));
    *b = (u8)(STASIS_TINT_B + ((f32)(STASIS_TINT_HOT_B - STASIS_TINT_B) * t));
}

static void Stasis_TintDraw(Actor* actor, PlayState* play) {
    ActorFunc inner = NULL;
    f32 pulse;
    u8 lerp;
    u8 tr;
    u8 tg;
    u8 tb;

    if ((sStasis.actor == actor) && (sStasis.origDraw != NULL)) {
        inner = sStasis.origDraw;
        // Held: full strength. The blend weight is what decides how much of the original survives,
        // and anything below ~230 reads as "slightly warm" rather than "this is in stasis".
        pulse = 0.5f + (0.5f * Math_SinS((s16)(sStasis.age * 0x900)));
        lerp = (u8)(235.0f + (20.0f * pulse));
        Stasis_ChargeColor(Stasis_ChargeFraction(), &tr, &tg, &tb);
    } else if ((sStasisOffer == actor) && (sStasisOfferDraw != NULL)) {
        inner = sStasisOfferDraw;
        // Merely offered: a faster, weaker shimmer, so "aimed at" never reads as "already frozen".
        pulse = 0.5f + (0.5f * Math_SinS((s16)(play->gameplayFrames * 0x1800)));
        lerp = (u8)(110.0f + (70.0f * pulse));
        Stasis_ChargeColor(0.0f, &tr, &tg, &tb); // nothing is charged yet — plain gold
    } else {
        return;
    }

    OPEN_DISPS(play->state.gfxCtx);

    // The three steps, in the order the hardware runs them.
    //
    // STEP 2 — BRIGHTNESS. An actor's own materials pick their own combiners, so unlike the chains
    //   there is no combiner of ours to lift them with. The lever that DOES reach them is the
    //   light: Actor_Draw calls Lights_Draw immediately before actor->draw, so replacing that with
    //   a near-white ambient here overrides it for this model only, and every lit material comes
    //   out far brighter. This is what stops a dark tree tinting to olive instead of gold.
    // STEPS 1 & 3 — GRAYSCALE, then YELLOW. The shader pass runs AFTER the combiner
    //   (libultraship default.shader.hlsl: intensity = (r+g+b)/3, new_texel = grayscale.rgb *
    //   intensity), so it takes the brightened colour, flattens its hue, and multiplies by gold.
    gSPSetLights1(POLY_OPA_DISP++, sStasisLights);
    gSPSetLights1(POLY_XLU_DISP++, sStasisLights);

    gDPPipeSync(POLY_OPA_DISP++);
    gDPSetGrayscaleColor(POLY_OPA_DISP++, tr, tg, tb, lerp);
    gSPGrayscale(POLY_OPA_DISP++, true);
    gDPPipeSync(POLY_XLU_DISP++);
    gDPSetGrayscaleColor(POLY_XLU_DISP++, tr, tg, tb, lerp);
    gSPGrayscale(POLY_XLU_DISP++, true);
    CLOSE_DISPS(play->state.gfxCtx);

    inner(actor, play);

    OPEN_DISPS(play->state.gfxCtx);
    gSPGrayscale(POLY_OPA_DISP++, false);
    gSPGrayscale(POLY_XLU_DISP++, false);
    CLOSE_DISPS(play->state.gfxCtx);
}

// Unregister the collision we built, if we built any. Only ever deletes what WE registered:
// deleting an actor's own bgId would leave a pushblock without collision for the rest of the scene.
static void Stasis_DropCollision(void) {
    if (sStasis.bgIsOurs && (sStasis.bgId >= 0) && (gPlayState != NULL)) {
        DynaPoly_DeleteBgActor(gPlayState, &gPlayState->colCtx.dyna, sStasis.bgId);
    }
    sStasis.bgIsOurs = 0;
    sStasis.bgId = -1;
}

// Hand the actor back exactly as we found it. Guarded on update != NULL throughout: that is the
// "did it die while we owned it" test.
static void Stasis_RestoreActor(void) {
    Actor* actor = sStasis.actor;

    Stasis_DropCollision();

    if ((actor != NULL) && (actor->update != NULL)) {
        actor->update = sStasis.origUpdate;
        if (sStasis.origDraw != NULL) {
            actor->draw = sStasis.origDraw;
        }
        actor->flags = sStasis.origFlags;
        actor->gravity = sStasis.origGravity;
        actor->minVelocityY = sStasis.origMinVelocityY;
        actor->shape.rot = sStasis.origShapeRot;
        actor->world.rot = sStasis.origWorldRot;
        actor->room = (s8)sStasis.origRoom;
        actor->colChkInfo.mass = sStasis.origMass;
        actor->speed = 0.0f;
        actor->velocity.x = actor->velocity.y = actor->velocity.z = 0.0f;
    }
}

// Drop every pointer WITHOUT writing through them. The scene-change path: by the time this runs the
// actors are gone and restoring their state would be a use-after-free.
void Stasis_Forget(void) {
    sStasis.actor = NULL;
    sStasis.kind = STASIS_KIND_NONE;
    sStasis.phase = STASIS_PHASE_FROZEN;
    sStasis.timer = 0;
    sStasis.chainTimer = 0;
    sStasis.age = 0;
    sStasis.accumDamage = 0;
    sStasis.force = 0.0f;
    sStasis.hitDir.x = sStasis.hitDir.y = sStasis.hitDir.z = 0.0f;
    sStasis.hasHitDir = 0;
    sStasis.bgId = -1;
}

// The launch direction as a unit vector, in full 3D. Falls back to "away from Link, level" when
// nothing has struck it yet.
static void Stasis_LaunchDir(PlayState* play, Vec3f* out) {
    Actor* actor = sStasis.actor;

    if (sStasis.hasHitDir) {
        *out = sStasis.hitDir;
        return;
    }
    {
        Player* player = GET_PLAYER(play);
        f32 dx = actor->world.pos.x - player->actor.world.pos.x;
        f32 dz = actor->world.pos.z - player->actor.world.pos.z;
        f32 len = sqrtf((dx * dx) + (dz * dz));

        if (len > 0.001f) {
            out->x = dx / len;
            out->z = dz / len;
        } else {
            out->x = 0.0f;
            out->z = 1.0f;
        }
        out->y = 0.0f;
    }
}

// How charged it is, 0..1. Drives both the arrow's length and the yellow-to-red fade.
static f32 Stasis_ChargeFraction(void) {
    f32 f = sStasis.force / (STASIS_LAUNCH_MAX - STASIS_LAUNCH_BASE);

    return (f > 1.0f) ? 1.0f : ((f < 0.0f) ? 0.0f : f);
}

static f32 Stasis_LaunchSpeed(void) {
    f32 speed = STASIS_LAUNCH_BASE + sStasis.force;

    return (speed > STASIS_LAUNCH_MAX) ? STASIS_LAUNCH_MAX : speed;
}

// End the stasis: enemies take their stored beating, everything else flies.
static void Stasis_End(PlayState* play) {
    Actor* actor = sStasis.actor;

    // The cue's tail IS the release, so it is only cut short when the stasis is broken early.
    if (sStasis.timer > 0) {
        StasisSfx_Stop();
    }

    if ((actor == NULL) || (actor->update == NULL)) {
        Stasis_Forget();
        return;
    }

    if (sStasis.kind == STASIS_KIND_ENEMY) {
        // Enemies are never launched (user-locked) — they just receive everything at once.
        //
        // The damage is applied directly rather than handed to the actor's own AC branch: that
        // branch only runs when the enemy's OWN collider reports AC_HIT, and ours is a different
        // collider. An enemy whose death is written inside that branch will therefore fall on the
        // next real hit rather than the instant it thaws, with its health already at zero.
        if (sStasis.accumDamage > 0) {
            s32 health = actor->colChkInfo.health - (s32)sStasis.accumDamage;

            actor->colChkInfo.health = (health > 0) ? (u8)health : 0;
            Actor_SetColorFilter(actor, COLORFILTER_COLORFLAG_RED, 255, COLORFILTER_BUFFLAG_OPA, 16);
            Actor_PlaySfx(actor, NA_SE_IT_HAMMER_HIT);
        }
        Stasis_RestoreActor();
        Stasis_Forget();
        return;
    }

    if (sStasis.force <= 0.0f) {
        // Nothing charged it — it simply resumes.
        Stasis_RestoreActor();
        Stasis_Forget();
        return;
    }

    // Launch. The engine derives velocity.x/z from world.rot.y + speed, so those are what we set.
    // The takeover is KEPT for the flight: our update stays in place and Stasis_Update flies it,
    // exactly as the Pacci lift does with a thrown object.
    {
        Vec3f dir;
        f32 speed = Stasis_LaunchSpeed();
        f32 horiz;
        s16 yaw;

        Stasis_LaunchDir(play, &dir);
        horiz = sqrtf((dir.x * dir.x) + (dir.z * dir.z));

        // Full 3D: the horizontal part of the blow becomes speedXZ along its yaw, the vertical part
        // becomes velocity.y, and gravity takes it from there. A hit arriving from below therefore
        // genuinely launches the body upward instead of skidding it along the floor.
        yaw = (horiz > 0.001f) ? Math_FAtan2F(dir.x, dir.z) * (0x8000 / M_PI) : actor->shape.rot.y;
        actor->world.rot.y = yaw;
        actor->shape.rot.y = yaw;
        actor->speed = speed * horiz;
        actor->velocity.y = (speed * dir.y) + STASIS_LAUNCH_VEL_Y;
        actor->gravity = STASIS_GRAVITY;
        actor->bgCheckFlags &= ~(BGCHECKFLAG_GROUND | BGCHECKFLAG_GROUND_TOUCH);
    }

    // The collision flies WITH it. The carrier is re-parked on the body every frame, so the thing
    // stays solid and grabbable the whole way — and it is only handed back to the real actor when
    // it lands (Stasis_RestoreActor drops the carrier there).
    sStasis.phase = STASIS_PHASE_FLYING;
    sStasis.timer = STASIS_FLIGHT_FRAMES;
    Actor_PlaySfx(actor, NA_SE_EV_HEAVY_THROW);
}

// Take the actor over.
static void Stasis_Begin(PlayState* play, Actor* target, u8 kind, s32 bgId) {
    // Drop the offer wrapper first: it is about to be replaced by the real one, and restoring it
    // afterwards would put the plain draw back over ours.
    Stasis_ClearOffer();
    Stasis_Forget();

    sStasis.actor = target;
    sStasis.kind = kind;
    sStasis.phase = STASIS_PHASE_FROZEN;
    sStasis.timer = (kind == STASIS_KIND_ENEMY) ? STASIS_FRAMES_ENEMY : STASIS_FRAMES_OBJECT;
    sStasis.chainTimer = STASIS_CHAIN_FRAMES;
    sStasis.bgId = (kind == STASIS_KIND_CLIMBABLE) ? bgId : -1;
    sStasis.bgIsOurs = 0;

    // A body with no dynapoly of its own gets one built for it. That is what makes a frozen boulder
    // read as SOLID — you can stand on it, it stops what it is hit with, and its wall is climbable
    // — instead of a cylinder Link walks through. Blocks and platforms already own real collision,
    // so they are left alone.
    if ((kind != STASIS_KIND_ENEMY) && (kind != STASIS_KIND_BLOCK) && (bgId < 0)) {
        s32 newBgId = Stasis_BuildCollision(play, target);

        if (newBgId >= 0) {
            sStasis.bgId = newBgId;
            sStasis.bgIsOurs = 1;
            sStasis.kind = STASIS_KIND_CLIMBABLE; // it has a wall now, so it can be climbed
        }
    }

    sStasis.origUpdate = target->update;
    sStasis.origDraw = target->draw;
    sStasis.origFlags = target->flags;
    sStasis.origGravity = target->gravity;
    sStasis.origMinVelocityY = target->minVelocityY;
    sStasis.origSpeed = target->speed;
    sStasis.origShapeRot = target->shape.rot;
    sStasis.origWorldRot = target->world.rot;
    sStasis.origRoom = target->room;
    sStasis.origMass = target->colChkInfo.mass;

    if (!sStasis.colliderReady) {
        Collider_InitCylinder(play, &sStasis.collider);
        sStasis.colliderReady = 1;
    }
    Collider_SetCylinder(play, &sStasis.collider, target, &sStasisColliderInit);

    target->update = Stasis_FrozenUpdate;
    target->draw = Stasis_TintDraw;
    target->velocity.x = target->velocity.y = target->velocity.z = 0.0f;
    target->speed = 0.0f;
    target->gravity = 0.0f;
    // Without this the engine culls the actor when the player looks away and stops running OUR
    // update with it — the object would thaw itself off-screen.
    target->flags |= ACTOR_FLAG_UPDATE_CULLING_DISABLED | ACTOR_FLAG_DRAW_CULLING_DISABLED;
    target->room = -1; // survive a room change while frozen

    // The rune's own cue. Enemies get it at double rate — the same sound, straining, which is what
    // sells a living thing fighting the field instead of a rock simply stopping.
    StasisSfx_Play((kind == STASIS_KIND_ENEMY) ? 2.0f : 1.0f, 0.85f);
}

// ============================================================================
// ENTRY POINTS
// ============================================================================

// Take our wrapper off whatever was being offered last frame. Guarded on the pointer still being
// ours: if the actor died, or something else replaced its draw, we must not write over that.
static void Stasis_ClearOffer(void) {
    if ((sStasisOffer != NULL) && (sStasisOffer->update != NULL) && (sStasisOffer->draw == Stasis_TintDraw) &&
        (sStasisOfferDraw != NULL)) {
        sStasisOffer->draw = sStasisOfferDraw;
    }
    sStasisOffer = NULL;
    sStasisOfferDraw = NULL;
}

// Paint whatever the rune is currently aimed at. Called EVERY frame — `allowed` says whether the
// slate is actually out on this rune. Called unconditionally on purpose: the clear at the top is
// what takes the shimmer off the last target when the tablet goes away.
void Stasis_UpdateOffer(PlayState* play, u8 allowed) {
    Actor* target;

    Stasis_ClearOffer();

    if (!allowed) {
        return;
    }
    if (sStasis.actor != NULL) {
        return; // already holding something — the offer would only confuse the read
    }
    target = TargetSelect_ScanCats(play, sStasisCats, ARRAY_COUNT(sStasisCats), Stasis_TargetFilter, STASIS_RANGE,
                                   TARGETSEL_DEFAULT_CONE);
    if ((target == NULL) || (target->draw == NULL) || (target->draw == Stasis_TintDraw)) {
        return;
    }
    sStasisOffer = target;
    sStasisOfferDraw = target->draw;
    target->draw = Stasis_TintDraw;
}

s32 Stasis_Cast(PlayState* play, Player* player) {
    Actor* target;
    s32 bgId = -1;
    u8 kind;

    // A second cast releases what is already held, whatever it is aimed at.
    if (sStasis.actor != NULL) {
        Stasis_End(play);
        return 1;
    }

    target = TargetSelect_ScanCats(play, sStasisCats, ARRAY_COUNT(sStasisCats), Stasis_TargetFilter, STASIS_RANGE,
                                   TARGETSEL_DEFAULT_CONE);
    if (target == NULL) {
        return 0; // nothing in range — the caller plays the error
    }

    kind = Stasis_Classify(play, target, &bgId);
    if (kind == STASIS_KIND_NONE) {
        return 0;
    }

    Stasis_Begin(play, target, kind, bgId);
    return 1;
}

// Read and bank an incoming blow.
//
// This MUST run before Stasis_Update re-registers the collider. CollisionCheck_SetAC calls the
// shape's AC reset first (Collider_ResetACBase: `ac = NULL; acFlags &= ~AC_HIT`), so registering
// wipes both the hit flag and the attacker. That is the bug that made every arrow read as "no
// attacker" and fall back to "away from Link" — the direction was never captured at all. It also
// cannot live in the frozen actor's own update: that runs in the PROP pass, long after the player
// pass where the tick sits.
static void Stasis_CaptureHit(PlayState* play, Actor* actor) {
    if (sStasis.collider.base.acFlags & AC_HIT) {
        Player* player = GET_PLAYER(play);
        // Who actually landed the blow. For an arrow this is the arrow actor, not Link — which is
        // the whole point: an arrow arriving from below-left must send the object up and to the
        // right, no matter where Link was standing when he loosed it.
        //
        // It is `.ac`, NOT `.at`. On a hit the engine writes `at->at = ac->actor` on the ATTACKER's
        // collider and `ac->ac = at->actor` on the VICTIM's (z_collision_check.c:1755/1764). Ours is
        // the victim, so `.at` here is whatever WE last hit while flying — reading it meant the
        // attacker came back NULL and the direction fell through to "away from Link" every time,
        // which is exactly the bug where the arrow always pointed along Link's line.
        Actor* attacker = sStasis.collider.base.ac;
        Vec3f dir;
        f32 len;

        if (attacker == NULL) {
            attacker = &player->actor;
        }

        // A projectile carries its real flight vector, so the object continues along it. Anything
        // swung by hand (sword, hammer) has no useful velocity, so the line attacker -> body is
        // what "the side it came from" means there. Both are full 3D.
        len = sqrtf((attacker->velocity.x * attacker->velocity.x) + (attacker->velocity.y * attacker->velocity.y) +
                    (attacker->velocity.z * attacker->velocity.z));
        if (len > 1.0f) {
            dir.x = attacker->velocity.x / len;
            dir.y = attacker->velocity.y / len;
            dir.z = attacker->velocity.z / len;
        } else {
            dir.x = actor->world.pos.x - attacker->world.pos.x;
            dir.y = (actor->world.pos.y + (actor->shape.yOffset * actor->scale.y)) - 
                    (attacker->world.pos.y + 30.0f);
            dir.z = actor->world.pos.z - attacker->world.pos.z;
            len = sqrtf((dir.x * dir.x) + (dir.y * dir.y) + (dir.z * dir.z));
            if (len > 0.001f) {
                dir.x /= len;
                dir.y /= len;
                dir.z /= len;
            } else {
                dir.x = 0.0f;
                dir.y = 0.0f;
                dir.z = 1.0f;
            }
        }
        // A rock or a tree takes NO damage from a sword — colChkInfo.damage stays 0 — so keying
        // any of this on damage meant hitting exactly the things Stasis exists for did nothing.
        // Every connected blow charges the launch; damage only decides how MUCH.
        f32 dmg = (f32)actor->colChkInfo.damage;
        f32 charge = (dmg > 0.0f) ? (dmg * STASIS_LAUNCH_PER_DAMAGE) : STASIS_LAUNCH_PER_HIT;

        sStasis.collider.base.acFlags &= ~AC_HIT;

        {
            sStasis.accumDamage += actor->colChkInfo.damage;
            sStasis.force += charge;
            // The LAST blow owns the direction outright. Damage only ever adds to the magnitude,
            // which is why you can keep re-aiming a fully charged rock with one light tap.
            sStasis.hitDir = dir;
            sStasis.hasHitDir = 1;
            // Zeroed so the actor never sees it. CollisionCheck_ResetDamage would wipe it a frame
            // later anyway, which is exactly why this has to happen here, inside our update.
            actor->colChkInfo.damage = 0;
            actor->colChkInfo.damageEffect = 0;

            // Recoil. A body held out of time does not budge, so the blow comes back at whoever
            // threw it — that bounce is the whole read on "this thing is now immovable".
            Combat_ApplyKnockbackFromPoint(&player->actor, &actor->world.pos, STASIS_RECOIL_SPEED,
                                           STASIS_RECOIL_HEIGHT);
            Actor_PlaySfx(actor, NA_SE_IT_SHIELD_REFLECT_MG);
        }
    }
}

void Stasis_Update(PlayState* play, Player* player) {
    static s16 sLastScene = -1;
    Actor* actor;

    // Scene change: the actors are already gone, so the pointer is dropped WITHOUT writing through
    // it. Detected here rather than through a hook, the same way the timestop helper does it.
    if (sLastScene != play->sceneId) {
        sLastScene = play->sceneId;
        Stasis_Forget();
        return;
    }

    actor = sStasis.actor;
    if (actor == NULL) {
        return;
    }
    // Died, despawned, or the scene took it: drop it without writing through the pointer.
    if (actor->update == NULL) {
        Stasis_Forget();
        return;
    }

    sStasis.age++;
    if (sStasis.chainTimer > 0) {
        sStasis.chainTimer--;
    }

    if (sStasis.phase == STASIS_PHASE_FLYING) {
        Actor_MoveWithGravity(actor);
        Actor_UpdateBgCheckInfo(play, actor, 5.0f, 15.0f, 0.0f, 0x85);

        // Drag the collision along, so a launched boulder is still something Link can be crushed by
        // or ride, not a ghost that happens to be drawn.
        if (sStasis.bgIsOurs) {
            Stasis_CarrierSync(actor);
        }

        if (sStasis.colliderReady) {
            Collider_UpdateCylinder(actor, &sStasis.collider);
            CollisionCheck_SetAT(play, &play->colChkCtx, &sStasis.collider.base);
        }
        if (sStasis.timer > 0) {
            sStasis.timer--;
        }
        // Landed, hit a wall, connected with something, or ran out of flight time.
        if ((actor->bgCheckFlags & (BGCHECKFLAG_GROUND | BGCHECKFLAG_WALL)) || (sStasis.timer <= 0) ||
            (sStasis.collider.base.atFlags & AT_HIT)) {
            Actor_PlaySfx(actor, NA_SE_EV_BOMB_DROP_WATER);
            Stasis_RestoreActor();
            Stasis_Forget();
        }
        return;
    }

    // Bank any blow from last frame's collision pass FIRST — re-registering below would erase it.
    Stasis_CaptureHit(play, actor);

    // Keep the collision carrier sitting on the body. It never moves while frozen, but this also
    // covers a body that was nudged by something else before it was caught.
    if (sStasis.bgIsOurs) {
        Stasis_CarrierSync(actor);
    }

    // Frozen: keep the AC live so the body stays hittable while its own update does nothing.
    if (sStasis.colliderReady) {
        Collider_UpdateCylinder(actor, &sStasis.collider);
        CollisionCheck_SetAC(play, &play->colChkCtx, &sStasis.collider.base);
    }

    if (sStasis.timer > 0) {
        sStasis.timer--;
    }
    if (sStasis.timer <= 0) {
        Stasis_End(play);
    }
}

// Only the frozen body's own bgId, and only while it is a climbable kind. Consulted by the wall
// flags getter in z_bgcheck.c, so it reverts by itself the moment the stasis ends.
u8 Stasis_IsClimbableBgId(s32 bgId) {
    return (sStasis.actor != NULL) && (sStasis.kind == STASIS_KIND_CLIMBABLE) && (sStasis.bgId >= 0) &&
           (sStasis.bgId == bgId);
}

// The rune's own sound, plus its PCM. Both are .inc.c rather than headers: mods/*.h is globbed
// with CONFIGURE_DEPENDS in 2ship and a new one there forces a CMake regeneration.
#include "stasis_sfx.inc.c"

#include "stasis_rune_vfx.inc.c"
