compiler_type = "ido"

[preserve_macros]
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"gDma.*" = "void"
"G_IM_SIZ_.*" = "int"
"G_IM_FMT_.*" = "int"
"G_TX_.*" = "int"
"G_[AC]C.*" = "int"
LOG = "void"
SET_FULLSCREEN_VIEWPORT = "void"
OPEN_DISPS = "void"
CLOSE_DISPS = "void"
ABS = "int"
ABS_ALT = "int"
SQ = "int"
ARRAY_COUNT = "int"
ARRAY_COUNTU = "int"
CLAMP = "int"
CLOCK_TIME = "int"
CURRENT_DAY = "int"
CHECK_NEWF = "int"
NULL = "int"
"SCREEN_.*" = "int"
GET_PLAYER = "int"
CHECK_WEEKEVENTREG = "int"
SET_WEEKEVENTREG = "int"
CLEAR_WEEKEVENTREG = "int"
"WEEKEVENTREG_.+" = "int"
CHECK_EVENTINF = "int"
SET_EVENTINF = "int"
CLEAR_EVENTINF = "int"
CLEAR_EVENTINF_ALT = "int"
"EVENTINF_.*" = "int"
".+REG" = "int"
SET_FULLSCREEN_VIEWPORT_DYNAMIC = "void"
gDrawRect = "void"

[decompme.compilers]
"tools/ido_recomp/linux/7.1/cc" = "ido7.1"
"tools/ido_recomp/macos/7.1/cc" = "ido7.1"
"tools/ido_recomp/windows/7.1/cc" = "ido7.1"
"tools/ido_recomp/linux/5.3/cc" = "ido5.3"
"tools/ido_recomp/macos/5.3/cc" = "ido5.3"
"tools/ido_recomp/windows/5.3/cc" = "ido5.3"
