#ifndef ACHIEVEMENTTYPES_H
#define ACHIEVEMENTTYPES_H

typedef enum {
    AID_UNKNOWN, // Start with unknown, similar to RC_UNKNOWN

    // Bomber's Notebook (BN)
    AID_BN_HONORARY_MEMBER,
    AID_BN_FAITHFUL_BRIDE,
    AID_BN_MINI_HE,
    AID_BN_AMBIGUOUS_ALLEGIANCE,
    AID_BN_FRAIL_DID,
    AID_BN_BRAVE_LITTLE_ARCHER,
    AID_BN_MATURE_RANCH_HAND,
    AID_BN_DROWNING_IN_RESPONSIBILITIES,
    AID_BN_CONCERNED_MOTHER,
    AID_BN_LOOKING_FOR_VOLUNTEERS,
    AID_BN_BREAKAWAY_BROTHER,
    AID_BN_ALWAYS_MAKES_HIS_APPOINTED_DELIVERIES,
    AID_BN_PREPARE_FOR_TROUBLE,
    AID_BN_YOU_MISSED_A_SPOT,
    AID_BN_STORYTELLER,
    AID_BN_PASSING_ON_THE_GROOVE,
    AID_BN_CARETAKER_OF_THE_FOWL,
    AID_BN_THERES_THREE_OF_YOU,
    AID_BN_PERFECTING_THE_ART,
    AID_BN_WINDMILL_MAN,
    AID_BN_LOCAL_HERO,

    // Time Manipulation
    AID_INTERNAL_SONG_DOUBLE_TIME_PLAYED,
    AID_INTERNAL_SONG_REVERSE_TIME_PLAYED,
    AID_TIMELORD,

    AID_MAX, // Represents the total number of defined achievements + 1 (for UNKNOWN)
} AchievementId;

#endif // ACHIEVEMENTTYPES_H