#pragma once

typedef enum {
    // Bomber's Notebook (BN) - All 20 individual achievements
    BN_HONORARY_MEMBER,
    BN_FAITHFUL_BRIDE,
    BN_MINI_HE,
    BN_AMBIGUOUS_ALLEGIANCE,
    BN_FRAIL_DID,
    BN_BRAVE_LITTLE_ARCHER,
    BN_MATURE_RANCH_HAND,
    BN_DROWNING_IN_RESPONSIBILITIES,
    BN_CONCERNED_MOTHER,
    BN_LOOKING_FOR_VOLUNTEERS,
    BN_BREAKAWAY_BROTHER,
    BN_ALWAYS_MAKES_HIS_APPOINTED_DELIVERIES,
    BN_PREPARE_FOR_TROUBLE,
    BN_YOU_MISSED_A_SPOT,
    BN_STORYTELLER,
    BN_PASSING_ON_THE_GROOVE,
    BN_CARETAKER_OF_THE_FOWL,
    BN_THERES_THREE_OF_YOU,
    BN_PERFECTING_THE_ART,
    BN_WINDMILL_MAN,
    BN_LOCAL_HERO, // Meta-achievement for completing all BN entries

    // Time Manipulation
    TIMELORD, // Replaces the old internal achievement system

    ACHIEVEMENT_ID_MAX
} AchievementId;

typedef enum {
    // Honorary Member Events (maps to LEARNED_SECRET_CODE + RECEIVED_BOMBERS_NOTEBOOK)
    EVENT_LEARNED_SECRET_CODE,
    EVENT_RECEIVED_BOMBERS_NOTEBOOK,

    // Faithful Bride Events (maps to 6 specific WEEKEVENTREG flags)
    EVENT_RECEIVED_ROOM_KEY,
    EVENT_PROMISED_MIDNIGHT_MEETING,
    EVENT_RECEIVED_LETTER_TO_KAFEI,
    EVENT_DEPOSITED_LETTER_TO_KAFEI,
    EVENT_DELIVERED_PENDANT_OF_MEMORIES,
    EVENT_RECEIVED_COUPLES_MASK,

    // Mini-He Events (maps to 4 specific WEEKEVENTREG flags)
    EVENT_PROMISED_TO_MEET_KAFEI,
    EVENT_RECEIVED_PENDANT_OF_MEMORIES,
    EVENT_ESCAPED_SAKONS_HIDEOUT,
    // NOTE: RECEIVED_COUPLES_MASK is shared between Faithful Bride and Mini-He

    // Ambiguous Allegiance Events (maps to 3 specific WEEKEVENTREG flags)
    EVENT_RECEIVED_KEATON_MASK,
    EVENT_RECEIVED_PRIORITY_MAIL,
    EVENT_RECEIVED_ALL_NIGHT_MASK,

    // Frail D.I.D. Event (maps to single WEEKEVENTREG flag)
    EVENT_RECEIVED_BLAST_MASK,

    // Brave Little Archer Events (maps to 3 specific WEEKEVENTREG flags)
    EVENT_PROMISED_TO_HELP_WITH_THEM,
    EVENT_DEFENDED_AGAINST_THEM,
    EVENT_RECEIVED_MILK_BOTTLE,

    // Mature Ranch Hand Events (maps to 2 specific WEEKEVENTREG flags)
    EVENT_ESCORTED_CREMIA,
    EVENT_RECEIVED_ROMANIS_MASK,

    // Single-event achievements (maps to individual WEEKEVENTREG flags)
    EVENT_RECEIVED_MAYOR_HP,
    EVENT_DELIVERED_PRIORITY_MAIL,
    EVENT_RECEIVED_CIRCUS_LEADERS_MASK,
    EVENT_MET_GORMAN,
    EVENT_RECEIVED_POSTMAN_HP,
    EVENT_RECEIVED_POSTMANS_HAT,
    EVENT_RECEIVED_ROSA_SISTERS_HP,
    EVENT_RECEIVED_TOILET_HAND_HP,
    EVENT_RECEIVED_GRANDMA_SHORT_STORY_HP,
    EVENT_RECEIVED_GRANDMA_LONG_STORY_HP,
    EVENT_RECEIVED_KAMAROS_MASK,
    EVENT_RECEIVED_BUNNY_HOOD,
    EVENT_RECEIVED_GAROS_MASK,
    EVENT_RECEIVED_STONE_MASK,
    EVENT_RECEIVED_BREMEN_MASK,
    EVENT_RECEIVED_KAFEIS_MASK,

    // Time manipulation events (replaces internal achievements)
    EVENT_PLAYED_SONG_OF_DOUBLE_TIME,
    EVENT_PLAYED_INVERTED_SONG_OF_TIME,

    // Miscellaneous events (Currently unused)
    EVENT_TINGLE_MAP_CLOCK_TOWN,
    EVENT_TINGLE_MAP_WOODFALL,
    EVENT_TINGLE_MAP_SNOWHEAD,
    EVENT_TINGLE_MAP_ROMANI_RANCH,
    EVENT_RECEIVED_LAND_TITLE_DEED,
    EVENT_BANK_REWARD_3,
    EVENT_BANK_REWARD_2,
    EVENT_BANK_REWARD_1,
    EVENT_LEARNED_SONATA_OF_AWAKENING,
    EVENT_DEKU_PLAYGROUND_REWARD_ALL_DAYS,
    EVENT_DEKU_PLAYGROUND_REWARD_ANY_DAY,
    EVENT_RECEIVED_MASK_OF_SCENTS,
    EVENT_RECEIVED_DOGGY_RACETRACK_HP,
    EVENT_RECEIVED_GREAT_SPIN_ATTACK,
    EVENT_GORON_RACE_REWARD,
    EVENT_RECEIVED_BOMB_BAG_FROM_GORON_SCRUB,
    EVENT_RECEIVED_MOUNTAIN_TITLE_DEED,
    EVENT_RECEIVED_POWDER_KEG,
    EVENT_HONEY_DARLING_REWARD_ALL_DAYS,
    EVENT_HONEY_DARLING_REWARD_ANY_DAY,
    EVENT_RECEIVED_LAB_FISH_HP,
    EVENT_LEARNED_ZORA_SONG,
    EVENT_CLOCK_TOWN_STRAY_FAIRY,
    EVENT_RECEIVED_DON_GERO_MASK,
    EVENT_RECEIVED_MOON_TEAR,
    EVENT_RECEIVED_PINNACLE_ROCK_HP,
    EVENT_TOWN_ARCHERY_REWARD_1,
    EVENT_SWAMP_ARCHERY_REWARD_1,
    EVENT_SWAMP_ARCHERY_REWARD_2,
    EVENT_RECEIVED_SWAMP_TITLE_DEED,
    EVENT_LEARNED_SONG_OF_SOARING,
    EVENT_SWORDSMAN_SCHOOL_HP,
    EVENT_BOAT_ARCHERY_HEART_PIECE,
    EVENT_RECEIVED_PICTOGRAPH_BOX,
    EVENT_TINGLE_PICTURE_HEART_PIECE,
    EVENT_LEARNED_GORON_LULLABY_INTRO,
    EVENT_BEAVER_RACE_2,
    EVENT_BEAVER_RACE_1,
    EVENT_RECEIVED_RED_POTION,
    EVENT_RECEIVED_OCEAN_TITLE_DEED,
    EVENT_ZORA_HALL_EVAN_HP,

    ACHIEVEMENT_EVENT_MAX
} AchievementEvent;