#ifndef EXT_EQUIP_ICON_ASSETS_H
#define EXT_EQUIP_ICON_ASSETS_H 1
#include "align_asset_macro.h"
// Custom EQUIPMENT icon textures (dg-macro string form used by sExtEquipIconPaths).
#define dgItemIconCaneOfByrnaTex "__OTR__textures/icon_item_custom/gItemIconCaneOfByrnaTex"
#define dgItemIconFourSwordTex "__OTR__textures/icon_item_custom/gItemIconFourSwordTex"
#define dgItemIconDrillshaftTex "__OTR__textures/icon_item_custom/gItemIconDrillshaftTex"
#define dgItemIconDivineShieldTex "__OTR__textures/icon_item_custom/gItemIconDivineShieldTex"
#define dgItemIconGerudoScimitarTex "__OTR__textures/icon_item_custom/gItemIconGerudoScimitarTex"
#define dgItemIconMagicCapeTex "__OTR__textures/icon_item_custom/gItemIconMagicCapeTex"
#define dgItemIconPending4Tex "__OTR__textures/icon_item_custom/gItemIconPending4Tex"
#define dgItemIconChampionsTunicTex "__OTR__textures/icon_item_custom/gItemIconChampionsTunicTex"
#define dgItemIconPegasusAnkletTex "__OTR__textures/icon_item_custom/gItemIconPegasusAnkletTex"
#define dgItemIconWaterDragonScaleTex "__OTR__textures/icon_item_custom/gItemIconWaterDragonScaleTex"
#endif
