#include <optional>
#include <string>
#include <vector>

namespace SOH {
enum class MigrationAction {
    Rename,
    Remove,
};

struct Migration {
    MigrationAction action;
    std::string from;
    std::optional<std::string> to = std::nullopt;
};

// clang-format off
std::vector<Migration> version1Migrations = {
    { MigrationAction::Rename, "gRando.CheckTracker.HideCollectedChecks", "gTrackers.CheckTracker.HideCollectedChecks" },
    { MigrationAction::Rename, "gRando.CheckTracker.HideSkippedChecks", "gTrackers.CheckTracker.HideSkippedChecks" },
    { MigrationAction::Rename, "gRando.CheckTracker.OnlyShowChecksInLogic", "gTrackers.CheckTracker.OnlyShowChecksInLogic" },
    { MigrationAction::Rename, "gRando.CheckTracker.Opacity", "gTrackers.CheckTracker.Opacity" },
    { MigrationAction::Rename, "gRando.CheckTracker.Scale", "gTrackers.CheckTracker.Scale" },
    { MigrationAction::Rename, "gRando.CheckTracker.ScrollToCurrentScene", "gTrackers.CheckTracker.ScrollToCurrentScene" },
    { MigrationAction::Rename, "gRando.CheckTracker.ShowCurrentScene", "gTrackers.CheckTracker.ShowCurrentScene" },
    { MigrationAction::Rename, "ItemTracker.BgColorR", "gTrackers.ItemTracker.BgColorR" },
    { MigrationAction::Rename, "ItemTracker.BgColorG", "gTrackers.ItemTracker.BgColorG" },
    { MigrationAction::Rename, "ItemTracker.BgColorB", "gTrackers.ItemTracker.BgColorB" },
    { MigrationAction::Rename, "ItemTracker.BgColorA", "gTrackers.ItemTracker.BgColorA" },
    { MigrationAction::Rename, "ItemTracker.IconSize", "gTrackers.ItemTracker.IconSize" },
    { MigrationAction::Rename, "ItemTracker.IconSpacing", "gTrackers.ItemTracker.IconSpacing" },
    { MigrationAction::Rename, "ItemTracker.TextSize", "gTrackers.ItemTracker.TextSize" },
    { MigrationAction::Rename, "ItemTracker.TextOffset", "gTrackers.ItemTracker.TextOffset" },
    { MigrationAction::Rename, "ItemTracker.WindowType", "gTrackers.ItemTracker.WindowType" },
    { MigrationAction::Rename, "ItemTracker.IsDraggable", "gTrackers.ItemTracker.IsDraggable" },
    { MigrationAction::Rename, "ItemTracker.OnlyDrawPaused", "gTrackers.ItemTracker.OnlyDrawPaused" },
    { MigrationAction::Rename, "ItemTracker.IncludeMapsAndCompasses", "gTrackers.ItemTracker.IncludeMapsAndCompasses" },
    { MigrationAction::Rename, "ItemTracker.DrawCurrentAmmo", "gTrackers.ItemTracker.DrawCurrentAmmo" },
    { MigrationAction::Rename, "ItemTracker.DrawMaxAmmo", "gTrackers.ItemTracker.DrawMaxAmmo" },
    { MigrationAction::Rename, "ItemTracker.DrawMaxCapacity", "gTrackers.ItemTracker.DrawMaxCapacity" },
    { MigrationAction::Rename, "ItemTracker.InventoryDrawMode", "gTrackers.ItemTracker.InventoryDrawMode" },
    { MigrationAction::Rename, "ItemTracker.MasksDrawMode", "gTrackers.ItemTracker.MasksDrawMode" },
    { MigrationAction::Rename, "ItemTracker.EquipmentDrawMode", "gTrackers.ItemTracker.EquipmentDrawMode" },
    { MigrationAction::Rename, "ItemTracker.MiscDrawMode", "gTrackers.ItemTracker.MiscDrawMode" },
    { MigrationAction::Rename, "ItemTracker.SongsDrawMode", "gTrackers.ItemTracker.SongsDrawMode" },
    { MigrationAction::Rename, "ItemTracker.StrayFairiesDrawMode", "gTrackers.ItemTracker.StrayFairiesDrawMode" },
    { MigrationAction::Rename, "ItemTracker.GoldSkulltulasDrawMode", "gTrackers.ItemTracker.GoldSkulltulasDrawMode" },
    { MigrationAction::Rename, "ItemTracker.DungeonDrawMode", "gTrackers.ItemTracker.DungeonDrawMode" },
    { MigrationAction::Rename, "gSettings.TimeSplits.Enable", "gTrackers.TimeSplitsTracker.Enable" },
    { MigrationAction::Rename, "gSettings.TimeSplits.Highlight", "gTrackers.TimeSplitsTracker.Highlight" },
    { MigrationAction::Rename, "gSettings.TimeSplits.Compare", "gTrackers.TimeSplitsTracker.Compare" },
    { MigrationAction::Rename, "gSettings.TimeSplits.Follow", "gTrackers.TimeSplitsTracker.Follow" },
    { MigrationAction::Rename, "gSettings.TimeSplits.ShowHeaders", "gTrackers.TimeSplitsTracker.ShowHeaders" },
    { MigrationAction::Rename, "gSettings.TimeSplits.Opacity", "gTrackers.TimeSplitsTracker.Opacity" },
    { MigrationAction::Rename, "gModes.PlayAsKafei", "gEnhancements.Modes.PlayAsKafei" },
    { MigrationAction::Rename, "gModes.HyruleWarriorsStyledLink", "gEnhancements.Modes.HyruleWarriorsStyledLink" },
    { MigrationAction::Rename, "gModes.TimeMovesWhenYouMove", "gEnhancements.Modes.TimeMovesWhenYouMove" },
    { MigrationAction::Rename, "gModes.MirroredWorld.Mode", "gEnhancements.Modes.MirroredWorld.Mode" },
    { MigrationAction::Rename, "gModes.MirroredWorld.State", "gEnhancements.Modes.MirroredWorld.State" },
    { MigrationAction::Rename, "gFixes.FixAmmoCountEnvColor", "gEnhancements.Fixes.FixAmmoCountEnvColor" },
    { MigrationAction::Rename, "gFixes.FixEponaStealingSword", "gEnhancements.Fixes.FixEponaStealingSword" },
    { MigrationAction::Rename, "gFixes.FixIkanaGreatFairyFountainColor", "gEnhancements.Fixes.FixIkanaGreatFairyFountainColor" },
    { MigrationAction::Rename, "gWindows.ItemTracker", "gOpenWindows.ItemTracker" },
    { MigrationAction::Rename, "gWindows.CheckTracker", "gOpenWindows.CheckTracker" },
    { MigrationAction::Rename, "gWindows.Notifications", "gOpenWindows.Notifications" },
    { MigrationAction::Rename, "gWindows.Menu", "gOpenWindows.Menu" },
    { MigrationAction::Rename, "gNotifications.BgOpacity", "gSettings.Notifications.BgOpacity" },
    { MigrationAction::Rename, "gNotifications.Duration", "gSettings.Notifications.Duration" },
    { MigrationAction::Rename, "gNotifications.Position", "gSettings.Notifications.Position" },
    { MigrationAction::Rename, "gNotifications.Size", "gSettings.Notifications.Size" },
    { MigrationAction::Rename, "gDisplayOverlay.Background", "gSettings.DisplayOverlay.Background" },
    { MigrationAction::Rename, "gDisplayOverlay.Scale", "gSettings.DisplayOverlay.Scale" },
    { MigrationAction::Rename, "gInterpolationFPS", "gSettings.Graphics.InterpolationFPS" },
    { MigrationAction::Rename, "gMatchRefreshRate", "gSettings.Graphics.MatchRefreshRate" },
    { MigrationAction::Rename, "gEventLog.Enabled", "gDeveloperTools.EventLog.Enabled" },
    { MigrationAction::Rename, "gEventLog.MaxEntries", "gDeveloperTools.EventLog.MaxEntries" },
    { MigrationAction::Rename, "gEventLog.Filter.ActorInit", "gDeveloperTools.EventLog.Filter.ActorInit" },
    { MigrationAction::Rename, "gEventLog.Filter.ActorKill", "gDeveloperTools.EventLog.Filter.ActorKill" },
    { MigrationAction::Rename, "gEventLog.Filter.FlagSet", "gDeveloperTools.EventLog.Filter.FlagSet" },
    { MigrationAction::Rename, "gEventLog.Filter.FlagUnset", "gDeveloperTools.EventLog.Filter.FlagUnset" },
    { MigrationAction::Rename, "gEventLog.Filter.ItemGive", "gDeveloperTools.EventLog.Filter.ItemGive" },
    { MigrationAction::Rename, "gEventLog.Filter.OpenText", "gDeveloperTools.EventLog.Filter.OpenText" },
    { MigrationAction::Rename, "gEventLog.Filter.RoomInit", "gDeveloperTools.EventLog.Filter.RoomInit" },
    { MigrationAction::Rename, "gEventLog.Filter.SceneFlagSet", "gDeveloperTools.EventLog.Filter.SceneFlagSet" },
    { MigrationAction::Rename, "gEventLog.Filter.SceneFlagUnset", "gDeveloperTools.EventLog.Filter.SceneFlagUnset" },
    { MigrationAction::Rename, "gEventLog.Filter.SceneInit", "gDeveloperTools.EventLog.Filter.SceneInit" },
    { MigrationAction::Rename, "gCollisionViewer.Enabled", "gDeveloperTools.CollisionViewer.Enabled" },
    { MigrationAction::Rename, "gCollisionViewer.ApplyShading", "gDeveloperTools.CollisionViewer.ApplyShading" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionMode", "gDeveloperTools.CollisionViewer.SceneCollisionMode" },
    { MigrationAction::Rename, "gCollisionViewer.BGActorsCollisionMode", "gDeveloperTools.CollisionViewer.BGActorsCollisionMode" },
    { MigrationAction::Rename, "gCollisionViewer.ColCheckCollisionMode", "gDeveloperTools.CollisionViewer.ColCheckCollisionMode" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionMode", "gDeveloperTools.CollisionViewer.WaterboxCollisionMode" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor", "gDeveloperTools.CollisionViewer.ACollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor.Value", "gDeveloperTools.CollisionViewer.ACollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor.Value.A", "gDeveloperTools.CollisionViewer.ACollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor.Value.B", "gDeveloperTools.CollisionViewer.ACollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor.Value.G", "gDeveloperTools.CollisionViewer.ACollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor.Value.R", "gDeveloperTools.CollisionViewer.ACollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.ACollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.ACollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor", "gDeveloperTools.CollisionViewer.ATCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor.Value", "gDeveloperTools.CollisionViewer.ATCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.ATCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.ATCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.ATCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.ATCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.ATCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.ATCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor", "gDeveloperTools.CollisionViewer.EntranceCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor.Value", "gDeveloperTools.CollisionViewer.EntranceCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.EntranceCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.EntranceCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.EntranceCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.EntranceCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.EntranceCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.EntranceCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor", "gDeveloperTools.CollisionViewer.HookshotCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor.Value", "gDeveloperTools.CollisionViewer.HookshotCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.HookshotCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.HookshotCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.HookshotCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.HookshotCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.HookshotCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.HookshotCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor", "gDeveloperTools.CollisionViewer.InteractableColor" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor.Value", "gDeveloperTools.CollisionViewer.InteractableColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor.Value.A", "gDeveloperTools.CollisionViewer.InteractableColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor.Value.B", "gDeveloperTools.CollisionViewer.InteractableColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor.Value.G", "gDeveloperTools.CollisionViewer.InteractableColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor.Value.R", "gDeveloperTools.CollisionViewer.InteractableColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.InteractableColor.Value.Type", "gDeveloperTools.CollisionViewer.InteractableColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor", "gDeveloperTools.CollisionViewer.OCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor.Value", "gDeveloperTools.CollisionViewer.OCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.OCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.OCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.OCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.OCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.OCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.OCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor", "gDeveloperTools.CollisionViewer.SceneCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor.Value", "gDeveloperTools.CollisionViewer.SceneCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.SceneCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.SceneCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.SceneCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.SceneCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.SceneCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.SceneCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor", "gDeveloperTools.CollisionViewer.SlopeCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor.Value", "gDeveloperTools.CollisionViewer.SlopeCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.SlopeCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.SlopeCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.SlopeCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.SlopeCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.SlopeCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.SlopeCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor.Value", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor.Value.A", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor.Value.B", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor.Value.G", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor.Value.R", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.SpecialSurfaceColor.Value.Type", "gDeveloperTools.CollisionViewer.SpecialSurfaceColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor", "gDeveloperTools.CollisionViewer.VoidCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor.Value", "gDeveloperTools.CollisionViewer.VoidCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.VoidCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.VoidCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.VoidCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.VoidCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.VoidCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.VoidCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor.Value", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor.Value" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor.Value.A", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor.Value.A" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor.Value.B", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor.Value.B" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor.Value.G", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor.Value.G" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor.Value.R", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor.Value.R" },
    { MigrationAction::Rename, "gCollisionViewer.WaterboxCollisionColor.Value.Type", "gDeveloperTools.CollisionViewer.WaterboxCollisionColor.Value.Type" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.Enabled", "gSettings.Graphics.AdvancedResolution.Enabled" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.AspectRatioX", "gSettings.Graphics.AdvancedResolution.AspectRatioX" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.AspectRatioY", "gSettings.Graphics.AdvancedResolution.AspectRatioY" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.IntegerScale.ExceedBoundsBy", "gSettings.Graphics.AdvancedResolution.IntegerScale.ExceedBoundsBy" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.IntegerScale.Factor", "gSettings.Graphics.AdvancedResolution.IntegerScale.Factor" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.PixelPerfectMode", "gSettings.Graphics.AdvancedResolution.PixelPerfectMode" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.VerticalResolutionToggle", "gSettings.Graphics.AdvancedResolution.VerticalResolutionToggle" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.VerticalPixelCount", "gSettings.Graphics.AdvancedResolution.VerticalPixelCount" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.UIComboItem.AspectRatio", "gSettings.Graphics.AdvancedResolution.UIComboItem.AspectRatio" },
    { MigrationAction::Rename, "gSettings.AdvancedResolution.UIComboItem.PixelCount", "gSettings.Graphics.AdvancedResolution.UIComboItem.PixelCount" },
    { MigrationAction::Rename, "gEnhancements.Sfx.MuteCarpenterSfx", "gAudioEditor.MuteCarpenterSfx" },
    { MigrationAction::Rename, "gEnhancements.Sfx.ChildGoronCry", "gAudioEditor.ChildGoronCry" },
    { MigrationAction::Rename, "gEnhancements.Sfx.LowHpAlarm", "gAudioEditor.LowHpAlarm" },
};
// clang-format on

} // namespace SOH
