#ifndef RANDO_SPOILER_H
#define RANDO_SPOILER_H

#include <vector>
#include <string>
#include "nlohmann/json.hpp"

namespace Rando {

namespace Spoiler {

extern std::vector<std::string> spoilerOptions;
void RefreshOptions();
void SelectSpoiler(s32 index);
nlohmann::json GenerateFromSaveContext();
void SaveToFile(const std::string& fileName, nlohmann::json spoiler);
nlohmann::json LoadFromFile(const std::string& filePath);
void ApplyToSaveContext(nlohmann::json spoiler);
bool HandleFileDropped(char* path);

// ---- Cross-game hints (OoT+MM combo) ----
// OoT area where an item that is NOT placed in MM ended up, e.g. "Kakariko Village".
// `riSpoilerName` is the item's spoilerName ("RI_REMAINS_ODOLWA"). Empty string if the item IS in MM,
// if there is no combo seed, or if the seed was generated by a soh build older than ootItemAreas.
//
// The data arrives in the combo spoiler (key "ootItemAreas") and is stored in a sidecar next to the
// save so it survives a restart: the spoiler is only applied when the file is created, but hints are
// read at any time.
std::string GetOotAreaForItem(const std::string& riSpoilerName);

// Writes the OoT area sidecar when a combo spoiler is applied. No-op if the object comes in empty.
void SaveOotItemAreas(uint32_t finalSeed, const nlohmann::json& ootItemAreas);

} // namespace Spoiler

} // namespace Rando

#endif
