#!/usr/bin/env python3
"""
Generate mm_2ship/LocationData.py from mm/2s2h/Rando/StaticData/Checks.cpp.

This gives each AP location an explicit RCTYPE so Regions.py can filter by
type rather than by fragile name-pattern matching.

Run from the repo root:
    python mm_2ship/tools/gen_location_rctypes.py

Re-run whenever Checks.cpp changes (new checks added, RCTYPE changed, etc.).
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CHECKS_CPP = REPO_ROOT / "mm" / "2s2h" / "Rando" / "StaticData" / "Checks.cpp"
OUTPUT = REPO_ROOT / "mm_2ship" / "LocationData.py"

# Matches:  RC(RC_SOME_NAME, RCTYPE_SOMETHING, ...)
RC_RE = re.compile(r"RC\(\s*(RC_\w+)\s*,\s*(RCTYPE_\w+)\s*,")


def main() -> None:
    if not CHECKS_CPP.exists():
        sys.exit(f"ERROR: {CHECKS_CPP} not found. Run from the repo root.")

    entries: list[tuple[str, str]] = []
    with open(CHECKS_CPP, encoding="utf-8") as f:
        for line in f:
            m = RC_RE.search(line)
            if m:
                rc_id = m.group(1)   # e.g. RC_TERMINA_FIELD_TALL_GRASS_CHEST
                rctype = m.group(2)  # e.g. RCTYPE_CHEST
                # Strip RC_ prefix → Python Locations enum key
                loc_key = rc_id[3:]  # e.g. TERMINA_FIELD_TALL_GRASS_CHEST
                entries.append((loc_key, rctype))

    if not entries:
        sys.exit("ERROR: No RC() entries found — check CHECKS_CPP path.")

    lines = [
        "# Auto-generated by mm_2ship/tools/gen_location_rctypes.py",
        "# Do not edit manually — re-run the script when Checks.cpp changes.",
        "",
        "# Maps each Locations enum key (UPPER_SNAKE_CASE) to its C++ RandoCheckType.",
        "# Used by Regions.location_should_be_included() for type-based filtering.",
        "LOCATION_RCTYPE: dict[str, str] = {",
    ]
    for loc_key, rctype in entries:
        lines.append(f'    "{loc_key}": "{rctype}",')
    lines.append("}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {OUTPUT}")


if __name__ == "__main__":
    main()
