#define INTENT_CONTROL_ROLL 1
#define INTENT_CONTROL_JUMP 2
#define INTENT_CONTROL_TALK 3

// Buttons for firing/shooting
#define INTENT_CONTROL_FIRE_BOW 4
#define INTENT_CONTROL_FIRE_HOOKSHOT 5

#define INTENT_HOTSWAP_ITEM_RIGHT 6
#define INTENT_HOTSWAP_ITEM_LEFT 7
#define INTENT_USE_ITEM 8

#define INTENT_HOTSWAP_ITEM_RIGHT2 9
#define INTENT_HOTSWAP_ITEM_LEFT2 10
#define INTENT_USE_ITEM2 11